// China directory: workbook numerical data is not published.
const CN=()=>window.CHINA_NICKEL;
const CN_PRODUCTS={npi:'镍生铁／镍铁',sulfate:'硫酸镍',refined:'纯镍'};
const cnOldGeoLinks=geoLinks;geoLinks=function(id){const p=CN().projects[id],l=geoLoc(id);return p&&l?`${wgCountryLinks(id)} › ${A('park',l.place_id,p.province)}${p.city?' · '+E(p.city):''}`:cnOldGeoLinks(id)};
function cnStats(){return `<div class="wg-statrow">${[['中国项目档案',Object.keys(CN().projects).length],...Object.entries(CN_PRODUCTS).map(([k,l])=>[l+'条目',Object.values(CN().projects).filter(p=>p.products.includes(k)).length])].map(([label,v])=>`<div><strong>${v}</strong><span>${label}</span></div>`).join('')}</div><p class="meta">同一企业可涉及多个产品，产品条目数不直接相加。</p>`}
const cnOldCountry=wgCountryPage;wgCountryPage=function(code){if(code!=='CN')return cnOldCountry(code);return cnOldCountry(code).replace(/<p class="lead">[\s\S]*?<\/p>/,'<p class="lead">中国目录连接镍铁原料、镍盐加工与纯镍生产。沿省份查工厂，沿集团查国内外项目，继续阅读企业介绍与加工关系。</p>').replace(wgStats(wgProjects(code)),cnStats()).replace('<input id="wgPlantQ"',`<select id="cnCountryProvince" aria-label="中国项目省份"><option value="">全部省份</option>${CN().provinces.map(p=>`<option>${E(p.name)}</option>`).join('')}</select><input id="wgPlantQ"`).replace('本地区条目主要来自2026年9月全球普查底表及已收录的海外加工资料。','中国目录按用户提供的企业清单整理，企业公开披露及关联资料在各项目正文列明。')};
const cnOldCountryProjects=wgProjects;wgProjects=function(code){const ps=cnOldCountryProjects(code);const prov=code==='CN'?document.getElementById('cnCountryProvince')?.value:'';return prov?ps.filter(p=>geoLoc(p.id)?.province===prov):ps};
const cnOldTrade=wikiTrade;wikiTrade=function(c){return CN().projects[c.p.id]?'<p>已核实的跨国供料与加工关系列在正文及关联项目中，可沿企业链接继续阅读。</p>':cnOldTrade(c)};
function cnRelations(id){const es=CN().relations.filter(e=>e.from===id||e.to===id);return es.length?`<section class="cn-relations"><h2>中国与海外加工关系</h2>${es.map(e=>`<p>${A('project',e.from,projectTitle(e.from))} → ${A('project',e.to,projectTitle(e.to))}</p><p>${E(e.label)} <a href="${E(e.url)}" target="_blank" rel="noopener">公司披露 ↗</a></p>`).join('')}</section>`:''}
const cnOldWiki=wikiArticle;wikiArticle=function(id){return cnOldWiki(id).replace('<section id="wiki-sources"',cnRelations(id)+'<section id="wiki-sources"')};
const cnOldWgRoute=wgRoute;wgRoute=function(k,id){return k==='china-production'?'<div class="kicker">中国项目</div><h1>中国企业与项目目录</h1><p>表格数据展示已撤下。</p><p><a href="#/country/CN">查看中国项目目录 →</a></p>':cnOldWgRoute(k,id)};
const cnOldWgBind=wgBind;wgBind=function(k,id){cnOldWgBind(k,id);if(k==='country'&&id==='CN'){$('cnCountryProvince').onchange=wgPlantRows;const old=$('wgPlantReset').onclick;$('wgPlantReset').onclick=()=>{$('cnCountryProvince').value='';old()}}};
