// China source-series are loaded only when a China chart is opened.
const CN=()=>window.CHINA_NICKEL;
Object.assign(OP_LABELS,{recorded:'有生产记录（资料期）'});
const CN_PRODUCTS={npi:'镍生铁／镍铁',sulfate:'硫酸镍',refined:'纯镍'};
const cnOldGeoLinks=geoLinks;geoLinks=function(id){const p=CN().projects[id],l=geoLoc(id);return p&&l?`${wgCountryLinks(id)} › ${A('park',l.place_id,p.province)}${p.city?' · '+E(p.city):''}`:cnOldGeoLinks(id)};
let cnSeriesPromise;
const cnSeries=()=>cnSeriesPromise??=fetch('library/china-series.json').then(r=>{if(!r.ok)throw Error('月度资料加载失败');return r.json()}).then(d=>d.series).catch(e=>{cnSeriesPromise=null;throw e});
function cnOptions(ps){return ps.map(p=>`<option value="${p.id}">${E(p.name)}</option>`).join('')}
function cnPanel(id=''){const p=CN().projects[id];return `<section id="china-production" data-project="${id}" class="cn-production"><h2>${p?'产品与产线月度记录':'中国项目月度数据'}</h2><p>按原表期间和字段查看。默认排除2026年9月及之后的未完结／未来月份；历史实绩与预测分界待原表口径确认。</p><div class="filters"><select id="cnProduct" aria-label="产品"><option value="npi">镍生铁／镍铁</option><option value="sulfate">硫酸镍</option><option value="refined">纯镍</option></select>${p?'':`<select id="cnProvince" aria-label="月度数据省份"><option value="">全部省份</option>${CN().provinces.map(p=>`<option>${E(p.name)}</option>`).join('')}</select><select id="cnProject" aria-label="月度项目"><option value="">同产品样本合计</option>${cnOptions(Object.values(CN().projects))}</select>`}<select id="cnLine" aria-label="统计产线"><option value="">全部有效产线</option></select><select id="cnYear" aria-label="数据年份"><option value="2026">2026</option></select><select id="cnMetric" aria-label="数量口径"><option value="nickel">镍金属量／纯镍表产量</option><option value="physical">实物产量（吨）</option><option value="capacity_ni">原表月产能</option></select><label class="cn-future"><input id="cnFuture" type="checkbox">包含未完结／未来列</label><button id="cnDownload">下载当前明细</button></div><p id="cnMessage" class="meta" role="status">正在加载月度数据…</p><div id="cnChart" class="ix-plot"></div><p id="cnPoint" class="cn-point" aria-live="polite">点击月份查看数值与可用记录数。</p><div id="cnRows"></div><details class="reading-notes"><summary>原料、自用量与原始行</summary><p>硫酸镍表“用量”和纯镍表按原料划分的“产量”按原字段展示，不把两者相加。可流通量是原表差额，不视为实际销量。公式错误与空白不按零处理。</p><div id="cnRaw"></div></details><div class="actions"><a href="library/china-register.csv" download>项目与原表行对照 ↓</a><a href="library/china-monthly.csv" download>中国月度明细全表 ↓</a><a href="library/china-import-notes.md">资料说明 →</a></div></section>`}
function cnHome(){return `<div class="kicker"><a href="#/country/CN">中国大陆镍产业</a> / 月度资料</div><h1>中国镍产能与月度产量</h1><p class="lead">把镍生铁、纯镍和硫酸镍放在同一资料库，按省份、项目和产线查看。产品分别统计，中间品与后续纯镍产量不相加。</p>${cnPanel()}`}
function cnStats(){return `<div class="wg-statrow">${[['中国项目档案',Object.keys(CN().projects).length],...Object.entries(CN_PRODUCTS).map(([k,l])=>[l+'条目',Object.values(CN().projects).filter(p=>p.products.includes(k)).length])].map(([label,v])=>`<div><strong>${v}</strong><span>${label}</span></div>`).join('')}</div><p class="meta">同一企业可涉及两个产品，因此产品条目数不直接相加；集团合计不另算一家工厂。</p>`}
const cnOldCountry=wgCountryPage;wgCountryPage=function(code){if(code!=='CN')return cnOldCountry(code);let html=cnOldCountry(code);html=html.replace(/<p class="lead">[\s\S]*?<\/p>/,'<p class="lead">中国目录连接镍铁原料、镍盐加工与纯镍生产。沿省份查工厂，沿集团查国内外项目，再进入逐月产能、产量和原料结构。</p>').replace(wgStats(wgProjects(code)),cnStats()).replace('<section><h2>工厂与项目</h2>','<div class="actions"><a href="#/china-production">交互月度产量与产能 →</a><a href="library/china-register.csv" download>中国项目表 ↓</a></div><section><h2>工厂与项目</h2>').replace('<input id="wgPlantQ"',`<select id="cnCountryProvince" aria-label="中国项目省份"><option value="">全部省份</option>${CN().provinces.map(p=>`<option>${E(p.name)}</option>`).join('')}</select><input id="wgPlantQ"`).replace('本地区条目主要来自2026年9月全球普查底表及已收录的海外加工资料。','中国条目来自本次提供的两份中国项目／月度表，共190条产品或产线记录，整理为170个档案；部分主要基地已补充公司披露。');return html};
const cnOldCountryProjects=wgProjects;wgProjects=function(code){const ps=cnOldCountryProjects(code);const prov=code==='CN'?document.getElementById('cnCountryProvince')?.value:'';return prov?ps.filter(p=>geoLoc(p.id)?.province===prov):ps};
const cnOldTrade=wikiTrade;wikiTrade=function(c){if(CN().projects[c.p.id])return '<p>本次资料提供国内产能、月度生产与原料结构。它们不属于海关逐票发货，不能替代实际客户或出口明细。已核实的跨国加工关系在下方列示，可继续进入相关项目。</p>';return cnOldTrade(c)};
function cnRelations(id){const es=CN().relations.filter(e=>e.from===id||e.to===id);return es.length?`<section class="cn-relations"><h2>中国与海外加工关系</h2>${es.map(e=>`<p>${A('project',e.from,projectTitle(e.from))} → ${A('project',e.to,projectTitle(e.to))}</p><p>${E(e.label)} <a href="${E(e.url)}" target="_blank" rel="noopener">公司披露 ↗</a></p>`).join('')}</section>`:''}
const cnOldWiki=wikiArticle;wikiArticle=function(id){let html=cnOldWiki(id);if(CN().projects[id])html=html.replace('<section id="wiki-trade">',cnPanel(id)+'<section id="wiki-trade">').replace('<a href="#" data-scroll="wiki-trade">','<a href="#" data-scroll="china-production">月度产能与产量</a><a href="#" data-scroll="wiki-trade">');return html.replace('<section id="wiki-sources"',cnRelations(id)+'<section id="wiki-sources"')};
const cnOldProfile=ptProfile;ptProfile=function(id){const p=cnOldProfile(id),c=CN().projects[id];if(c){p.production=c.last_positive_record?'最近正产量记录：'+c.last_positive_record+'；进入项目查看月度序列。':'原表尚无可用正产量记录';p.capacity=WIKI_ARTICLES[id].sections.find(s=>s.title==='工艺与产能记录')?.paragraphs.slice(1).join('\n')||p.capacity}return p};
let cnState={};
async function cnMount(){const root=$('china-production');if(!root)return;const pid=root.dataset.project,p=CN().projects[pid];const token={root};cnState={token,pid,rows:[]};try{const all=await cnSeries();if(!$('china-production')||$('china-production')!==root||cnState.token!==token)return;cnState.all=all;const available=p?p.products:['npi','sulfate','refined'];$('cnProduct').innerHTML=available.map(k=>`<option value="${k}">${CN_PRODUCTS[k]}</option>`).join('');cnUpdateOptions(true);for(const id of ['cnProduct','cnProvince','cnProject'])if($(id))$(id).onchange=()=>{cnUpdateOptions(id!=='cnProject');cnDraw()};for(const id of ['cnLine','cnYear','cnMetric','cnFuture'])$(id).onchange=cnDraw;$('cnDownload').onclick=()=>ixDownload([['项目','统计行','产品','省份','月份','期间性质','实物吨','镍金属量／纯镍表产量','月产能','原料原始字段','文件','工作表','行'],...cnState.rows.map(({s,r})=>[s.name,s.id,CN_PRODUCTS[s.product],s.province,r.month,r.period_type,r.physical??'',r.nickel??'',r.capacity_ni??'',JSON.stringify(r.feed_fields||{}),s.source_file,s.source_sheet,(r.source_rows||[s.source_row]).join(';')])],'中国项目月度记录.csv');cnDraw()}catch(e){if($('cnMessage'))$('cnMessage').textContent='月度数据未能加载，请刷新页面重试。'}}
function cnUpdateOptions(resetProject=false){const product=$('cnProduct').value,prov=$('cnProvince')?.value||'',fixed=cnState.pid;let ps=Object.values(CN().projects).filter(p=>p.products.includes(product)&&(!prov||p.province===prov));if($('cnProject')){let old=resetProject?'':$('cnProject').value;$('cnProject').innerHTML='<option value="">同产品样本合计</option>'+cnOptions(ps);$('cnProject').value=ps.some(p=>p.id===old)?old:''}const pid=fixed||$('cnProject')?.value||'',lines=Object.values(cnState.all).filter(s=>s.product===product&&(!prov||s.province===prov)&&(!pid||s.project_id===pid));$('cnLine').innerHTML='<option value="">'+(pid?'项目各独立产线':'样本内各独立产线')+'</option>'+lines.map(s=>`<option value="${s.id}">${E(s.name)} · ${s.id}${s.alias_of?'（别名原行）':''}</option>`).join('');const years=[...new Set(lines.flatMap(s=>s.records.map(r=>r.month.slice(0,4))))].sort().reverse(),old=$('cnYear').value;$('cnYear').innerHTML='<option value="">全部年份</option>'+years.map(y=>`<option>${y}</option>`).join('');$('cnYear').value=years.includes(old)?old:years.includes('2026')?'2026':years[0]||'';$('cnMetric').querySelector('[value="physical"]').disabled=product==='refined';if(product==='refined'&&$('cnMetric').value==='physical')$('cnMetric').value='nickel'}
function cnDraw(){if(!cnState.all)return;const product=$('cnProduct').value,province=$('cnProvince')?.value||'',pid=cnState.pid||$('cnProject')?.value||'',line=$('cnLine').value,year=$('cnYear').value,metric=$('cnMetric').value,future=$('cnFuture').checked;
const candidates=Object.values(cnState.all).filter(s=>s.product===product&&(!province||s.province===province)&&(!pid||s.project_id===pid)&&(!line||s.id===line));const lines=candidates.filter(s=>line||!s.aggregate_exclude);const rows=lines.flatMap(s=>s.records.filter(r=>(!year||r.month.startsWith(year))&&(future||r.month<'2026-09')).map(r=>({s,r})));cnState.rows=rows;const by={};for(const {s,r}of rows){const x=by[r.month]??={key:r.month,value:0,count:0,total:lines.length};if(typeof r[metric]==='number'){x.value+=r[metric];x.count++}}
const all=Object.values(by).sort((a,b)=>a.key.localeCompare(b.key)),buckets=all.filter(x=>x.count);let unit=metric==='physical'?'实物吨':product==='refined'?'纯镍表数值（吨口径）':'镍金属吨';$('cnMessage').textContent=`${lines.length}条统计行 · ${rows.length}条月份记录 · ${pid?'项目范围':'同产品样本，不代表全国全量'} · ${candidates.length-lines.length}条别名或边界未清行未重复汇总。${product==='refined'?'纯镍表未在每列重列单位，保留原始数值；月产能不年化。':''}`;
$('cnChart').innerHTML=buckets.length?ixSvg(buckets,{unit,width:Math.max(320,$('cnChart').clientWidth||700)}):'<p>当前筛选没有可用数值。缺数未按零填充。</p>';
ixMarkEvents($('cnChart'),buckets,b=>{$('cnPoint').textContent=`${b.key}：${F(b.value)} ${unit}；${b.count}/${b.total}条统计行有数。${b.key>='2026-09'?'未完结／未来月份。':'原表月度记录。'}`;$('cnRows').querySelectorAll('tr').forEach(tr=>tr.classList.toggle('wg-highlight',tr.dataset.month===b.key))},unit);
$('cnRows').innerHTML=`<div class="table-wrap"><table><thead><tr><th>月份</th><th>${E(unit)}</th><th>有数／所选统计行</th><th>期间说明</th></tr></thead><tbody>${all.map(r=>`<tr data-month="${r.key}"><td>${r.key}</td><td>${r.count?F(r.value):'缺少数值'}</td><td>${r.count} / ${r.total}</td><td>${r.key>='2026-09'?'未完结／未来列':'原表记录'}</td></tr>`).join('')}</tbody></table></div>`;
const raw=rows.slice().sort((a,b)=>b.r.month.localeCompare(a.r.month));$('cnRaw').innerHTML=`<p class="meta">展示最近${Math.min(raw.length,60)}条，可下载当前全部明细。有数行数不足时，月度合计只包括已填数的记录。</p><div class="table-wrap"><table><thead><tr><th>项目／产线</th><th>月份</th><th>原料字段</th><th>自用／可流通</th><th>原表位置</th></tr></thead><tbody>${raw.slice(0,60).map(({s,r})=>`<tr><td>${A('project',s.project_id,projectTitle(s.project_id))}<span class="sub">${E(s.name)}</span></td><td>${r.month}</td><td>${Object.entries(r.feed_fields||{}).filter(([k,v])=>v!==0).map(([k,v])=>`${E(k)}：${F(v)}`).join('<br>')||'未列非零记录'}</td><td>${r.own_use!=null?'自用：'+F(r.own_use):''}${r.available!=null?'<br>可流通：'+F(r.available):''}</td><td>${E(s.source_sheet)} 第${(r.source_rows||[s.source_row]).join('、')}行<span class="sub">${E(s.source_file)}</span></td></tr>`).join('')}</tbody></table></div>`;
}
const cnOldWgRoute=wgRoute;wgRoute=function(k,id){return k==='china-production'?cnHome():cnOldWgRoute(k,id)};
const cnOldWgBind=wgBind;wgBind=function(k,id){cnOldWgBind(k,id);if(k==='country'&&id==='CN'){$('cnCountryProvince').onchange=wgPlantRows;const old=$('wgPlantReset').onclick;$('wgPlantReset').onclick=()=>{$('cnCountryProvince').value='';old()}}if($('china-production'))cnMount()};
