// China directory: workbook numerical data is not published.
const CN=()=>window.CHINA_NICKEL;
const CN_PRODUCTS={npi:'镍生铁／镍铁',sulfate:'硫酸镍',refined:'纯镍'};
const cnOldGeoLinks=geoLinks;geoLinks=function(id){const p=CN().projects[id],l=geoLoc(id);return p&&l?`${wgCountryLinks(id)} › ${A('park',l.place_id,p.province)}${p.city?' · '+E(p.city):''}`:cnOldGeoLinks(id)};
function cnStats(){return `<div class="wg-statrow">${[['中国项目档案',Object.keys(CN().projects).length],...Object.entries(CN_PRODUCTS).map(([k,l])=>[l+'条目',Object.values(CN().projects).filter(p=>p.products.includes(k)).length])].map(([label,v])=>`<div><strong>${v}</strong><span>${label}</span></div>`).join('')}</div><p class="meta">同一企业可涉及多个产品，产品条目数不直接相加。</p>`}
const cnOldCountry=wgCountryPage;wgCountryPage=function(code){if(code!=='CN')return cnOldCountry(code);return cnOldCountry(code).replace(/<p class="lead">[\s\S]*?<\/p>/,'<p class="lead">中国目录连接镍铁原料、镍盐加工与纯镍生产。沿省份查工厂，沿集团查国内外项目，继续阅读企业介绍与加工关系。</p>').replace(wgStats(wgProjects(code)),cnStats()).replace('<h2>工厂与项目</h2>','<h2>工厂与项目</h2><p class="meta">状态按所列资料年份记录。“历史已投产”表示曾有生产记录，近期运行情况仍需更新；集团总览与生产工厂分别列示。</p>').replace('<input id="wgPlantQ"',`<select id="cnCountryProvince" aria-label="中国项目省份"><option value="">全部省份</option>${CN().provinces.map(p=>`<option>${E(p.name)}</option>`).join('')}</select><input id="wgPlantQ"`).replace('本地区条目主要来自2026年9月全球普查底表及已收录的海外加工资料。','中国目录按用户提供的企业清单整理，企业公开披露及关联资料在各项目正文列明。')};
const cnOldCountryProjects=wgProjects;wgProjects=function(code){const ps=cnOldCountryProjects(code);const prov=code==='CN'?document.getElementById('cnCountryProvince')?.value:'';return prov?ps.filter(p=>geoLoc(p.id)?.province===prov):ps};
const cnOldTrade=wikiTrade;wikiTrade=function(c){return CN().projects[c.p.id]?'<p>已核实的跨国供料与加工关系列在正文及关联项目中，可沿企业链接继续阅读。</p>':cnOldTrade(c)};
function cnRelations(id){const es=CN().relations.filter(e=>e.from===id||e.to===id);return es.length?`<section class="cn-relations"><h2>中国与海外加工关系</h2>${es.map(e=>`<p>${A('project',e.from,projectTitle(e.from))} → ${A('project',e.to,projectTitle(e.to))}</p><p>${E(e.label)} <a href="${E(e.url)}" target="_blank" rel="noopener">公司披露 ↗</a></p>`).join('')}</section>`:''}
const cnOldWiki=wikiArticle;wikiArticle=function(id){return cnOldWiki(id).replace('<section id="wiki-sources"',cnRelations(id)+'<section id="wiki-sources"')};
const cnOldWgRoute=wgRoute;wgRoute=function(k,id){return k==='china-production'?'<div class="kicker">中国项目</div><h1>中国企业与项目目录</h1><p>表格数据展示已撤下。</p><p><a href="#/country/CN">查看中国项目目录 →</a></p>':cnOldWgRoute(k,id)};
const cnOldWgBind=wgBind;wgBind=function(k,id){cnOldWgBind(k,id);if(k==='country'&&id==='CN'){$('cnCountryProvince').onchange=wgPlantRows;const old=$('wgPlantReset').onclick;$('wgPlantReset').onclick=()=>{$('cnCountryProvince').value='';old()}}};

// Connect researched Chinese entities without duplicating their physical plants.
CN_PRODUCTS.other='其他／历史产业';CN_PRODUCTS.matte='冰镍加工';
function cnRelatedReading(id){const ids=(window.WIKI_ARTICLES[id]?.related_projects||[]).filter(pid=>U().projects.some(p=>p.id===pid));return ids.length?`<section class="cn-related-reading"><h2>关联企业与继续阅读</h2><p>沿集团、实际厂区和加工关系继续查看；具体关系在各条正文中说明。</p><div class="entries">${ids.map(pid=>{const a=window.WIKI_ARTICLES[pid];return `<article class="entry"><h3>${A('project',pid,projectTitle(pid))}</h3><p>${E(a?.intro||'')}</p></article>`}).join('')}</div></section>`:''}
const cnResearchWiki=wikiArticle;wikiArticle=function(id){return cnResearchWiki(id).replace('<section id="wiki-sources"',cnRelatedReading(id)+'<section id="wiki-sources"')};
function cnIndustryReading(){return `<section class="cn-industry-reading"><h2>中国镍产业的三条发展路线</h2><div class="entries"><article class="entry"><h3>镍铁与不锈钢基地</h3><p>一些项目由独立镍铁冶炼起步，另一些与炼钢、轧钢配套建设。后来的转产、重组和海外投资，改变了各厂在产业链中的位置。</p><p>${['CN005','CN023','CN031','CN032','CN033','CN065','CN069'].map(id=>A('project',id,projectTitle(id))).join(' · ')}</p></article><article class="entry"><h3>镍盐与资源循环</h3><p>镍盐企业的原料各不相同：有的衔接矿冶资源，有的处理进口中间品，也有的从废电池和工业废料中回收镍。看清原料和工序，才能理解它们为什么建厂、卖给谁。</p><p>${['CN083','CN085','CN087','CN092','CN111','CN125'].map(id=>A('project',id,projectTitle(id))).join(' · ')}</p></article><article class="entry"><h3>精炼镍与跨国加工</h3><p>金川等矿冶基地有较长的金属镍生产历史。中伟、华友、格林美等企业则在海外原料与国内材料业务之间增加精炼镍选择，逐步形成跨国加工联系。</p><p>${['CN153','CN082','CN155','CN156','CN164','CN149','CN167'].map(id=>A('project',id,projectTitle(id))).join(' · ')}</p></article></div></section>`}
const cnResearchCountry=wgCountryPage;wgCountryPage=function(code){let html=cnResearchCountry(code);return code==='CN'?html.replace('<div class="filters">',cnIndustryReading()+'<div class="filters">'):html};

const cnReadableStatus=wikiArticle;wikiArticle=function(id){let html=cnReadableStatus(id);if(CN().projects[id])html=html.replace(/<div class="fact-row"><dt>岛屿<\/dt>[\s\S]*?<\/div>/,'');if(CN().projects[id]&&opGet(id)?.key==='unknown'){html=html.replace(/<section class="op-panel"[\s\S]*?<\/section>/,'');}return html};
