// Wikipedia-style country articles (library/country-articles.json) placed above each country's plant directory.
// Text markup: [n] cites source n; {{P:id|名}} / {{G:id|名}} / {{C:code|名}} link a project, group or country.
function caArticle(code){return window.COUNTRY_ARTICLES?.articles?.[code]}
function caCite(a,nums){const ns=nums.filter(n=>a.sources.some(s=>s.n===n));return ns.length?`<sup class="wiki-cites">${ns.map(n=>`<a href="#" data-scroll="cref-${n}" title="${E(a.sources.find(s=>s.n===n).title)}">[${n}]</a>`).join('')}</sup>`:''}
function caText(a,t){const route={P:'project',G:'group',C:'country'};let out='',last=0;const re=/\{\{([PGC]):([^|}]+)\|([^}]+)\}\}|((?:\[\d+(?:[,，]\s*\d+)*\])+)/g;let m;
 const plain=s=>E(s);while((m=re.exec(t))){out+=plain(t.slice(last,m.index));if(m[1])out+=`<a href="#/${route[m[1]]}/${E(m[2])}">${E(m[3])}</a>`;else out+=caCite(a,(m[4].match(/\d+/g)||[]).map(Number));last=re.lastIndex}return out+plain(t.slice(last))}
function caInfobox(code,a){const c=wgCountry(code),ps=wgProjects(code);return `<aside class="infobox country-infobox"><h3>${c.flag} ${E(a.title)}</h3><dl>${a.facts.map(([k,v,r])=>`<dt>${E(k)}</dt><dd>${caText(a,String(v))}${caCite(a,r||[])}</dd>`).join('')}<dt>本站收录</dt><dd><a href="#" data-scroll="country-plants">${ps.length}份工厂与项目档案</a>${code==='CN'?'':`，其中${homeActive(ps)}项在产／部分生产`}</dd></dl></aside>`}
function caBlock(code,a){return `<div class="wiki-layout country-article no-autolink"><article class="wiki-prose"><p class="wiki-intro">${caText(a,a.intro)}</p><nav class="wiki-toc" aria-label="本条目录"><strong>目录</strong>${a.sections.map((s,i)=>`<a href="#" data-scroll="country-section-${i}">${i+1}. ${E(s.title)}</a>`).join('')}<a href="#" data-scroll="country-plants">工厂与项目</a><a href="#" data-scroll="country-refs">参考资料</a></nav>${a.sections.map((s,i)=>`<section id="country-section-${i}"><h2>${E(s.title)}</h2>${s.paragraphs.map(p=>`<p>${caText(a,p)}</p>`).join('')}</section>`).join('')}</article>${caInfobox(code,a)}</div>`}
function caRefs(a){return `<section id="country-refs" class="reading-notes reading-information"><h2>参考资料</h2><ol>${a.sources.map(s=>`<li id="cref-${s.n}" value="${s.n}">${s.publisher?E(s.publisher)+'：':''}<a href="${E(s.url)}" target="_blank" rel="noopener">${E(s.title)}</a>${s.date?`（${E(s.date)}）`:''}</li>`).join('')}</ol><p class="meta">条目更新于${E(a.updated_at||window.COUNTRY_ARTICLES.asof||'')}。工厂运行状态以各项目条目为准。</p></section>`}
const caOldCountry=wgCountryPage;wgCountryPage=function(code){let html=caOldCountry(code);const a=caArticle(code);if(!a)return html;
 return html.replace(/<p class="lead">[\s\S]*?<\/p>/,caBlock(code,a)).replace('<section><h2>工厂与项目</h2>','<section id="country-plants"><h2>工厂与项目</h2>').replace('<section class="reading-information"><h2>资料说明</h2>',caRefs(a)+'<section class="reading-information"><h2>资料说明</h2>')};
