const EX_NAMES={npi:'镍铁',low:'低冰镍',high:'高冰镍',mhp:'MHP',sulfate:'硫酸镍',refined:'精炼镍',other:'另列冰镍记录'};
let exByProject=null,exRowsCurrent=[],exLimit=100;
function exIndex(){if(!exByProject){exByProject={};for(const r of window.EXPORTS.records)(exByProject[r.project]??=[]).push(r)}return exByProject}
function exProjectRows(id){return exIndex()[id]||[]}
function exSum(rs){return rs.reduce((s,r)=>s+Number(r.counted||0),0)}
function exKinds(rs){return Object.keys(EX_NAMES).filter(k=>rs.some(r=>r.product===k))}
function exLink(target,kind,label){return `<a href="#/exports/${E(target)}~${kind}">${E(label||EX_NAMES[kind])}</a>`}
function exportMiniLinks(id){let rs=exProjectRows(id);return exKinds(rs).map(k=>exLink(id,k,EX_NAMES[k]+' '+rs.filter(r=>r.product===k).length+'条')).join('<br>')||(['NPI058','NPI072'].includes(id)?exLink('ANTAM集团','npi','ANTAM集团记录'):'<span class="meta">暂无匹配记录</span>')}
function exMonthChart(rs){if(!rs.length)return '';let months=[...new Set(window.EXPORTS.records.map(r=>r.month))].sort(),vals=months.map(m=>exSum(rs.filter(r=>r.month===m))),max=Math.max(...vals,1);return `<div class="ex-chart"><svg viewBox="0 0 960 215" role="img" aria-label="月度出口实物吨"><line x1="10" y1="175" x2="950" y2="175" stroke="#cdd5dc"/>${vals.map((v,i)=>{let x=12+i*21,h=v/max*135;return `<rect x="${x}" y="${175-h}" width="15" height="${h}" fill="#a51b25"><title>${months[i]}：${F(v)} 实物吨</title></rect>${i%6===0?`<text x="${x}" y="200" font-size="12" fill="#58646c">${months[i]}</text>`:''}`}).join('')}<text x="10" y="20" font-size="12" fill="#58646c">最高月 ${F(max)} 实物吨</text></svg></div>`}
function exAnnual(rs){let ys=[...new Set(rs.map(r=>r.date.slice(0,4)))].sort();return `<div class="stat-row">${ys.map(y=>`<div><strong>${F(exSum(rs.filter(r=>r.date.startsWith(y))))}</strong><span>${y}${y==='2026'?'年截至8月':'年'} · 实物吨</span></div>`).join('')}</div>`}
function exBuyers(rs,limit=8){let map={};for(const r of rs){let key=r.customer||r.buyer;let b=map[key]??={name:r.buyer,customer:r.customer,tonnes:0,records:0};b.tonnes+=r.counted||0;b.records++}let a=Object.values(map).sort((a,b)=>b.tonnes-a.tonnes),total=exSum(rs);return `<div class="table-wrap"><table><thead><tr><th>买方／客户词条</th><th>实物吨</th><th>占比</th><th>记录</th></tr></thead><tbody>${a.slice(0,limit).map(b=>`<tr><td>${b.customer?A('customer',b.customer,b.name):E(b.name)}</td><td>${F(b.tonnes)}</td><td>${total?(b.tonnes/total*100).toFixed(1)+'%':'—'}</td><td>${b.records}</td></tr>`).join('')}</tbody></table></div>${a.length>limit?`<p class="meta">列出前${limit}个买方；逐票页面可查看和下载完整结果。</p>`:''}`}
function exNotes(kind){return kind==='sulfate'?'硫酸镍按实物吨列示；不使用统一22.2%作为实测品位。同票特征的跨抬头记录保留原行，复核参考合计仅计一次，原始重量仍可下载。':kind==='refined'?'精炼镍按原始货描及实物重量列示；出口抬头、品牌交割资格和实际终端用途分别阅读。':kind==='low'?'低冰镍沿用原复核库的候选范围，逐票保留原货描、品位及识别标签。':kind==='high'?'高冰镍沿用原复核库的关联范围，货描及品位支持记录与假设品位记录分别标注。':kind==='mhp'?'MHP重量为实物吨；原文品位与估算品位分开保留，不用湿重直接折算镍金属量。':kind==='other'?'这些记录沿用原库的单列范围，原票重量可查，不计入主口径实物吨。':'商业镍铁记录沿用原核查范围；样品、疑低冰和性质待核记录可在原核查表中查看。2025年10月来源为残月。'}
function exportProject(c){let rs=exProjectRows(c.p.id),ks=exKinds(rs);if(!ks.length)return `<p>本库暂无与本项目直接匹配的出口记录。</p>${['NPI058','NPI072'].includes(c.p.id)?`<p>ANTAM的出口按集团抬头记录，未分配到单厂。${exLink('ANTAM集团','npi','查看集团镍铁记录 →')}</p>`:''}<a href="#/exports">进入统一出口查询 →</a>`;return `<div class="ex-tabs">${ks.map(k=>exLink(c.p.id,k,EX_NAMES[k]+' · '+rs.filter(r=>r.product===k).length+'条')).join('')}</div>${ks.map(k=>{let a=rs.filter(r=>r.product===k),dates=a.map(r=>r.date).sort();return `<section class="ex-product"><h3>${EX_NAMES[k]}出口</h3><p>${dates[0]}—${dates.at(-1)} · ${a.length}条记录 · ${F(exSum(a))}${k==='sulfate'?'参考实物吨':'实物吨'}</p>${exRawNote(a)}${exAnnual(a)}${exMonthChart(a)}${exBuyers(a)}<p>${exLink(c.p.id,k,'查看全部'+EX_NAMES[k]+'逐票记录 →')}</p><p class="meta">${exNotes(k)}</p></section>`}).join('')}<p class="meta">资料说明：各产品分别统计，出口记录不等于自产产量；境内供料及长期协议见正文和客户词条。</p>`}
function exContext(id=''){let [target='',kind='']=id.split('~');return {target,kind:EX_NAMES[kind]?kind:'npi'}}
function exBase(target){let a=window.EXPORTS.records;if(!target)return a;if(target.startsWith('park:'))return a.filter(r=>geoLoc(r.project)?.place_id===target.slice(5));if(target.startsWith('island:'))return a.filter(r=>geoLoc(r.project)?.island_id===target.slice(7));if(target.startsWith('customer:'))return a.filter(r=>r.customer===target.slice(9));return a.filter(r=>r.project===target)}
function exportsHome(id){let c=exContext(id),base=exBase(c.target);if(!base.some(r=>r.product===c.kind)&&!id?.includes('~'))c.kind=exKinds(base)[0]||'npi';let context=c.target.startsWith('park:')?geoPlace(c.target.slice(5))?.name:c.target.startsWith('island:')?G().islands.find(i=>i.id===c.target.slice(7))?.name:c.target.startsWith('customer:')?U().customers.find(x=>x.id===c.target.slice(9))?.name:U().projects.find(x=>x.id===c.target)?.name||c.target;return `<div class="kicker">贸易资料 / 统一查询</div><h1>出口与客户记录</h1><p class="lead">镍铁、低冰镍、高冰镍、MHP、硫酸镍和精炼镍使用同一套查询方式。按产品查看趋势、客户和每条发货，再回到企业或园区词条。</p>${c.target?`<div class="ex-context">当前范围：${E(context)} <a href="#/exports">查看全部 →</a>${U().projects.some(p=>p.id===c.target)?` · ${A('project',c.target,'返回项目')}`:''}</div>`:''}<div class="ex-tabs">${Object.keys(EX_NAMES).map(k=>exLink(c.target,k,EX_NAMES[k]+' · '+base.filter(r=>r.product===k).length+'条')).join('')}</div><div class="filters"><select id="exProduct" aria-label="出口产品">${Object.entries(EX_NAMES).map(([k,v])=>`<option value="${k}" ${c.kind===k?'selected':''}>${v}</option>`).join('')}</select><select id="exPlace" aria-label="出口园区"><option value="">全部园区与区域</option>${G().places.map(p=>`<option value="${p.id}">${E(p.name)}</option>`).join('')}</select><select id="exProject" aria-label="出口企业"><option value="">全部出口企业</option>${[...new Set(base.map(r=>r.project))].sort().map(pid=>`<option value="${E(pid)}">${E(U().projects.find(p=>p.id===pid)?.name||pid)}</option>`).join('')}</select><select id="exYear" aria-label="出口年份"><option value="">全部年份</option>${[...new Set(base.map(r=>r.date.slice(0,4)))].sort().map(y=>`<option>${y}</option>`).join('')}</select><input id="exQ" aria-label="搜索出口明细" placeholder="查买方、出口商、货描或原票编号"><button id="exDownload" class="linkbutton">下载筛选明细</button></div><div id="exStats"></div><section><h2>年度与月度出口</h2><div id="exTrend"></div></section><section><h2>买方与客户</h2><div id="exBuyers"></div></section><section><h2>逐票发货记录</h2><p id="exCount" class="meta"></p><div id="exRows"></div><button id="exMore" class="linkbutton">再显示100条</button></section><section><h2>资料说明</h2><p>${E(window.EXPORTS.note)}</p><p id="exNote"></p><div class="actions">${Object.values(window.EXPORTS.sources).map(s=>`<a href="${s.url}" download>${s.label} ↓</a>`).join('')}<a href="#/trade">冰镍供销关系与协议 →</a><a href="#/npi-trade">原镍铁核查视图 →</a><a href="#/mhp-trade">原MHP核查视图 →</a></div></section>`}
function exportsRows(target,reset=true){if(reset)exLimit=100;let k=$('exProduct').value,place=$('exPlace').value,p=$('exProject').value,y=$('exYear').value,q=$('exQ').value.trim().toLowerCase();let rs=exBase(target).filter(r=>r.product===k&&(!place||geoLoc(r.project)?.place_id===place)&&(!p||r.project===p)&&(!y||r.date.startsWith(y))&&(!q||[r.exporter,r.buyer,r.description,r.id].join(' ').toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));exRowsCurrent=rs;$('exStats').innerHTML=`<div class="numbers"><div class="number"><strong>${F(rs.length)}</strong><span>${EX_NAMES[k]}记录</span></div><div class="number"><strong>${F(exSum(rs))}</strong><span>${k==='sulfate'?'复核参考实物吨':'主口径实物吨'}</span></div><div class="number"><strong>${new Set(rs.map(r=>r.exporter)).size}</strong><span>出口抬头</span></div><div class="number"><strong>${new Set(rs.map(r=>r.buyer)).size}</strong><span>买方抬头</span></div></div>`;$('exTrend').innerHTML=rs.length?exRawNote(rs)+exAnnual(rs)+exMonthChart(rs):'<p>当前筛选没有匹配记录。</p>';$('exBuyers').innerHTML=exBuyers(rs,40);$('exRows').innerHTML=`<div class="table-wrap"><table><thead><tr><th>日期／来源</th><th>出口企业／地点</th><th>买方</th><th>实物吨／产品</th><th>原票内容</th></tr></thead><tbody>${rs.slice(0,exLimit).map(r=>`<tr><td>${r.date}<span class="sub">${r.id} · 原${r.source==='matte'?'序号':'行'}${r.source_row}</span></td><td>${U().projects.some(p=>p.id===r.project)?A('project',r.project,r.exporter):E(r.exporter)}<span class="sub">${geoLinks(r.project)}</span></td><td>${r.customer?A('customer',r.customer,r.buyer):E(r.buyer)}</td><td>${F(r.tonnes)}<span class="sub">${E(r.classification)}</span>${r.counted!==r.tonnes?`<span class="sub">${E(r.review_note||'另列，未计入主口径')}</span>`:''}</td><td><details><summary>货描、品位与来源</summary><p>${E(r.description)}</p><p>原文品位：${r.grade==null?'未列可用数值':E(r.grade)+'%'} · ${E(r.grade_basis)}</p>${r.review_note?`<p>${E(r.review_note)}</p>`:''}${r.hs?`<p>HS ${E(r.hs)}</p>`:''}<p>${E([r.origin_port,r.destination_port].filter(Boolean).join(' → '))}</p><a href="${window.EXPORTS.sources[r.source].url}">查看来源文件</a></details></td></tr>`).join('')||'<tr><td colspan="5">没有匹配记录。</td></tr>'}</tbody></table></div>`;$('exCount').textContent=`显示${Math.min(exLimit,rs.length)} / ${rs.length}条`;$('exMore').hidden=exLimit>=rs.length;$('exNote').textContent=exNotes(k)}
function exportsBind(k,id){if(k!=='exports')return;let c=exContext(id);exportsRows(c.target);['exProduct','exPlace','exProject','exYear'].forEach(id=>$(id).onchange=()=>exportsRows(c.target));$('exQ').oninput=()=>exportsRows(c.target);$('exMore').onclick=()=>{exLimit+=100;exportsRows(c.target,false)};$('exDownload').onclick=()=>{let cols=['id','source','source_row','project','product','date','exporter','buyer','country','tonnes','counted','classification','description','grade','grade_basis','hs','origin_port','destination_port','review_note','corrected_grade','original_grade_basis','original_flag'];let csv=[cols,...exRowsCurrent.map(r=>cols.map(c=>r[c]))].map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');let u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='镍产业出口_筛选.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}}

function exRawNote(rs){let raw=rs.reduce((s,r)=>s+r.tonnes,0),n=rs.filter(r=>r.product==='sulfate'&&r.counted!==r.tonnes).length;return n?`<p class="meta">原始记录合计 ${F(raw)} 实物吨；${n}条跨抬头同票特征候选另列后，参考合计 ${F(exSum(rs))} 实物吨。原行和原始重量均保留，是否确属同一票仍需报关单号核验。</p>`:''}
