function paragraphs(a=[]){return a.map(t=>`<p>${E(t)}</p>`).join('')}
function sections(a=[]){return a.map(s=>`<section><h2>${E(s.title)}</h2>${paragraphs(s.paragraphs)}</section>`).join('')}
function associated(ids=[]){return `<div class="entries">${ids.map(P).filter(Boolean).map(card).join('')}</div>`}
function directory(type){let arr=type==='company'?K.companies:K.topics;return `<div class="kicker">百科目录</div><h1>${type==='company'?'母公司与集团':'产品与工艺'}</h1><p class="lead">${type==='company'?'从母公司的业务出发，理解它为什么投资印尼，以及项目之间如何分工。关联项目不代表全部由该集团控股。':'先理解每一种产品在哪里产生、下一步如何加工，再回到具体工厂核对实际生产。'}</p><div class="entries">${type==='company'?'<article class="entry"><h3><a href="#/npi-parents">镍铁母公司百科：30组投资体系 →</a></h3><p>项目股权、投资逻辑与客户承购，另有完整的镍铁专题。</p><a href="#/npi-customers">客户与下游百科 →</a></article>':''}${arr.map(x=>`<article class="entry"><span class="num">${E(type==='company'?'集团条目':({product:'产品',process:'工艺',commercial:'商业关系'}[x.kind]||'专题'))}</span><h3>${A(type,x.id,x.name)}</h3><p>${E(x.intro)}</p><div class="meta">关联 ${x.project_ids.length} 项研究对象</div></article>`).join('')}</div>`}
function article(type,id){let x=(type==='company'?K.companies:K.topics).find(o=>o.id===id);if(!x)return missing();return `<div class="kicker">${type==='company'?'母公司与集团':'产品与工艺'} / 百科条目</div><h1>${E(x.name)}</h1><div class="article-layout"><article class="article-body"><p class="lead">${E(x.intro)}</p>${sections(x.sections)}${x.open_questions?.length?`<h2>仍需验证</h2>${paragraphs(x.open_questions)}`:''}<h2>关联工厂</h2>${type==='company'?`<div class="ownership-map"><div class="owner-root">${E(x.name)}</div><div class="owner-branches">${x.project_ids.map(P).filter(Boolean).map(p=>`<div class="owner-leaf">${A('plant',p.id,p.name)}<p>${E(p.ownership)}</p></div>`).join('')}</div></div><p class="meta">连接表示投资或产业关联；直接持股、间接权益和历史时点以节点内说明为准。</p>`:''}${associated(x.project_ids)}<h2>资料依据</h2>${refs(x.source_ids)}</article><aside class="infobox"><h3>继续阅读</h3>${(x.related_topics||[]).map(t=>A('topic',t,K.topics.find(o=>o.id===t)?.name||t)).join('<br>')}<p><a href="#/graph">查看产业链关系 →</a></p><p><a href="#/sources">查找原始披露 →</a></p><p class="meta">产业角色与权益比例按各项目条目所列时点理解。</p></aside></div>`}
const stories={
 huake:{name:'华科—友山：跨厂加工',nodes:[['plant','P04','华科 · NPI'],['plant','P16','友山 · 低冰镍'],['plant','P04','华科 · 高冰镍']],text:'这条链解释了为什么一家镍铁厂和一家低冰镍厂会互相买卖。华科将NPI供给友山，友山加工成低冰镍后回供华科，再由华科完成高冰镍工序。同一批镍在两个法人间流转，不应在每个节点重复计作新增镍供应。',evidence:'路径来自用户提供的产业核实；具体年度供货量、定价和合同期限仍缺公开闭环。'},
 sunny:{name:'旭日—华旭：低冰镍与高冰镍分工',nodes:[['plant','P17','旭日 Sunny · 低冰镍'],['plant','P05','华旭 Walhsu · 高冰镍'],['topic','wet-refining','后续精炼']],text:'旭日与华旭需要作为不同工序主体阅读。华新丽华的集团披露支持低冰镍与高冰镍的产业分工，但集团内的配置关系不能直接变成每一票货的供料证明；外采、库存和其他供料也可能参与。',evidence:'集团财报与项目资料支持工序分工。图示不表示华旭全部原料来自旭日，也不表示全部出口都是自产。'},
 hnmi:{name:'华能：低冰镍进入高冰镍环节',nodes:[['plant','P21','CSI 等供料主体'],['plant','P01','HNMI · 高冰镍'],['topic','wet-refining','买家精炼环节']],text:'HNMI的生产取决于低冰镍原料、转换加工的经济性和销售合同。披露中的阶段性停产与重启，需要结合集团在NPI和冰镍之间的收益选择解释；出口量也可能受库存和交付时间影响。',evidence:'供料体系以集团披露为依据；图示的CSI是代表节点，不是唯一供应商。各供料厂逐月分配仍需入厂单据。'},
 cngrlow:{name:'中伟：低冰镍进口路线',nodes:[['plant','P18','德邦 · 低冰镍候选出口'],['company','cngr','钦州 · 低冰镍升级'],['topic','nickel-sulphate','后续镍盐加工']],text:'德邦在本库的2023—2024年记录主要属于低冰镍候选。中伟钦州后来增加低冰镍升级工序；这是“进口低冰镍后进一步加工”的线索。不能把德邦全部发货分配给钦州，也不能据此给中伟所有印尼工厂套上同一路线。',evidence:'出口产品识别与钦州装置披露是两层证据；图示为部分渠道与加工能力的连接，非逐票入厂追踪。'},
 cngrhigh:{name:'中伟：高冰镍进入国内精炼',nodes:[['plant','P19','翡翠湾 · 高冰镍出口'],['company','cngr','钦州／铜仁 · 高冰镍精炼'],['topic','nickel-sulphate','硫酸镍与材料原料']],text:'翡翠湾有约70%镍品位的高冰镍出口记录，中青和德龙四期也必须按自身记录判断。中伟国内的钦州和铜仁具备高冰镍制镍盐环节。这里的“回国加工”是高冰镍后续精炼，不能写成低冰镍转高冰镍。',evidence:'翡翠湾有集团渠道及外部买家；国内装置的存在不证明每一票由该装置消化。点击集团条目查看两个基地及其他候选主体的区别。'},
 vale:{name:'Vale：承购关系与精炼链',nodes:[['plant','P12','Sorowako · 高冰镍'],['company','smm','住友／Vale承购体系'],['topic','refined-nickel','镍与镍盐产品']],text:'Sorowako高冰镍通过长期承购体系进入后续精炼。住友的20%承购份额不能等同于持股比例，报关买家也不能完全等同于合同承购方。长期供料的意义在于将稳定原料与专门的精炼能力连接起来。',evidence:'这是承购机制示意，不是全部出口目的地分配图；Vale与住友两条渠道应结合具体买家记录分别阅读。'}
};
function graph(){return `<div class="kicker">VISUAL EXPLORER / 关系可视化</div><h1>沿着镍的去向阅读</h1><p class="lead">箭头解释加工或交易关系，每张图同时注明证据范围。选择一条产业链，再进入工厂与集团条目。</p><div class="filters"><select id="chainSelect" aria-label="选择产业链">${Object.entries(stories).map(([k,v])=>`<option value="${k}" ${k===graphKey?'selected':''}>${E(v.name)}</option>`).join('')}</select></div><div id="chainStory"></div><h2>看一家工厂的发货去向</h2><p>下图汇总本库报关买家，单位为实物吨，不代表最终加工地或镍金属量。</p><div class="filters"><select id="flowProject" aria-label="发货工厂">${K.projects.filter(p=>p.shipments).map(p=>`<option value="${p.id}">${E(p.name)}</option>`).join('')}</select></div><div id="buyerGraph"></div>`}
function drawStory(){let s=stories[graphKey];$('chainStory').innerHTML=`<div class="panel"><h2>${E(s.name)}</h2><div class="flowrow">${s.nodes.map((n,i)=>`${i?'<span class="arrow">→</span>':''}<div class="flow-node">${A(...n)}</div>`).join('')}</div><p>${E(s.text)}</p><div class="note neutral">${E(s.evidence)}</div></div>`}
function drawBuyerGraph(){let id=$('flowProject').value;let grouped={};K.relations.filter(r=>r.project===id).forEach(r=>grouped[r.buyer]=(grouped[r.buyer]||0)+r.tonnes);let a=Object.entries(grouped).sort((a,b)=>b[1]-a[1]),top=a.slice(0,8);if(a.length>8)top.push(['其他买家',a.slice(8).reduce((s,x)=>s+x[1],0)]);let max=Math.max(...top.map(x=>x[1]),1);$('buyerGraph').innerHTML=`<div class="hbars">${top.map(([name,t])=>`<div class="hbar"><div>${E(name)}<strong>${F(t)}</strong></div><span style="width:${t/max*100}%"></span></div>`).join('')}</div><p>${A('plant',id,'阅读该工厂的完整供销与产品判断 →')}</p>`}
function timeline(){return `<div class="kicker">EVENTS / 历史脉络</div><h1>建设、投产与产业变化</h1><p class="lead">事件保留原有时间精度；某年披露的事实，不一定就是当年发生的事实。详细判断以条目及原文为准。</p><div class="filters"><select id="eventProject" aria-label="筛选事件项目"><option value="">全部项目</option>${K.projects.map(p=>`<option value="${p.id}">${E(p.name)}</option>`).join('')}</select></div><div id="events"></div>`}
function drawEvents(){let id=$('eventProject').value,a=K.projects.filter(p=>!id||p.id===id).flatMap(p=>p.events.map(e=>({...e,project:p}))).sort((a,b)=>a.date.localeCompare(b.date));$('events').innerHTML=`<p class="result-count">${a.length} 条研究事件</p><div class="timeline">${a.map(e=>`<div class="event"><div class="date">${E(e.date)}</div><h3>${E(e.label)}</h3>${A('plant',e.project.id,e.project.name)}<p>${E(e.detail)}</p>${e.source_url?`<a target="_blank" rel="noopener" href="${E(e.source_url)}">查看披露 ↗</a>`:''}</div>`).join('')}</div>`}
function buyerFor(name){return K.buyers.find(b=>b['买家原名']===name)}
function buyerLink(name){let b=buyerFor(name);return b?A('buyer',b.id,name):E(name)}
function trade(){return `<div class="kicker">TRADE / 实际交易与商业安排</div><h1>谁卖给谁，为什么交易</h1><p class="lead">将已发生的出口，与买家的身份、加工用途和商业安排放在一起。集团关联、长期承购、一般外售与身份待核分别记录。</p><div class="stat-row"><div><strong>1,192</strong><span>2023—2026年样本记录</span></div><div><strong>${F(K.summary.physical_tonnes)}</strong><span>主口径 · 实物吨</span></div><div><strong>84</strong><span>报关买家身份条目</span></div></div><div class="filters"><input id="tradeQ" placeholder="查买家、集团、出口商或采购原因" aria-label="筛选交易"><select id="tradeProject" aria-label="交易项目"><option value="">全部项目</option>${K.projects.filter(p=>p.shipments).map(p=>`<option value="${p.id}">${E(p.name)}</option>`).join('')}</select><button id="exportTrade" class="button">下载筛选结果</button></div><div id="tradeResults"></div><h2>合同与承购安排</h2><p>协议类型、承诺数量、实际执行与仍待核实的条款分别列出。备忘录不能直接算作已履行订单。</p>${K.contracts.map(c=>`<details class="contract"><summary>${E(c.parties_zh)} · ${E(c.instrument_type_zh)}</summary><p>${E(c.product_zh)}；披露／协议日期：${E(c.disclosure_or_agreement_date)}</p><p><strong>数量与期限：</strong>${E(c.quantity_or_allocation_zh)}；${E(c.term_zh)}</p><p><strong>为何长期采购：</strong>${E(c.buyer_mechanism_zh)}</p><p><strong>价格及执行：</strong>${E(c.price_zh)} ${E(c.execution_evidence_zh)}</p><p><strong>待核：</strong>${E(c.unresolved_zh)}</p>${refs(c.source_ids)}</details>`).join('')}`}
function filteredTrades(){let q=$('tradeQ').value.toLowerCase(),p=$('tradeProject').value;return K.relations.filter(r=>(!p||r.project===p)&&(!q||[r.buyer,r.exporter,r.group,r.why,r.name,r.category].join(' ').toLowerCase().includes(q)))}
function drawTrades(){let a=filteredTrades();$('tradeResults').innerHTML=`<p class="result-count">${a.length} 组关系 · ${F(a.reduce((s,r)=>s+r.tonnes,0))} 实物吨</p><div class="table-wrap"><table><thead><tr><th>供货方 → 买家</th><th>关系与采购解释</th><th>样本交付</th></tr></thead><tbody>${a.map(r=>`<tr><td>${A('plant',r.project,r.name)}<span class="sub">${E(r.exporter)}</span><span class="sub">↓</span>${buyerLink(r.buyer)}<span class="sub">${E(r.group)} · ${E(r.role)}</span></td><td><strong>${E(r.category)}</strong><p>${E(r.why)}</p><span class="sub">${E(r.basis)}</span></td><td>${F(r.tonnes)} 吨<span class="sub">${r.records} 条 · ${E(r.products)}</span><span class="sub">${E(r.first)}—${E(r.last)}</span></td></tr>`).join('')}</tbody></table></div>${a.length?'':'<p class="empty">没有匹配结果，请调整筛选条件。</p>'}`}
function downloadTrades(){let a=filteredTrades(),keys=['name','exporter','buyer','group','role','category','records','tonnes','first','last','products','why','basis'];let csv='\uFEFF'+[['项目','出口商','买家','集团','角色','关系','记录数','实物吨','首次','末次','产品识别','采购原因','依据'],...a.map(r=>keys.map(k=>r[k]))].map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');let u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),el=document.createElement('a');el.href=u;el.download='印尼镍供销关系_筛选.csv';el.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function buyer(id){let b=K.buyers.find(x=>x.id===id);if(!b)return missing();let a=K.relations.filter(r=>r.buyer===b['买家原名']);return `<div class="kicker">买家百科 / ${E(id)}</div><h1>${E(b['中文或识别名']||b['买家原名'])}</h1><div class="legal">${E(b['买家原名'])}</div><div class="article-body"><p class="lead">${E(b['用途和采购原因'])}</p><h2>它是谁</h2><p>本库将其识别为${E(b['集团'])}渠道，角色为${E(b['角色'])}。身份把握：${E(b['身份把握'])}。</p><h2>怎样理解它的采购</h2><p>${E(b['限制/归并规则'])}</p><h2>可观察的供货关系</h2>${a.map(r=>`<div class="panel"><h3>${A('plant',r.project,r.name)}</h3><p>${E(r.first)}至${E(r.last)}，本库有${r.records}条交付记录，合计${F(r.tonnes)}实物吨。产品识别为“${E(r.products)}”。</p><p>${E(r.why)}。${E(r.basis)}。</p></div>`).join('')}<h2>原始依据</h2>${refs(b.source_ids)}<p><a href="library/exports.xlsx" download>下载底稿，核对买家与原票来源 →</a></p></div>`}
function sources(){return `<div class="kicker">EVIDENCE / 来源中心</div><h1>每个判断，都有出处</h1><div class="note neutral"><a href="#/npi-sources">新增：${window.NPI.sources.length}项NPI研究资料与逐厂证据 →</a></div><p class="lead">${K.sources.length} 项去重来源。这里收录原始链接、定位说明及其关联条目；正文区分披露事实、贸易观察与待证推断。</p><div class="filters"><input id="sourceQ" placeholder="查公司、公告、年报或工艺关键词" aria-label="查找来源"></div><div id="sourceResults"></div>`}
function drawSources(){let q=$('sourceQ').value.toLowerCase(),a=K.sources.filter(s=>[s.title,s.url,s.locator,s.note].join(' ').toLowerCase().includes(q));$('sourceResults').innerHTML=`<p class="result-count">${a.length} 项来源</p>${a.map(s=>`<div class="source-entry"><span class="num">${s.id}</span><h3>${A('source',s.id,s.title)}</h3><p>${E(s.locator)} ${E(s.note)}</p><a target="_blank" rel="noopener" href="${E(s.url)}">打开原文 ↗</a></div>`).join('')}`}
function source(id){let s=K.sources.find(x=>x.id===id);if(!s)return missing();return `<div class="kicker">来源卡片 / ${E(id)}</div><h1>${E(s.title)}</h1><p>${E(s.locator)} ${E(s.note)}</p><p><a class="button" target="_blank" rel="noopener" href="${E(s.url)}">打开原始来源 ↗</a></p><h2>引用此来源的条目</h2>${[['plant',K.projects,'sources'],['company',K.companies,'source_ids'],['topic',K.topics,'source_ids']].map(([t,a,k])=>a.filter(x=>x[k]?.includes(id)).map(x=>`<p>${A(t,x.id,x.name)}</p>`).join('')).join('')||'<p>该来源用于综合报告或交易核对。</p>'}`}
function searchPage(raw){let q='';try{q=decodeURIComponent(raw||'')}catch{}let match=x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase());return `<div class="kicker">全库检索</div><h1>${q?'关于“'+E(q)+'”的资料':'搜索资料库'}</h1>${q?[['园区与区域','park',G().places],['岛屿与地区','island',G().islands],['母公司与集团','group',U().companies],['工厂与项目','project',U().projects],['客户与下游','customer',U().customers],['客户业务专题','npi-dossier',NE().dossiers],['产品与工艺','topic',K.topics],['原始来源','source',K.sources],['NPI原始来源','npi-source',window.NPI.sources]].map(([label,type,a])=>{let found=a.filter(match);return `<section class="search-group"><h2>${label} <span class="meta">${found.length}</span></h2>${found.length?found.slice(0,60).map(x=>`<div class="search-result"><h3>${A(type,x.id,x.name||x.title||x['中文或识别名']||x['买家原名'])}</h3><p>${E(x.intro||x.narrative?.[0]||x.intro_paragraphs?.[0]||x['用途和采购原因']||x.locator||'').slice(0,180)}</p></div>`).join(''):'<p class="meta">本类没有匹配项。</p>'}</section>`}).join(''):'<p>使用页面顶部的搜索框，输入工厂、集团、产品或要了解的关键词。</p>'}`}
function about(){return `<div class="kicker">关于本库 / 研究口径</div><h1>把资料整理成可以追溯的知识</h1><div class="article-body"><p class="lead">这是一部持续积累的印尼镍产业百科。它把研究条目、原始证据和贸易观察连接起来，帮助你理解“谁生产什么、为什么建设、产品去了哪里”。</p><h2>本版收录范围</h2><p>以V19研究底稿为基础，收录49个工厂、项目与相关主体，20个集团、12个专题、84个买家、250组供销关系及11组合同安排。49项并不都已投产，身份待核或仅为贸易抬头的对象仍单独标注。</p><p>出口样本覆盖2023年1月6日至2026年8月29日，共1,192条记录。主口径合计1,532,224.54实物吨，是现有样本统计，不能直接当作印尼全国总产量。2026年为不完整年度。</p><h2>如何读懂证据</h2><p>公司公告和财报用于确认股权、建设与商业安排；项目披露用于识别装置和工艺；报关记录说明可观察的交付。产业访谈、用户核实和推断各自保留标签。每一种来源能回答的问题不同，不能互相替代。</p><p>原票品位覆盖主口径重量约61.96%。缺少品位的货物不会被伪装成精确镍金属量；高冰镍关联、低冰镍候选及中间品争议也分别保留。实物吨不能与项目的镍金属吨产能直接比较。</p><h2>本轮关键修正</h2><p>中伟按德邦、翡翠湾、中青和德龙四期分别判断产品与时期。钦州低冰镍升级，与钦州、铜仁使用高冰镍生产镍盐，是不同工序。不能将集团内一座装置的能力，推定为所有印尼项目的实际路线。</p><h2>保存与继续维护</h2><p>条目正文、关系、事件、合同与来源均保存在结构化资料文件中，可以继续增补和复核。本版支持阅读、检索、筛选与下载；资料更新由后续研究整理后发布，不会自动改写结论。</p><div class="actions"><a class="button" href="knowledge.json" download>下载完整资料库</a><a class="button" href="library/exports.xlsx" download>下载项目与出口底稿</a><a class="button" href="library/report.html" target="_blank">阅读V19完整研究报告</a></div><h2>尚未闭合的资料</h2><p>部分工厂的自产与贸易货比例、逐票最终入厂去向、未公开的合同价格及供料数量仍不能确定。每个条目保留自身待核问题，新的资料应注明时间和来源，避免用今天的股权或工艺倒推历史。</p><p class="meta">内容整理截止：2026年9月17日。</p></div>`}
function extra(key,id){return key==='companies'?directory('company'):key==='company'?article('company',id):key==='topics'?directory('topic'):key==='topic'?article('topic',id):key==='graph'?graph():key==='timeline'?timeline():key==='trade'?trade():key==='buyer'?buyer(id):key==='sources'?sources():key==='source'?source(id):key==='search'?searchPage(id):key==='about'?about():missing()}
function bindExtra(key){if(key==='graph'){drawStory();drawBuyerGraph();$('chainSelect').onchange=e=>{graphKey=e.target.value;drawStory()};$('flowProject').onchange=drawBuyerGraph}if(key==='timeline'){drawEvents();$('eventProject').onchange=drawEvents}if(key==='trade'){drawTrades();$('tradeQ').oninput=drawTrades;$('tradeProject').onchange=drawTrades;$('exportTrade').onclick=downloadTrades}if(key==='sources'){drawSources();$('sourceQ').oninput=drawSources}}
