const G=()=>window.GEOGRAPHY;
const geoPlace=id=>G().places.find(p=>p.id===id);
const geoLoc=id=>G().locations[id];
function geoLinks(id){let l=geoLoc(id);if(!l)return '';let p=geoPlace(l.place_id);return `<span class="geo-links">${A('island',l.island_id,l.island)}<span> › </span>${p?A('park',p.id,p.name):E(l.locality||'地点待确认')}</span>`}
function geoFacts(id){let l=geoLoc(id),p=l&&geoPlace(l.place_id);return l?`<dt>岛屿／地区</dt><dd>${A('island',l.island_id,l.island)}</dd><dt>${p?.kind==='park'?'所在园区':'所在区域'}</dt><dd>${p?A('park',p.id,p.name):'地点待确认'}</dd>${l.location_basis?`<dt>地点资料</dt><dd>${E(l.location_basis)}</dd>`:''}${l.province?`<dt>省／行政区</dt><dd>${E(l.province)}</dd>`:''}${l.regency||l.locality?`<dt>具体地点</dt><dd>${E([l.regency,l.locality].filter(Boolean).join(' · '))}</dd>`:''}`:''}
function geoScope(p,s){return !s||s==='both'&&p.npi_id&&p.matte_ids.length||s==='npi'&&p.npi_id||s==='matte'&&p.matte_ids.length||s==='mhp'&&p.mhp_ids?.length||['sulfate','refined'].includes(s)&&p.refining_products?.includes(s)}
function geoTable(ps){return `<div class="table-wrap"><table class="geo-table"><thead><tr><th>企业／项目</th><th>岛屿与园区</th><th>投产与运行状态</th><th>产品与阶段</th><th>母公司与股东</th><th>出口记录</th></tr></thead><tbody>${ps.map(p=>{let a=window.WIKI_ARTICLES[p.id],status=a?.facts.find(([k])=>/状态|阶段|进度/.test(k))?.[1],product=a?.facts.find(([k])=>/主要产品|^产品$/.test(k))?.[1];let groups=U().companies.filter(g=>g.project_ids.includes(p.id));return `<tr><td>${A('project',p.id,a?.title||p.name)}${p.legal&&!(a?.title||p.name).includes(p.legal)?`<span class="sub">${E(p.legal)}</span>`:''}</td><td>${geoLinks(p.id)}</td><td>${opCell(p.id)}</td><td>${E(product||p.classification)}${status?`<span class="sub">${E(status)}</span>`:''}</td><td>${groups.map(g=>A('group',g.id,g.name)).join(' · ')||E(p.ownership)}</td><td>${exportMiniLinks(p.id)}</td></tr>`}).join('')}</tbody></table></div>`}
function geoHome(){return `<div class="kicker">地点百科</div><h1>园区与岛屿</h1><p class="lead">沿岛屿查看冶炼基地，再进入园区、企业和它们的客户。正式工业园区与园区之外的地理区域分别标注。</p><div class="geo-islands">${G().islands.filter(i=>!i.id.startsWith('country-')).map(i=>{let ps=U().projects.filter(p=>geoLoc(p.id)?.island_id===i.id);return `<a href="#/island/${i.id}"><strong>${E(i.name)}</strong><span>${ps.length}个已收录项目</span></a>`}).join('')}</div><div class="filters"><input id="geoQ" placeholder="查园区、岛屿、省份或企业" aria-label="查园区"><select id="geoIsland" aria-label="选择岛屿"><option value="">全部岛屿与地区</option>${G().islands.filter(i=>!i.id.startsWith('country-')).map(i=>`<option value="${i.id}">${E(i.name)}</option>`).join('')}</select></div><div id="geoResults"></div><p class="meta">企业清单以本库已研究的镍产业项目为基础，包含在产、在建、规划及历史项目；不代表园区全部注册企业或当前在产厂数。</p>`}
function geoRows(){let q=$('geoQ').value.toLowerCase(),island=$('geoIsland').value;let ps=G().places.filter(p=>!p.id.startsWith('country-')&&(!island||p.island_id===island)&&(!q||JSON.stringify(p).toLowerCase().includes(q)||U().projects.some(x=>geoLoc(x.id)?.place_id===p.id&&(x.name+' '+x.legal).toLowerCase().includes(q))));$('geoResults').innerHTML=`<div class="table-wrap"><table><thead><tr><th>园区／区域</th><th>位置</th><th>镍产业概况</th><th>已收录项目</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${A('park',p.id,p.name)}<span class="sub">${p.kind==='park'?'工业园区':'地理区域'}</span></td><td>${A('island',p.island_id,p.island)}<span class="sub">${E([p.province,p.regency].filter(Boolean).join(' · '))}</span></td><td>${E(p.intro)}</td><td>${U().projects.filter(x=>geoLoc(x.id)?.place_id===p.id).length}</td></tr>`).join('')}</tbody></table></div>`}
function geoArticle(id,island=false){let p=island?G().islands.find(p=>p.id===id):geoPlace(id);if(!p)return missing();let ps=U().projects.filter(x=>{let l=geoLoc(x.id);return l&&(island?l.island_id===id:l.place_id===id)}),parks=island?G().places.filter(x=>x.island_id===id):[],extras=G().additional_entities.filter(x=>island?geoPlace(x.place_id)?.island_id===id:x.place_id===id);return `<div class="kicker"><a href="#/parks">园区与岛屿</a>${island?'':` / ${A('island',p.island_id,p.island)}`}</div><h1>${E(p.name)}</h1><p class="lead">${E(p.intro||'这里收录该地区的镍产业项目，并连接各工厂的股东、产品、客户和出口记录。')}</p><div class="actions"><a href="#" data-scroll="geo-companies">企业清单（${ps.length}）</a><a href="#/exports/${island?'island:':'park:'}${p.id}~npi">本地区出口记录 →</a></div>${parks.length?`<div class="geo-islands">${parks.map(x=>`<a href="#/park/${x.id}"><strong>${E(x.name)}</strong><span>${x.kind==='park'?'工业园区':'地理区域'}</span></a>`).join('')}</div>`:''}<article class="wiki-prose geo-prose">${(p.sections||[]).map(s=>`<section><h2>${E(s.title)}</h2>${s.paragraphs.map((t,j)=>`<p>${E(t)}${j===s.paragraphs.length-1?wikiCites(p,s.refs):''}</p>`).join('')}</section>`).join('')}</article><section id="geo-companies"><h2>已收录企业与项目</h2><p>企业在同一地区，不等于拥有相同股东；各行的产品与建设阶段以项目正文为准。</p>${geoTable(ps)}</section>${extras.length?`<section><h2>其他已识别的园区企业</h2><div class="table-wrap"><table><thead><tr><th>企业</th><th>园区角色</th><th>资料</th></tr></thead><tbody>${extras.map(e=>`<tr><td>${E(e.name)}</td><td>${E(e.role)}</td><td><a href="${E(e.url)}" target="_blank" rel="noopener">企业资料 ↗</a></td></tr>`).join('')}</tbody></table></div></section>`:''}${p.sources?.length?`<section><h2>参考资料</h2><ol>${p.sources.map(s=>`<li><a href="${E(s.url)}" target="_blank" rel="noopener">${E(s.title)}</a></li>`).join('')}</ol></section>`:''}${p.pending?.length?`<details class="reading-notes"><summary>需要再确认</summary>${p.pending.map(t=>`<p>${E(t)}</p>`).join('')}</details>`:''}`}
const geoOldDirectory=uDirectory,geoOldRows=uRows;
uDirectory=function(k){if(k!=='projects')return geoOldDirectory(k);return `<div class="kicker">统一项目目录</div><h1>工厂与项目</h1><p class="lead">按岛屿、园区或产品查找企业。每个项目都连接地点、股东、客户和出口记录。</p><div class="actions"><a href="#/parks">园区与岛屿百科 →</a><a href="#/exports">出口与客户记录 →</a><a href="library/npi-audit.xlsx">镍铁产线产能表 ↓</a></div><div class="filters"><select id="uStatus" aria-label="投产与运行状态"><option value="">全部投产与运行状态</option>${Object.entries(OP_LABELS).map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select><input id="uQ" aria-label="搜索统一资料库" placeholder="查企业、股东、岛屿或园区"><select id="uScope" aria-label="产品资料范围"><option value="">全部产品资料</option><option value="npi">镍铁</option><option value="matte">低冰镍／高冰镍</option><option value="mhp">MHP／MSP及下游</option><option value="sulfate">硫酸镍</option><option value="refined">精炼镍</option><option value="both">镍铁与冰镍共有项目</option></select><select id="uIsland" aria-label="项目岛屿"><option value="">全部岛屿与地区</option>${G().islands.filter(i=>!i.id.startsWith('country-')).map(i=>`<option value="${i.id}">${E(i.name)}</option>`).join('')}</select><select id="uPlace" aria-label="项目园区"><option value="">全部园区与区域</option>${G().places.map(p=>`<option value="${p.id}">${E(p.name)}</option>`).join('')}</select></div><p class="op-directory-note">已投产表示项目已进入生产；停产、检修与历史记录按各项资料时点阅读。<a href="library/project-status.csv">下载项目状态表 ↓</a></p><div id="uResults"></div>`};
uRows=function(k){if(k!=='projects')return geoOldRows(k);let q=$('uQ').value.toLowerCase(),s=$('uScope').value,i=$('uIsland')?.value||'',l=$('uPlace')?.value||'';let ps=U().projects.filter(p=>{let g=geoLoc(p.id);return opFilterMatch(p)&&geoScope(p,s)&&(!i||g?.island_id===i)&&(!l||g?.place_id===l)&&(!q||(JSON.stringify(p)+' '+JSON.stringify(g)+' '+JSON.stringify(geoPlace(g?.place_id))).toLowerCase().includes(q))});$('uResults').innerHTML=`<p class="meta">${ps.length}项</p>`+geoTable(ps)};
function geoRoute(k,id){return k==='parks'?geoHome():k==='park'?geoArticle(id):k==='island'?geoArticle(id,true):null}
function geoBind(k){if(k==='parks'){geoRows();$('geoQ').oninput=geoRows;$('geoIsland').onchange=geoRows}if(k==='projects'){['uIsland','uPlace'].forEach(id=>$(id).onchange=()=>uRows('projects'))}}

const geoOldGroup=uGroup;uGroup=function(id){let s=geoOldGroup(id),c=U().companies.find(g=>g.id===id);if(!c)return s;let ids=[...new Set(c.project_ids.map(pid=>geoLoc(pid)?.place_id).filter(Boolean))];return s.replace('</h1>','</h1><div class="geo-group-links"><strong>关联园区与区域</strong><p>'+ids.map(id=>A('park',id,geoPlace(id).name)).join(' · ')+'</p></div>')};
const geoOldCustomer=uCustomer;uCustomer=function(id){let s=geoOldCustomer(id),rs=exBase('customer:'+id);return s.replace('</h1>','</h1><div class="ex-tabs">'+exKinds(rs).map(k=>exLink('customer:'+id,k,'查看'+EX_NAMES[k]+'采购记录 →')).join('')+'</div>')};
for(const p of U().projects){let g=geoLoc(p.id);if(g)p.search_text+=' '+JSON.stringify(g)+' '+geoPlace(g.place_id).name}
