// Global geography and source-backed facility records extend the original stable routes.
const WG=()=>window.GLOBAL_NICKEL;
const wgCountry=code=>WG().countries.find(c=>c.id===code);
const wgCodes=id=>U().projects.find(p=>p.id===id)?.country_codes||[];
let wgProjects=code=>U().projects.filter(p=>!code||p.country_codes?.includes(code));
function wgLabel(id){return wgCodes(id).map(code=>{const c=wgCountry(code);return c?c.flag+' '+c.name:code}).join(' / ')}
function wgCountryLinks(id){return wgCodes(id).map(code=>{const c=wgCountry(code);return c?A('country',code,c.flag+' '+c.name):''}).join(' · ')}
const wgStatus={care:'保养维护',closed:'永久关闭',demolished:'已拆除',construction:'在建',planned:'规划／可研',cancelled:'中止未建'};Object.assign(OP_LABELS,wgStatus);
const WG_CHAINS={'Glencore-Nikkelverk-Feed':'嘉能可：冶炼原料与挪威Nikkelverk精炼链','Doniambo-Sandouville-historic':'SLN—Sandouville：历史冶炼与精炼联系','Harjavalta-FI':'Harjavalta：芬兰冶炼与精炼基地','Nornickel-Kola-Taimyr':'诺里尔斯克镍业：泰梅尔—科拉体系','SMM-Philippines-Japan':'住友金属矿山：菲律宾—日本加工链','Hyuga-SMM':'日向精炼所：镍铁与新建冰镍环节','POSCO-SNNC':'POSCO—SNNC：镍铁与高纯镍加工','BHP-NickelWest':'BHP Nickel West：Kalgoorlie—Kwinana','Vale-CopperCliff-Sudbury':'Vale：Sudbury与Copper Cliff加工体系','BANCo-Nickelton-Deschenes':'BANCo：Nickelton—Deschênes历史加工链','Sherritt-Moa-FortSask':'Sherritt：古巴莫阿—加拿大萨斯喀彻温堡','Vale-Thompson':'Vale：Thompson历史冶炼与精炼链','Impala-Zimplats':'Implats：津巴布韦—南非加工链'};
const WG_PRODUCTS={npi:'镍铁／NPI',matte:'冰镍',mhp:'MHP／MSP',sulfate:'硫酸镍',refined:'精炼镍',other:'其他镍产品'};
const wgOldScope=geoScope;geoScope=function(p,s){return wgOldScope(p,s)||!!(s&&p.global_scopes?.includes(s))};
const wgOldProducts=uProducts;uProducts=function(p){return p.global_scopes?p.global_scopes.map(s=>WG_PRODUCTS[s]).join(' · '):wgOldProducts(p)};
const wgOldLinks=geoLinks;geoLinks=function(id){let l=geoLoc(id);return `<span class="country-links">${wgCountryLinks(id)}</span>${l&&!l.place_id.startsWith('country-')?' › '+wgOldLinks(id):l?.locality?' · '+E(l.locality):''}`};
const wgOldInfo=projectInfobox;projectInfobox=function(id,a,c){return wgOldInfo(id,a,c).replace(/<dt>国家<\/dt><dd>[\s\S]*?<\/dd>/,'<dt>国家／地区</dt><dd>'+wgCountryLinks(id)+'</dd>')};
const wgOldProfile=ptProfile;ptProfile=function(id){let p=wgOldProfile(id);p.location=wgLabel(id)+'\n'+p.location;const r=WG().records[id];if(r){p.capacity=(r.capacity_display!=null?F(r.capacity_display)+' 吨镍／年\n':'')+(r.capacity_note||'见项目正文');p.sales=r.offtake||p.sales;p.production=wgOutputs(r).map(x=>x.period+'：'+F(x.value)+' 镍金属吨（'+(r.output_basis||'底表口径')+'）').join('\n')}return p};
function wgOutputs(r){return ['2022','2023','2024','2025','2026H1'].filter(y=>typeof r['output_'+y]==='number').map(y=>({period:y==='2026H1'?'2026上半年':y+'全年',value:r['output_'+y]}))}
function wgProduction(r){const rows=wgOutputs(r);if(!rows.length)return '';return `<section class="wg-production" id="global-production" data-id="${r.id}"><h2>已披露产量</h2><p>${E(r.output_basis||'按底表列示，镍金属吨；具体产品和期间见原始资料。')}</p><div class="filters"><select id="wgOutputPeriod" aria-label="选择产量期间"><option value="year">完整年度</option><option value="half">上半年</option><option value="all">全部列示</option></select><button id="wgOutputDownload">下载产量记录</button></div><div id="wgOutputChart"></div><div id="wgOutputRows"></div><p class="meta">年度和半年分别列示。集团或加工链口径不视为单厂产量。</p></section>`}
function wgRelated(id){const r=WG().records[id],p=U().projects.find(x=>x.id===id);let ps=r?.chain?Object.values(WG().records).filter(x=>x.chain===r.chain).map(x=>x.id):p?.component_ids||[];if(!ps.length)return '';return `<section class="wg-related"><h2>关联设施与加工链</h2><p>${E(WG_CHAINS[r?.chain]||r?.chain||'跨厂／多地点档案')}：各设施按地点与工序分别建档。历史关联和当前供料安排见各条正文。</p><div class="wg-chain">${ps.map(pid=>`<div>${A('project',pid,projectTitle(pid))}<span>${E(WG().records[pid]?.stage||'独立设施')}</span>${opBadge(pid)}</div>`).join('')}</div><p><a href="#/compare/${ps.slice(0,5).join(',')}">并排比较这些设施 →</a> · <a href="#/chains">全部跨厂加工链 →</a></p></section>`}
const wgOldWiki=wikiArticle;wikiArticle=function(id){let html=wgOldWiki(id),r=WG().records[id];html=html.replace('<section id="wiki-trade">',wgRelated(id)+(r?wgProduction(r):'')+'<section id="wiki-trade">');if(r){html=html.replace('<section id="wiki-sources"',`<section class="reading-information"><h2>资料说明</h2><p>${r.researched_at?`本条已按地质调查资料、历史文献及企业资料重新核对，更新日期：${E(r.researched_at)}。工艺、设备和事件按各自历史时期说明，来源列于下方。`:`本条接入用户提供的《全球镍冶炼厂数据库》总表 ${E(r.source_id)}。状态资料核实年份为 ${E(r.verified||'底表未列')}；导入整理日期为 ${WG().asof}。各网页来源沿用底表记录，部分信息另作核对。`}</p><p>厂名包括设施名称与历史名称；法人和股权关系见正文。${r.capacity_basis==='估算值，待核对原始单位'?'底表产能含估算换算，具体数值与原始单位放在产能章节阅读。':''}</p><a href="library/global-register.csv" download>下载全球逐厂资料表 ↓</a></section><section id="wiki-sources"`)}return html};
const wgOldTrade=wikiTrade;wikiTrade=function(c){if(WG().records[c.p.id]&&!exBase(c.p.id).length)return '<p>该设施的供料、承购和销售安排见正文。现有逐票数据主要覆盖印尼出口，本次全球普查没有附各国完整逐票记录。</p>';return wgOldTrade(c)};
const WG_INTROS={ID:'印尼条目沿用原有逐厂研究，把镍铁、冰镍、MHP、硫酸镍与精炼镍连接到园区、集团和出口记录。可继续进入苏拉威西、哈马黑拉与Obi岛的各个园区。',AU:'澳大利亚目录同时收录硫化矿冶炼精炼、红土矿湿法项目和新建电池材料计划。BHP Nickel West的冶炼与精炼设施、First Quantum的Ravensthorpe分别建档，便于查看维护状态和不同原料路线。',CA:'加拿大目录把冶炼厂与后续精炼厂分开，也保留Sudbury等地区早期设施的历史记录。Copper Cliff的前身冶炼厂、现有冶炼系统与镍精炼厂各有条目；古巴Moa至Fort Saskatchewan的加工链可以跨国阅读。',JP:'日本项目覆盖镍铁、不锈钢原料、镍中间品处理与精炼。目录连接住友金属矿山在日本的加工设施和菲律宾的HPAL项目，并单列日向的镍铁设施与新建冰镍环节。',PH:'菲律宾目录既有Coral Bay和Taganito等湿法中间品项目，也包括历史精炼厂及新的冶炼计划。沿住友金属矿山加工链，可继续阅读日本的新居滨与播磨设施。',FI:'芬兰目录把Harjavalta的冶炼与精炼环节分开，并收录Terrafame从矿石到电池化学品的加工项目。Kokkola的镍精炼计划单独标注，不能把已有钴业务当成镍线投产。',NC:'新喀里多尼亚同时保留镍铁、湿法镍钴项目与早期冶炼历史。Doniambo、Koniambo和Goro的工艺、股东及运行状态分别列示，便于比较同一地区不同路线的发展。',RU:'俄罗斯目录连接诺里尔斯克与科拉体系的冶炼、精炼和历史退出设施。集团披露产量与单厂能力分开保存，沿加工链查看各工序的角色。',KR:'韩国条目覆盖镍铁、高纯镍精炼、镍盐与电池材料项目。既有生产线与新建项目分别建档；拟议合作的取消不自动改变同一集团其他在产工厂的状态。',CU:'古巴目录覆盖红土矿镍钴中间品与历史镍冶炼设施。莫阿的上游生产与加拿大萨斯喀彻温堡精炼厂分开列示，并保留跨国加工链入口。'};
function wgStats(ps){return `<div class="wg-statrow">${[['研究档案',ps.length],['在产／部分生产',ps.filter(p=>['operating','partial','trial'].includes(opGet(p.id)?.key)).length],['停产／保养维护',ps.filter(p=>['halted','care'].includes(opGet(p.id)?.key)).length],['关闭／已拆除',ps.filter(p=>['closed','demolished'].includes(opGet(p.id)?.key)).length]].map(([label,v])=>`<div><strong>${v}</strong><span>${label}</span></div>`).join('')}</div>`}
function worldHome(){return `<div class="kicker">GLOBAL NICKEL ATLAS</div><h1>国家与地区</h1><p class="lead">先找到国家，再进入工厂、股东与跨国加工链。国旗与文字名称并列显示，历史工厂和规划项目同样保留位置。</p>${wgStats(U().projects)}<div class="wg-map" id="worldMap" aria-label="国家与地区导航地图"></div><p class="meta">有色地区表示本库已有条目；灰色表示未纳入当前资料，不代表没有镍产业。地图用于地区导航，项目页标注具体地点。边界底图：<a href="https://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/" target="_blank" rel="noopener">Natural Earth</a>。</p><div class="filters"><input id="wgCountryQ" aria-label="搜索国家或地区" placeholder="搜索国家、地区或英文名"><select id="wgRegion" aria-label="选择世界地区"><option value="">全部大区</option>${[...new Set(WG().countries.map(c=>c.region))].map(x=>`<option>${E(x)}</option>`).join('')}</select><select id="wgCountryOrder" aria-label="国家排序"><option value="count">按收录数量</option><option value="name">按名称</option></select></div><div id="wgCountryResults"></div><section class="reading-information"><h2>资料覆盖</h2><p>${E(WG().source_scope)} 中国大陆项目已接入，覆盖范围见中国条目。当前共${WG().countries.length}个国家和地区、${U().projects.length}个研究档案，其中166条全球底表记录与原库合并；12条沿用原项目入口，154条新增。</p><p>档案数包含设施、规划、历史及跨厂研究对象；同一跨国档案可关联两个地区，因此各国档案数不直接相加。这里不将上下游产能加成“全球总产能”。</p><div class="actions"><a href="library/global-register.csv" download>全球逐厂资料表 ↓</a><a href="library/global-crosswalk.csv" download>原表与百科编号对照 ↓</a><a href="#/chains">跨厂加工链 →</a></div></section>`}
function wgCountryRows(){const q=$('wgCountryQ').value.trim().toLowerCase(),reg=$('wgRegion').value;let cs=WG().countries.filter(c=>(!reg||c.region===reg)&&[c.name,c.english,c.id].join(' ').toLowerCase().includes(q));cs.sort($('wgCountryOrder').value==='name'?(a,b)=>a.name.localeCompare(b.name,'zh'):(a,b)=>wgProjects(b.id).length-wgProjects(a.id).length);$('wgCountryResults').innerHTML=`<p class="meta">${cs.length}个国家／地区</p><div class="wg-countries">${cs.map(c=>{const ps=wgProjects(c.id),active=ps.filter(p=>['operating','partial','trial'].includes(opGet(p.id)?.key)).length;return `<a href="#/country/${c.id}"><span class="wg-flag" aria-hidden="true">${c.flag}</span><div><h2>${E(c.name)}</h2><span>${E(c.english)}</span><p>${ps.length}个档案 · ${c.id==='CN'?'企业与产品目录':active+'项在产／部分生产'}</p><small>${E(c.region)}</small></div></a>`}).join('')}</div>`}
function wgCountryPage(code){const c=wgCountry(code);if(!c)return missing();const ps=wgProjects(code),parks=G().places.filter(x=>!x.id.startsWith('country-')&&ps.some(p=>geoLoc(p.id)?.place_id===x.id));return `<div class="kicker"><a href="#/world">国家与地区</a> / ${E(c.region)}</div><h1><span aria-hidden="true">${c.flag}</span> ${E(c.name)}镍产业</h1><p class="lead">${E(WG_INTROS[code]||c.name+'的目录将现有生产设施、停产项目、规划和历史工厂放在同一条时间脉络中。进入项目，可查看工艺、原料、设备、股权沿革和资料来源。')}</p>${wgStats(ps)}<div class="actions"><a href="#/projects/country:${code}">在统一目录筛选 →</a><a href="#/chains/${code}">跨厂加工链 →</a></div>${parks.length?`<section><h2>园区与具体地区</h2><div class="tags">${parks.map(p=>A('park',p.id,p.name)).join(' · ')}</div></section>`:''}<section><h2>工厂与项目</h2><div class="filters"><input id="wgPlantQ" aria-label="搜索本地区工厂" placeholder="搜索工厂、运营方或原料"><select id="wgPlantStatus" aria-label="本地区运行状态"><option value="">全部运行状态</option>${Object.entries(OP_LABELS).map(([k,l])=>`<option value="${k}">${l}</option>`).join('')}</select><select id="wgPlantProduct" aria-label="本地区产品"><option value="">全部产品</option>${Object.entries(WG_PRODUCTS).map(([k,l])=>`<option value="${k}">${l}</option>`).join('')}</select><button id="wgPlantReset">重置</button><button id="wgPlantDownload">下载筛选清单</button></div><div id="wgStatusChart" class="wg-status-chart"></div><div id="wgPlantResults"></div></section><section><h2>项目历史时间线</h2><p>事件年份与资料核实年份分开记录；在表格筛选项目时，时间线同步更新。</p><select id="wgHistoryOrder" aria-label="时间排序"><option value="desc">最新在前</option><option value="asc">从早到晚</option></select><div id="wgCountryHistory"></div></section><section class="reading-information"><h2>资料说明</h2><p>${code==='ID'?'印尼项目沿用原有研究与用户提供的逐票出口资料。':'本地区条目主要来自2026年9月全球普查底表及已收录的海外加工资料。'} 运行状态、产能与产量各自保留来源时期。${ps.some(p=>p.record_type)?'跨厂或多地点总览会标注档案类型，不把它视为另一座独立工厂。':''}</p><a href="#/sources">查阅来源目录 →</a></section><div id="wgCountrySeed" data-code="${code}" hidden></div>`}
let wgSelected=[];
function wgPlantRows(){const code=$('wgCountrySeed').dataset.code,q=$('wgPlantQ').value.toLowerCase(),s=$('wgPlantStatus').value,kind=$('wgPlantProduct').value;wgSelected=wgProjects(code).filter(p=>(!s||opGet(p.id)?.key===s)&&geoScope(p,kind)&&(!q||p.search_text.toLowerCase().includes(q)));$('wgPlantResults').innerHTML=`<p class="meta">${wgSelected.length}项研究档案</p>`+geoTable(wgSelected);const all=wgProjects(code),counts={};all.forEach(p=>{const s=opGet(p.id)?.key||'unknown';counts[s]=(counts[s]||0)+1});$('wgStatusChart').innerHTML=Object.entries(counts).map(([k,v])=>`<button data-wg-status="${k}" aria-pressed="${s===k}">${OP_LABELS[k]} <strong>${v}</strong></button>`).join('');$('wgStatusChart').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('wgPlantStatus').value=s===b.dataset.wgStatus?'':b.dataset.wgStatus;wgPlantRows()});wgCountryHistory()}
function wgCountryHistory(){const ids=new Set(wgSelected.map(p=>p.id)),desc=$('wgHistoryOrder').value==='desc',es=HX().events.filter(e=>ids.has(e.project_id)).sort((a,b)=>(hxSort(a)-hxSort(b))*(desc?-1:1));$('wgCountryHistory').innerHTML=`<p class="meta">${es.length}项事件</p><div class="timeline">${es.slice(0,24).map(e=>hxEvent(e,true)).join('')||'<p>这些项目的历史沿革见正文。</p>'}</div>${es.length>24?`<details><summary>展开其余${es.length-24}项事件</summary><div class="timeline">${es.slice(24).map(e=>hxEvent(e,true)).join('')}</div></details>`:''}`}
function wgChains(code){const groups={};Object.values(WG().records).filter(r=>r.chain).forEach(r=>(groups[r.chain]??=[]).push(r));return `<div class="kicker"><a href="#/world">全球镍产业</a> / 跨厂关系</div><h1>跨国与跨厂加工链</h1><p class="lead">从上游中间品或冶炼设施，继续找到后续精炼厂。每个框都是独立条目，点击可以查看所在国家、设备和经营历史。</p><p>同组表示底表识别的产业链关联，包含历史关系；图中不把所有成员自动视作当前直接供销双方。产能分别看，不相加。</p><div class="actions"><a href="#/graph">印尼园区供料与加工关系 →</a><a href="#/groups">沿集团查看全球布局 →</a></div>${Object.entries(groups).filter(([name,rs])=>!code||rs.some(r=>r.country_code===code)).map(([name,rs])=>`<section class="wg-chain-section"><h2>${E(WG_CHAINS[name]||name)}</h2><div class="wg-chain">${rs.map(r=>`<div><span>${E(r.stage)}</span>${A('project',r.id,projectTitle(r.id))}<p>${wgCountryLinks(r.id)}</p>${opBadge(r.id)}</div>`).join('')}</div><p><a href="#/compare/${rs.slice(0,5).map(r=>r.id).join(',')}">比较设备、产能与供料 →</a></p></section>`).join('')}<a href="library/global-register.csv" download>下载逐厂关系资料 ↓</a>`}
const wgOldDirectory=uDirectory;uDirectory=function(k){if(k!=='projects')return wgOldDirectory(k);return wgOldDirectory(k).replace('按岛屿、园区或产品查找企业。','按国家、地区、园区或产品查找企业。').replace('<div class="filters">','<div class="filters"><select id="uCountry" aria-label="项目国家或地区"><option value="">全部国家／地区</option>'+WG().countries.map(c=>`<option value="${c.id}">${c.flag} ${E(c.name)}</option>`).join('')+'</select>').replace('<div class="actions">','<div class="actions"><a href="#/world">国家与地区导航 →</a><a href="#/chains">跨厂加工链 →</a>').replace('<option value="both">','<option value="other">其他镍产品</option><option value="both">')};
const wgOldRows=uRows;uRows=function(k){if(k!=='projects')return wgOldRows(k);const q=$('uQ').value.toLowerCase(),s=$('uScope').value,c=$('uCountry')?.value||'',island=$('uIsland')?.value||'',place=$('uPlace')?.value||'';const ps=U().projects.filter(p=>{let l=geoLoc(p.id);return (!c||p.country_codes?.includes(c))&&opFilterMatch(p)&&geoScope(p,s)&&(!island||l?.island_id===island)&&(!place||l?.place_id===place)&&(!q||(p.search_text+' '+wgLabel(p.id)+' '+p.name).toLowerCase().includes(q))});$('uResults').innerHTML=`<p class="meta">${ps.length}项研究档案 · 国家、状态和产品可组合筛选</p>`+geoTable(ps)};
const wgOldTable=geoTable;geoTable=function(ps){return wgOldTable(ps).replace('<th>岛屿与园区</th>','<th>国家／地区与地点</th>').replaceAll('class="geo-table"','class="geo-table wg-table"')};
const wgOldPcProjects=pcProjects;pcProjects=function(m){const ps=wgOldPcProjects(m);let globals=U().projects.filter(p=>p.global_scopes?.includes(m.scope));if(m.id==='low-matte')globals=globals.filter(p=>/低冰|低品位.*锍/.test(WG().records[p.id]?.products||''));if(m.id==='high-matte')globals=globals.filter(p=>/高冰|高品位.*锍/.test(WG().records[p.id]?.products||''));return [...new Map([...ps,...globals].map(p=>[p.id,p])).values()]};
const wgOldPcHome=pcHome;pcHome=function(id){return wgOldPcHome(id).replace('<span>印尼关联研究项目</span>','<span>全球关联研究项目</span>').replace('<option value="unknown">待确认</option>','<option value="unknown">待确认</option>').replace('</h1>','</h1><p class="meta">全球企业目录 · 产业叙述与逐票贸易分析仍以印尼资料为主；海外工厂历史请进入项目正文。</p>').replace('<div class="pc-toc">','<p class="meta">企业与项目目录已扩展至全球；下方产业叙述与逐票出口分析以印尼研究为主，各国完整沿革见国家和工厂条目。</p><div class="pc-toc">')};
const wgOldHome=homePage;homePage=function(){let html=wgOldHome().replaceAll('印尼镍产业百科','全球镍产业百科').replace('从镍铁、低冰镍、高冰镍和MHP，到硫酸镍与精炼镍，查阅项目的建设历史、设备产能、股东与供销关系。','从国家与工厂出发，查阅镍铁、冰镍、湿法中间品及精炼产品的历史、股东、设备和供销关系。').replace('<section class="hi-products">',`<section class="wg-home-world"><div class="section-head"><h2>从全球找到工厂</h2><a href="#/world">${WG().countries.length}个国家与地区 →</a></div><div class="wg-home-regions">${[...new Set(WG().countries.map(c=>c.region))].map(reg=>{const cs=WG().countries.filter(c=>c.region===reg);return `<article><h3>${E(reg)}</h3><p>${cs.slice(0,7).map(c=>A('country',c.id,c.flag+' '+c.name)).join(' · ')}</p><a href="#/world/${encodeURIComponent(reg)}">查看${cs.length}个国家／地区 →</a></article>`}).join('')}</div><p class="meta">中国大陆已接入镍生铁、纯镍与硫酸镍项目表。目录保留在产、停产、规划和历史设施；档案数不等于在产厂数。</p><div class="actions"><a href="#/chains">跨国加工链 →</a><a href="#/projects">全球项目总目录 →</a></div></section><section class="hi-products">`).replace('从园区找到工厂','印尼园区与产业集群').replace('也收录部分海外加工项目作对照。','另接入166条全球普查记录与中国项目表，原有同厂档案合并。各项目保留原始资料时点。').replace('六个品目完整研究 →','产品与工艺研究 →');return html};
function wgRoute(k,id){return k==='world'?worldHome():k==='country'?wgCountryPage(id):k==='chains'?wgChains(id):null}
function wgBind(k,id){if(k==='world'){$('worldMap').innerHTML=window.WORLD_MAP_SVG||'';if(id)$('wgRegion').value=decodeURIComponent(id);wgCountryRows();$('wgCountryQ').oninput=wgCountryRows;['wgRegion','wgCountryOrder'].forEach(id=>$(id).onchange=wgCountryRows)}if(k==='country'){wgPlantRows();$('wgPlantQ').oninput=wgPlantRows;['wgPlantStatus','wgPlantProduct'].forEach(id=>$(id).onchange=wgPlantRows);$('wgHistoryOrder').onchange=wgCountryHistory;$('wgPlantReset').onclick=()=>{['wgPlantQ','wgPlantStatus','wgPlantProduct'].forEach(id=>$(id).value='');wgPlantRows()};$('wgPlantDownload').onclick=()=>ixDownload([['项目ID','项目','国家／地区','状态','产品','运营方','资料时点'],...wgSelected.map(p=>[p.id,p.name,wgLabel(p.id),opGet(p.id)?.label,uProducts(p),p.ownership,opGet(p.id)?.period])],wgCountry(id).name+'项目清单.csv')}
 if(k==='projects'){if(id?.startsWith('country:'))$('uCountry').value=id.slice(8);$('uCountry').onchange=()=>{$('uIsland').value='';$('uPlace').value='';wgGeoOptions();uRows(k)};wgGeoOptions();uRows(k)}
 if(k==='project'&&$('wgOutputPeriod')){let r=WG().records[id];function draw(){let mode=$('wgOutputPeriod').value,rows=wgOutputs(r).filter(x=>mode==='all'||(mode==='half')===x.period.includes('半年'));const buckets=rows.map(x=>({key:x.period,value:x.value}));$('wgOutputChart').innerHTML=ixSvg(buckets,{unit:'镍金属吨',width:Math.max(320,$('wgOutputChart').clientWidth||640)});ixMarkEvents($('wgOutputChart'),buckets,b=>{$('wgOutputRows').querySelectorAll('tr').forEach(t=>t.classList.toggle('wg-highlight',t.dataset.period===b.key))},'镍金属吨');$('wgOutputRows').innerHTML='<div class="table-wrap"><table><thead><tr><th>期间</th><th>镍金属吨</th><th>口径</th></tr></thead><tbody>'+rows.map(x=>`<tr data-period="${x.period}"><td>${x.period}</td><td>${F(x.value)}</td><td>${E(r.output_basis||'底表所列口径')}</td></tr>`).join('')+'</tbody></table></div>'}draw();$('wgOutputPeriod').onchange=draw;$('wgOutputDownload').onclick=()=>ixDownload([['期间','镍金属吨','口径','底表编号'],...wgOutputs(r).map(x=>[x.period,x.value,r.output_basis,r.source_id])],'项目披露产量.csv')}
}
function wgGeoOptions(){let code=$('uCountry').value,ps=wgProjects(code),ids=new Set(ps.map(p=>geoLoc(p.id)?.place_id)),islands=new Set(ps.map(p=>geoLoc(p.id)?.island_id));for(let [el,items,text] of [['uIsland',G().islands.filter(x=>islands.has(x.id)),'全部岛屿／地区'],['uPlace',G().places.filter(x=>ids.has(x.id)),'全部园区／区域']]){let old=$(el).value;$(el).innerHTML=`<option value="">${text}</option>`+items.map(x=>`<option value="${x.id}">${E(x.name)}</option>`).join('');$(el).value=items.some(x=>x.id===old)?old:''}}

const wgOldResolve=uResolve;uResolve=function(k,id){if(['park','island'].includes(k)&&id?.startsWith('country-'))return ['country',id.slice(8)];return wgOldResolve(k,id)};
const wgOldAbout=about;about=function(){return wgOldAbout().replace('追踪印尼镍从矿石','追踪各地镍原料从矿石').replace('项目库包含印尼工厂、建设规划、贸易主体和海外比较对象；条目数不等于印尼在产工厂数。','项目库覆盖48个国家和地区，包含工厂、建设规划、贸易主体、历史设施和跨厂档案；条目数不等于在产工厂数。').replace('<h2>出口样本按产品阅读</h2>','<h2>全球普查如何接入</h2><p>2026年9月全球底表的166条记录中，12条与既有项目合并，154条新增；原有项目链接保留。中国大陆新增170份企业与项目档案；灰色地图区域表示当前资料未覆盖。</p><p>运行状态沿用逐条核实年份，不把导入日期当成重新确认生产的日期。三份底稿分别用于逐厂字段、报告背景和范围核对；来源链接保留，明显冲突另作记录。</p><div class="actions"><a href="library/global-register.csv" download>逐厂资料表 ↓</a><a href="library/global-crosswalk.csv" download>原表与百科编号对照 ↓</a><a href="library/global-import-notes.md">本次整理说明 →</a></div><h2>出口样本按产品阅读</h2>')};
