// Group dossiers share the project, geography, product and source indexes.
const GP=()=>window.GROUP_PROFILES;
const gpProjects=id=>{const c=U().companies.find(c=>c.id===id);return (c?.project_ids||[]).map(id=>U().projects.find(p=>p.id===id)).filter(Boolean)};
function gpCountries(ps){return [...new Set(ps.flatMap(p=>p.country_codes||[]))].map(wgCountry).filter(Boolean)}
function gpScopes(p){return Object.keys(WG_PRODUCTS).filter(s=>geoScope(p,s))}
function gpCites(a,refs=[]){return `<sup class="wiki-cites">${refs.filter(i=>a.sources[i]).map(i=>`<a href="${E(a.sources[i].url)}" target="_blank" rel="noopener" title="${E(a.sources[i].title)}">[${i+1}]</a>`).join('')}</sup>`}
function gpEvents(id){const a=GP().groups[id],ps=gpProjects(id),own=(a.timeline||[]).map(e=>({...e,category:'集团发展',url:a.sources[e.source]?.url,source_title:a.sources[e.source]?.title}));const project=ps.flatMap(p=>(HISTORY.projects[p.id]?.events||[]).filter(e=>!String(e.label).includes('底表投产年')).map(e=>({date:e.date,title:e.label,detail:e.detail,category:'项目事件',project_id:p.id,url:e.source_url,source_title:e.source_title})));return [...own,...project]}
uGroup=function(id){const c=U().companies.find(c=>c.id===id),a=GP().groups[id];if(!c||!a)return missing();const ps=gpProjects(id),countries=gpCountries(ps),pending=a.pending||[];
return `<div class="kicker"><a href="#/groups">母公司与集团</a> / ${E(a.kind||'企业档案')}</div><h1>${E(c.name)}</h1><p class="lead">${E(a.intro)}</p><div class="wiki-layout group-dossier" data-group="${E(id)}"><article class="wiki-prose"><nav class="wiki-toc" aria-label="集团条目目录"><strong>目录</strong>${a.sections.map((s,i)=>`<a href="#" data-scroll="group-section-${i}">${i+1}. ${E(s.title)}</a>`).join('')}<a href="#" data-scroll="group-projects">关联企业与项目</a><a href="#" data-scroll="group-history">发展时间线</a><a href="#" data-scroll="group-sources">参考资料</a></nav>${a.sections.map((s,i)=>`<section id="group-section-${i}"><h2>${E(s.title)}</h2>${s.paragraphs.map((p,j)=>`<p>${E(p)}${j===s.paragraphs.length-1?gpCites(a,s.refs):''}</p>`).join('')}</section>`).join('')}
<section id="group-projects"><h2>关联企业与项目</h2><p>从下表进入工厂，可继续查看设备、产品、股东和客户。关联关系包括控股、参股、历史投资及商业合作，各项目分别说明。</p><div class="filters"><input id="gpProjectQuery" aria-label="搜索集团关联项目" placeholder="查项目、园区或关系"><select id="gpCountry" aria-label="筛选项目国家"><option value="">全部国家与地区</option>${countries.map(c=>`<option value="${c.id}">${E(c.flag+' '+c.name)}</option>`).join('')}</select><select id="gpProduct" aria-label="筛选集团项目产品"><option value="">全部产品</option>${Object.entries(WG_PRODUCTS).map(([k,v])=>`<option value="${k}">${E(v)}</option>`).join('')}</select><button id="gpReset">重置</button></div><div id="gpProjectRows"></div></section>
<section id="group-history"><h2>发展时间线</h2><div class="filters"><select id="gpHistoryType" aria-label="筛选时间线事件"><option value="">全部事件</option><option value="集团发展">集团发展</option><option value="项目事件">项目事件</option></select><select id="gpHistoryOrder" aria-label="集团时间线排序"><option value="asc">从早到晚</option><option value="desc">最新在前</option></select></div><div id="gpHistoryRows"></div></section>
<section id="group-sources" class="reading-information"><h2>参考资料</h2><ol class="source-list">${a.sources.map(s=>`<li><a href="${E(s.url)}" target="_blank" rel="noopener">${E(s.title||'企业资料')} ↗</a>${s.locator?`<span class="meta">${E(s.locator)}</span>`:''}</li>`).join('')}</ol></section>${pending.length?`<details class="reading-notes"><summary>需要再确认</summary>${pending.map(p=>`<p>${E(p)}</p>`).join('')}</details>`:''}</article>
<aside class="wiki-facts project-infobox group-infobox" aria-label="集团简明资料"><div class="infobox-title"><span>企业与投资体系</span><h2>${E(c.name)}</h2></div><dl><div class="fact-row"><dt>档案类型</dt><dd>${E(a.kind||'集团与企业')}</dd></div>${(a.facts||[]).map(([k,v])=>`<div class="fact-row"><dt>${E(k)}</dt><dd>${E(v)}</dd></div>`).join('')}<div class="fact-row"><dt>关联项目地区</dt><dd>${countries.map(c=>A('country',c.id,c.flag+' '+c.name)).join('<br>')}</dd></div><div class="fact-row"><dt>已收录项目</dt><dd>${ps.length}项</dd></div></dl><div class="infobox-foot"><a href="#" data-scroll="group-projects">查看项目与关系 ↓</a><a href="#" data-scroll="group-history">查看发展时间线 ↓</a><a href="#" data-scroll="group-sources">资料来源 ↓</a><a href="#/groups">全部母公司与集团 →</a></div></aside></div>`};
function gpRenderProjects(id){const a=GP().groups[id],q=$('gpProjectQuery').value.trim().toLowerCase(),country=$('gpCountry').value,scope=$('gpProduct').value,ps=gpProjects(id).filter(p=>(!q||[p.name,p.ownership,geoLoc(p.id)?.locality,a.relation_notes?.[p.id]].join(' ').toLowerCase().includes(q))&&(!country||p.country_codes?.includes(country))&&(!scope||geoScope(p,scope)));
$('gpProjectRows').innerHTML=`<p class="meta">${ps.length}项关联项目</p>`+(ps.length?`<div class="table-wrap"><table class="group-project-table"><thead><tr><th>企业／项目</th><th>地点与产品</th><th>与本集团的关系</th><th>运行状态与客户</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${A('project',p.id,projectTitle(p.id))}</td><td>${wgCountryLinks(p.id)}<span class="sub">${E(geoLoc(p.id)?.locality||'')}</span><span class="sub">${E(uProducts(p))}</span></td><td>${E(a.relation_notes?.[p.id]||p.ownership)}</td><td>${opBadge(p.id)}<span class="sub">${exportMiniLinks(p.id)}</span><a href="#/project/${p.id}">产品与客户 →</a></td></tr>`).join('')}</tbody></table></div>`:'<p>没有符合条件的项目。</p>')}
function gpRenderHistory(id){const type=$('gpHistoryType').value,order=$('gpHistoryOrder').value,events=gpEvents(id).filter(e=>!type||e.category===type);events.sort((a,b)=>String(a.date).localeCompare(String(b.date),'en',{numeric:true})*(order==='desc'?-1:1));const render=e=>`<article class="group-event"><span class="group-event-date">${E(e.date)}</span><div><span class="meta">${E(e.category)}${e.project_id?' · '+A('project',e.project_id,projectTitle(e.project_id)):''}</span><h3>${E(e.title)}</h3><p>${E(e.detail||'')}</p>${e.url?`<a class="meta" href="${E(e.url)}" target="_blank" rel="noopener">${E(e.source_title||'资料来源')} ↗</a>`:''}</div></article>`;$('gpHistoryRows').innerHTML=`<p class="meta">${events.length}个已收录事件</p>`+(events.length?events.slice(0,16).map(render).join('')+(events.length>16?`<details class="group-more-events"><summary>展开其余${events.length-16}个事件</summary>${events.slice(16).map(render).join('')}</details>`:''):'<p>该筛选下暂无单独记录的事件，可在关联项目中继续阅读历史。</p>')}
function gpBind(key,id){if(key!=='group'||!GP().groups[id])return;gpRenderProjects(id);gpRenderHistory(id);$('gpProjectQuery').oninput=()=>gpRenderProjects(id);for(const k of ['gpCountry','gpProduct'])$(k).onchange=()=>gpRenderProjects(id);$('gpReset').onclick=()=>{for(const k of ['gpProjectQuery','gpCountry','gpProduct'])$(k).value='';gpRenderProjects(id)};for(const k of ['gpHistoryType','gpHistoryOrder'])$(k).onchange=()=>gpRenderHistory(id)}
const gpOldDirectory=uDirectory;uDirectory=function(kind){if(kind!=='groups')return gpOldDirectory(kind);return `<div class="kicker">全球镍产业百科</div><h1>母公司与集团</h1><p class="lead">从公司怎样发展，读到它为什么投资镍、项目建在哪里，以及产品流向哪些加工环节。</p><div class="filters"><input id="uQ" aria-label="搜索统一资料库" placeholder="查集团、企业、项目或发展历史"><select id="uScope" aria-label="产品资料范围"><option value="">全部产品</option>${Object.entries(WG_PRODUCTS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div id="uResults"></div>`};
const gpOldRows=uRows;uRows=function(kind){if(kind!=='groups')return gpOldRows(kind);const q=$('uQ').value.trim().toLowerCase(),scope=$('uScope').value,cs=U().companies.filter(c=>(!q||[c.name,c.intro,c.search_text,JSON.stringify(GP().groups[c.id])].join(' ').toLowerCase().includes(q))&&(!scope||gpProjects(c.id).some(p=>geoScope(p,scope))));$('uResults').innerHTML=`<p class="meta">${cs.length}个集团、企业与投资体系</p><div class="entries">${cs.map(c=>{const a=GP().groups[c.id];return `<article class="entry"><span class="meta">${E(a?.kind||'集团与企业')}</span><h3>${A('group',c.id,c.name)}</h3><p>${E(a?.intro||c.intro)}</p><span class="meta">${c.project_ids.length}项关联项目 · ${gpCountries(gpProjects(c.id)).map(c=>E(c.flag+' '+c.name)).join(' / ')}</span><p>${A('group',c.id,'历史、业务与项目关系 →')}</p></article>`}).join('')}</div>`};
for(const c of U().companies){const a=GP().groups[c.id];if(a){c.intro=a.intro;c.search_text+=' '+a.intro+' '+a.sections.map(s=>s.title+' '+s.paragraphs.join(' ')).join(' ')}}
