// The homepage indexes the existing encyclopedia; every count is computed from the current data at render time.
const HOME_CHAIN=[
 {scope:'npi',name:'镍铁／NPI',topic:'npi',process:['rkef','回转窑—电炉'],out:'不锈钢',examples:[['NPI009','纬达贝镍业'],['GL073','多尼安博'],['GL127','塞罗马托索']]},
 {scope:'matte',name:'低冰镍／高冰镍',topic:'high-matte',process:['conversion','硫化与吹炼'],out:'硫酸镍、精炼镍',examples:[['P12','索罗瓦科'],['GL031','纳杰日达'],['GL016','哈尔亚瓦尔塔']]},
 {scope:'mhp',name:'MHP／MSP',topic:'mhp',process:['hpal','高压酸浸'],out:'硫酸镍',examples:[['MHP006','华越镍钴'],['MHP048','安巴托维'],['MHP049','穆林穆林']]},
 {scope:'sulfate',name:'硫酸镍',topic:'nickel-sulphate',process:['wet-refining','浸出与除杂'],out:'电池材料',examples:[['MHP011','青美邦'],['MHP046','特拉法姆'],['CN083','金川镍盐']]},
 {scope:'refined',name:'精炼镍',topic:'refined-nickel',process:['wet-refining','精炼与电积'],out:'合金、电镀与电池',examples:[['GL037','新居浜'],['GL106','铜崖精炼厂'],['CN153','金川纯镍']]}
];
const HOME_HOT=[['group','tsingshan','青山体系'],['group','huayou','华友'],['park','imip','IMIP'],['group','nornickel','诺镍'],['group','vale-gem-bnsi','淡水河谷'],['country','CN','中国大陆']];
const HOME_BINS=[[1,'1','#f1d4d2'],[2,'2–4','#e2a9a6'],[5,'5–9','#cb7773'],[10,'10–29','#ad4541'],[30,'30+','#861d21']];
function homeActive(ps){return ps.filter(p=>['operating','partial','trial'].includes(opGet(p.id)?.key)).length}
function homeFlag(id){const c=U().projects.find(p=>p.id===id)?.country_codes?.[0];return WG().countries.find(x=>x.id===c)?.flag||''}
function homePage(){let u=U(),h=HX(),cs=WG().countries,events=h.events.filter(e=>/^\d{4}-\d{2}(?:-\d{2})?$/.test(e.date)&&e.date<=(h.asof||'2026-09-18')&&e.kind!=='规划'&&geoLoc(e.project_id)?.island_id!=='overseas').sort((a,b)=>hxSort(b)-hxSort(a));let recent=[],seen=new Set();for(let e of events){if(!seen.has(e.project_id)){recent.push(e);seen.add(e.project_id)}if(recent.length===4)break}
 const counts=cs.map(c=>[c,wgProjects(c.id).length]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]),regions=[...new Set(cs.map(c=>c.region))].map(r=>{const rc=cs.filter(c=>c.region===r);return [r,rc.length,rc.reduce((n,c)=>n+wgProjects(c.id).length,0)]});
 return `<div class="home-index">
 <section class="hv-hero"><div class="hv-intro"><div class="kicker">工厂 · 公司 · 园区 · 产业链</div><h1>全球镍产业百科</h1><p class="hv-lead">${cs.length}个国家与地区的${F(u.projects.length)}份工厂与项目档案：谁在生产、用什么工艺、产品卖给谁。</p>
 <form id="homeSearch" class="hi-search" role="search"><label class="sr-only" for="homeQuery">搜索百科</label><input id="homeQuery" type="search" placeholder="输入工厂、公司、园区或产品名称" required><button type="submit">搜索百科 →</button></form>
 <p class="hv-hot">常查：${HOME_HOT.map(([k,id,t])=>`<a href="#/${k}/${id}">${t}</a>`).join('')}</p><p class="hv-date">资料整理 ${E(h.asof)}</p></div>
 <figure class="hv-map"><div id="homeMap" class="wg-map" aria-label="各国项目档案数量地图"></div><figcaption><span class="hv-legend">${HOME_BINS.map(([,t,c])=>`<span><i style="background:${c}"></i>${t}</span>`).join('')}<span>份档案</span></span><span id="homeMapNote">点击国家进入项目目录</span></figcaption></figure></section>
 <div class="hi-stats">${[['projects',u.projects.length,'项目档案'],['projects',homeActive(u.projects),'在产／部分生产'],['world',cs.length,'国家与地区'],['groups',u.companies.length,'母公司与集团'],['exports',window.EXPORTS?EXPORTS.records.length:EX_SUMMARY.total,'出口记录']].map(([r,n,label])=>`<a href="#/${r}"><strong>${F(n)}</strong><span>${label} ↗</span></a>`).join('')}</div>
 <section class="hv-chain"><div class="section-head"><h2>镍从矿石到产品</h2><a href="#/topics">产品与工艺研究 →</a></div><div class="hv-flow"><div class="hv-ore"><strong>矿石原料</strong><span>红土镍矿</span><span>硫化镍矿</span></div><div class="hv-routes">${HOME_CHAIN.map(c=>`<div class="hv-route" data-p="${c.scope}"><span class="hv-proc">${A('topic',c.process[0],c.process[1])}</span><span class="hv-arrow" aria-hidden="true">→</span><span class="hv-prod">${A('topic',c.topic,c.name)}<a class="hv-count" href="#/projects/${c.scope}">${F(u.projects.filter(p=>geoScope(p,c.scope)).length)}个项目</a></span><span class="hv-arrow" aria-hidden="true">→</span><span class="hv-out">${c.out}</span><span class="hv-eg">例：${c.examples.map(([id,t])=>`<a href="#/project/${id}">${homeFlag(id)} ${t}</a>`).join('')}</span></div>`).join('')}</div></div></section>
 <section class="hv-regions"><div class="section-head"><h2>按地区查找</h2><a href="#/world">${cs.length}个国家与地区 →</a></div><div class="hv-region-list">${regions.map(([r,n,p])=>`<a href="#/world/${encodeURIComponent(r)}"><strong>${E(r)}</strong><span>${n}国 · ${F(p)}份档案</span></a>`).join('')}</div><p class="hv-top">${counts.slice(0,10).map(([c,n])=>`<a href="#/country/${c.id}">${c.flag} ${E(c.name)}<b>${n}</b></a>`).join('')}</p></section>
 <div class="hi-columns"><section><div class="section-head"><h2>近期历史事件</h2><a href="#/timeline">完整时间线 →</a></div><div class="hi-history">${recent.map(e=>`<article><time>${E(e.date)}</time><div><h3>${A('project',e.project_id,e.label)}</h3><p>${E(window.WIKI_ARTICLES[e.project_id]?.title||u.projects.find(p=>p.id===e.project_id)?.name)}</p><a class="small-link" href="${E(e.source_url)}" target="_blank" rel="noopener">事件资料 ↗</a></div></article>`).join('')}</div></section><section><div class="section-head"><h2>顺着产业关系查</h2></div><div class="hi-reading">${[['groups','谁投资、谁控制？','从母公司进入各地项目，查股东、收购和产业布局。'],['customers','产品卖给谁？','查买方背景、加工用途、集团关系和承购安排。'],['exports','什么时候发货、发了多少？','按产品与项目查看出口走势，点击图表进入客户和逐票明细。'],['chains','跨厂加工链','从一座工厂的产品追到下一道工序和最终精炼厂。']].map(([r,t,s])=>`<a href="#/${r}"><h3>${t}<span>→</span></h3><p>${s}</p></a>`).join('')}</div></section></div>
 <section class="hi-geography"><div class="section-head"><h2>印尼园区与产业集群</h2><a href="#/parks">全部园区与岛屿 →</a></div><div class="hi-places">${[['imip','IMIP · 莫罗瓦利'],['iwip','IWIP · 纬达贝'],['obi-harita','Obi · Harita运营区'],['huabao','IHIP · 华宝'],['north-morowali','北莫罗瓦利 · 德龙'],['ipip','IPIP · 波马拉']].map(([id,name])=>{let p=geoPlace(id),count=u.projects.filter(x=>geoLoc(x.id)?.place_id===id).length;return `<a href="#/park/${id}"><span>${E(p.island)}</span><h3>${name}</h3><p>${count}个已收录项目 <b>↗</b></p></a>`}).join('')}</div></section>
 <section class="hi-sources"><div class="section-head"><h2>资料说明</h2><a href="#/sources">查看资料来源 →</a></div><p>本库以企业公告、财报、园区资料及行业资料建立项目档案，并连接${F(window.EXPORTS?EXPORTS.records.length:EX_SUMMARY.total)}条用户提供的出口样本。项目目录包含在产、在建、规划、历史项目及相关贸易主体；全球普查记录与中国项目表并入同一目录，同一工厂只保留一份档案。各项目保留原始资料时点，档案数不等于在产工厂数。</p><div class="hi-downloads"><a href="library/npi-audit.xlsx">镍铁产线产能表 ↓</a><a href="library/mhp-audit.xlsx">MHP项目核查表 ↓</a><a href="library/project-history.csv">项目历史事件表 ↓</a><a href="#/research">研究进展与待核 →</a><a href="#/about">统计口径 →</a></div></section></div>`}
function homeMapBind(){const box=$('homeMap');if(!box||!window.WORLD_MAP_SVG)return;box.innerHTML=WORLD_MAP_SVG;const note=$('homeMapNote'),rest=note.textContent;box.querySelectorAll('a[href^="#/country/"]').forEach(a=>{const code=a.getAttribute('href').split('/').pop(),c=wgCountry(code),ps=wgProjects(code),n=ps.length,bin=HOME_BINS.filter(b=>n>=b[0]).pop();if(!c||!n)return;a.querySelectorAll('path').forEach(p=>p.style.fill=bin[2]);const label=`${c.flag} ${c.name}：${n}份档案`+(code==='CN'?'':` · ${homeActive(ps)}项在产／部分生产`),t=a.querySelector('title');if(t)t.textContent=label;a.onmouseenter=a.onfocus=()=>note.textContent=label;a.onmouseleave=a.onblur=()=>note.textContent=rest})}
function homeBind(){if(!$('homeSearch'))return;$('homeSearch').onsubmit=e=>{e.preventDefault();let q=$('homeQuery').value.trim();if(q)location.hash='/search/'+encodeURIComponent(q)};homeMapBind()}
