// The homepage indexes the existing encyclopedia; counts come from its current data.
const HOME_PRODUCTS=[
 {id:'npi',name:'镍铁 / NPI',topic:'npi',scope:'npi',trade:'npi',text:'镍铁是印尼不锈钢原料链的重要起点。矿石经干燥、焙烧和电炉冶炼形成含镍铁合金，进入不锈钢厂；部分工厂也能通过后续硫化和吹炼衔接冰镍生产。',chain:[['rkef','回转窑—电炉'],['npi','镍铁'],[null,'不锈钢原料']],items:[['NPI020','旭日金属工业','从试产、股权调整到低冰镍能力，理解一家镍铁厂如何连接集团的下游业务。'],['NPI051','硕石镍铁','沿华宝园区建设，查看首条产线与全线投产的先后，以及镍铁产能的实物口径。'],['NPI009','纬达贝镍业','把矿山、镍铁冶炼和Eramet销售渠道放在同一个项目中阅读。']]},
 {id:'low',name:'低冰镍',topic:'low-matte',scope:'matte',trade:'low',text:'低冰镍是含镍、铁和硫的冶炼中间品，需要继续除铁、富集镍。它可以在同一厂内升级，也可以卖给另一座工厂加工；理解这一步，才能看清镍铁厂与高冰镍厂之间的供料关系。',chain:[['low-matte','低冰镍'],['conversion','转炉除铁'],['high-matte','高冰镍']],items:[['NPI008','友山镍业','从镍铁原料采购、低冰镍生产及对华科供料，阅读跨厂加工链。'],['NPI020','旭日金属工业','查看华新丽华旗下项目的设备、镍铁与低冰镍产品经历。'],['P02','中青新能源','了解低冰镍、高冰镍连续生产路线，以及分期建设和股权变化。']]},
 {id:'high',name:'高冰镍',topic:'high-matte',scope:'matte',trade:'high',text:'高冰镍是富集后的镍硫化物原料，可送往精炼厂生产镍盐或精炼镍。项目的供销安排既与股东体系有关，也受到加工设施、产品规格和长期合同影响。',chain:[['high-matte','高冰镍'],['wet-refining','浸出与精炼'],['nickel-sulphate','硫酸镍']],items:[['P01','华能金属工业','阅读收购、生产调整、销售合同与复产之间的关系。'],['NPI004','妮可镍业','追踪POSCO参股后，由原有NPI业务向高冰镍延伸的过程。'],['P12','Sorowako高冰镍','从长期运营历史、炉子重建及承购安排，理解传统冰镍项目。']]},
 {id:'mhp',name:'MHP',topic:'mhp',scope:'mhp',trade:'mhp',text:'MHP是镍钴混合氢氧化物。印尼湿法项目通常利用高压酸浸处理褐铁矿，再将镍钴沉淀为中间品。矿源、酸和能源供应、股东承购及后续精炼，共同决定项目如何运行。',chain:[['hpal','高压酸浸'],['mhp','MHP'],['wet-refining','后续精炼']],items:[['MHP006','华越镍钴','从建设、首产和达产，读到矿石供应及与股东加工业务的衔接。'],['MHP003','Obi岛HPL湿法项目','查看岛内从MHP向硫酸镍延伸的建设历史、产销和出口。'],['MHP011','青美邦','从分期扩建走向硫酸镍晶体和电积镍，理解多产品经营。']]},
 {id:'sulfate',name:'硫酸镍',topic:'nickel-sulphate',scope:'sulfate',trade:'sulfate',text:'硫酸镍将上游镍原料连接到电池材料加工。MHP或高冰镍经浸出、除杂等工序得到镍盐；溶液与结晶产品的销售、运输和产能口径各不相同。',chain:[['wet-refining','浸出与除杂'],['nickel-sulphate','硫酸镍'],[null,'电池材料']],items:[['MHP003','HPL硫酸镍','在同一项目中对照自产、委外加工、销量与逐票出口。'],['MHP011','青美邦硫酸镍','分开阅读晶体产能、镍金属量与电积镍产线。'],['MHP017','Excelsior Nickel Cobalt','查看MHP、阴极镍与硫酸镍规划之间的关系，以及各产品的进度。']]},
 {id:'refined',name:'精炼镍',topic:'refined-nickel',scope:'refined',trade:'refined',text:'精炼镍把镍原料进一步加工成高纯度金属。原料来源、精炼工序、产品品牌和销售渠道，是理解印尼精炼镍项目的主要线索；投产、品牌注册与实际发货分别记录。',chain:[['wet-refining','精炼与电积'],['refined-nickel','精炼镍'],[null,'合金与其他用镍领域']],items:[['RF001','中伟鼎兴','查看项目建设、合资股东、承购安排、品牌注册及发货。'],['RF002','永恒镍业','沿股东结构和精炼镍销售，阅读项目与下游企业的联系。'],['MHP011','青美邦电积镍','查看镍板产线的建设、开通及其与原有湿法加工的衔接。']]}
];
function homePage(){let u=U(),g=G(),h=HX(),events=h.events.filter(e=>/^\d{4}-\d{2}(?:-\d{2})?$/.test(e.date)&&e.date<=(h.asof||'2026-09-18')&&e.kind!=='规划'&&geoLoc(e.project_id)?.island_id!=='overseas').sort((a,b)=>hxSort(b)-hxSort(a));let recent=[],seen=new Set();for(let e of events){if(!seen.has(e.project_id)){recent.push(e);seen.add(e.project_id)}if(recent.length===4)break}return `<div class="home-index">
 <div class="hi-heading"><div><div class="kicker">工厂 · 公司 · 园区 · 产业链</div><h1>印尼镍产业百科</h1><p>从镍铁、低冰镍、高冰镍和MHP，到硫酸镍与精炼镍，查阅项目的建设历史、设备产能、股东与供销关系。</p></div><span class="hi-date">资料整理 <br>${E(h.asof)}</span></div>
 <form id="homeSearch" class="hi-search" role="search"><label class="sr-only" for="homeQuery">搜索百科</label><input id="homeQuery" type="search" placeholder="输入工厂、公司、园区或产品名称" required><button type="submit">搜索百科 →</button></form>
 <div class="hi-stats">${[['projects',u.projects.length,'项目档案'],['groups',u.companies.length,'母公司与集团'],['customers',u.customers.length,'买方抬头'],['parks',g.places.length,'园区与区域'],['timeline',h.events.length,'历史事件']].map(([r,n,label])=>`<a href="#/${r}"><strong>${F(n)}</strong><span>${label} ↗</span></a>`).join('')}</div>
 <section class="hi-products"><div class="section-head"><h2>按产品阅读</h2><a href="#/topics">六个品目完整研究 →</a></div><div class="hi-tabs" role="tablist" aria-label="产品类别">${HOME_PRODUCTS.map((p,i)=>`<button id="home-tab-${p.id}" data-home-product="${p.id}" role="tab" aria-selected="${!i}" aria-controls="homeProduct" tabindex="${i?-1:0}">${p.name}</button>`).join('')}</div><div id="homeProduct" role="tabpanel" aria-labelledby="home-tab-npi">${homeProductPanel('npi')}</div></section>
 <section class="hi-geography"><div class="section-head"><h2>从园区找到工厂</h2><a href="#/parks">全部园区与岛屿 →</a></div><div class="hi-places">${[['imip','IMIP · 莫罗瓦利'],['iwip','IWIP · 纬达贝'],['obi-harita','Obi · Harita运营区'],['huabao','IHIP · 华宝'],['north-morowali','北莫罗瓦利 · 德龙'],['ipip','IPIP · 波马拉']].map(([id,name])=>{let p=geoPlace(id),count=u.projects.filter(x=>geoLoc(x.id)?.place_id===id).length;return `<a href="#/park/${id}"><span>${E(p.island)}</span><h3>${name}</h3><p>${count}个已收录项目 <b>↗</b></p></a>`}).join('')}</div><div class="hi-islands">${g.islands.map(i=>A('island',i.id,i.name)).join('')}<a href="#/projects">按岛屿筛选全部项目 →</a></div></section>
 <div class="hi-columns"><section><div class="section-head"><h2>近期历史事件</h2><a href="#/timeline">完整时间线 →</a></div><div class="hi-history">${recent.map(e=>`<article><time>${E(e.date)}</time><div><h3>${A('project',e.project_id,e.label)}</h3><p>${E(window.WIKI_ARTICLES[e.project_id]?.title||u.projects.find(p=>p.id===e.project_id)?.name)}</p><a class="small-link" href="${E(e.source_url)}" target="_blank" rel="noopener">事件资料 ↗</a></div></article>`).join('')}</div></section><section><div class="section-head"><h2>顺着产业关系查</h2></div><div class="hi-reading">${[['groups','谁投资、谁控制？','从母公司进入各地项目，查股东、收购和产业布局。'],['customers','产品卖给谁？','查买方背景、加工用途、集团关系和承购安排。'],['exports','什么时候发货、发了多少？','按产品与项目查看出口走势，点击图表进入客户和逐票明细。'],['graph','上下游如何连接？','沿原料供应、跨厂加工和销售关系继续阅读。']].map(([r,t,s])=>`<a href="#/${r}"><h3>${t}<span>→</span></h3><p>${s}</p></a>`).join('')}</div></section></div>
 <section class="hi-sources"><div class="section-head"><h2>资料说明</h2><a href="#/sources">查看资料来源 →</a></div><p>本库以企业公告、财报、园区资料及行业资料建立项目档案，并连接${F(EXPORTS.records.length)}条用户提供的出口样本。项目目录包含在产、在建、规划、历史项目及相关贸易主体，也收录部分海外加工项目作对照。正文与时间线中的资料链接可以直接打开。</p><div class="hi-downloads"><a href="library/npi-audit.xlsx">镍铁产线产能表 ↓</a><a href="library/mhp-audit.xlsx">MHP项目核查表 ↓</a><a href="library/project-history.csv">项目历史事件表 ↓</a><a href="#/about">统计口径 →</a></div><details class="reading-notes"><summary>需要再确认</summary><p>尚待补齐的日期、股权与产品信息收在各条目的同名栏目中。</p><a href="#/research">查看研究进展与待核事项 →</a></details></section></div>`}
function homeProductPanel(id){let p=HOME_PRODUCTS.find(p=>p.id===id);return `<div class="hi-product-intro"><div><h3>${p.name}</h3><p>${p.text}</p><div class="hi-chain">${p.chain.map(([id,t])=>id?A('topic',id,t):`<span>${t}</span>`).join('<span aria-hidden="true">→</span>')}</div></div><div class="hi-product-links"><a href="#/projects/${p.scope}">相关项目目录 →</a><a href="#/exports/~${p.trade}">出口与买方记录 →</a>${A('topic',p.topic,'进入完整品目研究 →')}</div></div><div class="hi-projects">${p.items.map(([id,title,text])=>`<article><span>${E(geoLoc(id)?.island||'')} · ${E(geoPlace(geoLoc(id)?.place_id)?.name||'')}</span><h3>${A('project',id,projectTitle(id,title))}</h3><p>${text}</p><a class="small-link" href="#/timeline/${id}">建设与运营时间线 →</a></article>`).join('')}</div>`}
function homeBind(){if(!$('homeSearch'))return;$('homeSearch').onsubmit=e=>{e.preventDefault();let q=$('homeQuery').value.trim();if(q)location.hash='/search/'+encodeURIComponent(q)};let tabs=[...document.querySelectorAll('[data-home-product]')];function choose(button,focus=false){tabs.forEach(b=>{b.setAttribute('aria-selected',String(b===button));b.tabIndex=b===button?0:-1});$('homeProduct').innerHTML=homeProductPanel(button.dataset.homeProduct);$('homeProduct').setAttribute('aria-labelledby',button.id);if(focus)button.focus()}tabs.forEach((b,i)=>{b.onclick=()=>choose(b);b.onkeydown=e=>{let index=e.key==='ArrowRight'?(i+1)%tabs.length:e.key==='ArrowLeft'?(i+tabs.length-1)%tabs.length:e.key==='Home'?0:e.key==='End'?tabs.length-1:null;if(index!==null){e.preventDefault();choose(tabs[index],true)}}})}
