// Link existing encyclopedia entities in prose, without rewriting source text or trade tables.
let proseIndex=null,proseObserver=null;
function proseLinkIndex(){if(proseIndex)return proseIndex;let candidates=new Map();const add=(alias,type,id,title)=>{alias=String(alias||'').trim();if(alias.length<2||alias.length>180||/^\d+$/.test(alias)||/待核|候选|待识别|需确认|项目库无对应/.test(alias))return;if(['MSP','CNI','AMI','SMI','HNC'].includes(alias.toUpperCase()))return;let key=alias.toLocaleLowerCase(),href='#/'+type+'/'+id;if(!candidates.has(key))candidates.set(key,{alias,targets:new Map()});candidates.get(key).targets.set(href,{href,title})};
 for(let p of U().projects){let n=PROJECT_NAMES[p.id];for(let t of [n.title,n.english,n.chinese,...n.aliases])add(t,'project',p.id,n.title);let english=n.english.replace(/\s*\([A-Z0-9]+\)\s*$/,'');add(english,'project',p.id,n.title);if(/^PT\s+/i.test(english))add(english.replace(/^PT\s+/i,''),'project',p.id,n.title);for(let m of n.english.matchAll(/\(([A-Z][A-Z0-9]{1,7})\)/g))add(m[1],'project',p.id,n.title)}
 const projectAliases={NPI008:['友山'],NPI022:['华科'],NPI020:['旭日','Sunny Metal'],NPI021:['纬创','Westrong'],NPI023:['翡翠湾'],NPI024:['澜凯'],NPI004:['妮可','Nicole Metal'],NPI005:['安琪'],NPI006:['蓝天'],NPI007:['雅石'],NPI010:['英菲'],NPI011:['科赞'],NPI012:['德邦'],NPI034:['华新镍业'],NPI038:['恒嘉','Hengjaya Nickel'],NPI039:['兰吉尔','Ranger Nickel'],NPI051:['硕石'],P01:['华能'],P02:['中青新能源'],P05:['华旭'],P09:['嘉曼'],P11:['寰宇'],P28:['嘉曼达'],P29:['嘉曼美'],P48:['恒生'],MHP003:['HPL'],MHP006:['华越'],MHP008:['华飞'],MHP011:['QMB','青美邦'],MHP014:['美明'],MHP015:['格林爱科'],MHP017:['ENC','晨曦镍钴'],MHP028:['诚盛'],MHP031:['华山镍钴'],RF001:['中伟鼎兴','鼎兴'],RF002:['永恒镍业','PTENICO'],RF003:['华翔精炼']};for(let [id,as]of Object.entries(projectAliases))for(let alias of as)add(alias,'project',id,projectTitle(id));
 // Group aliases are curated; the source records also contain subsidiaries, which must not be treated as group synonyms.
 const groupAliases={cngr:['中伟','中伟股份','CNGR'],weiming:['伟明环保','伟明'],huayou:['华友','华友钴业','Huayou'],tsingshan:['青山','青山控股','Tsingshan'],zhenshi:['振石','Zhenshi'],delong:['德龙集团'],jinchuan:['金川','金川集团'],gem:['格林美','GEM'],'catl-brunp':['宁德时代','CATL','邦普'],'lygend-resources':['力勤','力勤资源','Lygend'],'harita-nickel':['Harita','哈利达'],'harum-energy':['Harum','Harum Energy'],'walsin-lihwa':['华新丽华','华新','Walsin Lihwa'],'antam-mind-id':['ANTAM','安塔姆'],'shengtun-mining':['盛屯','盛屯矿业'],'eramet':['Eramet','埃赫曼'],'nickel-industries':['Nickel Industries','Nickel Industries Limited','NIC'],'merdeka-battery-materials':['Merdeka Battery Materials','MBMA'],'posco-holdings-nicole':['POSCO','POSCO Holdings','浦项'],'vale-gem-bnsi':['Vale','Vale Indonesia','淡水河谷'],'smm':['住友金属矿山','Sumitomo Metal Mining'],'ecopro':['EcoPro'],'hanrui':['寒锐钴业'],'dowstone':['道氏技术'],'ls-mnm':['LS MnM'],'neo-energy':['Neo Energy'],'glencore':['Glencore','嘉能可'],'seah':['SeAH','世亚特钢']};for(let c of U().companies){add(c.name,'group',c.id,c.name);for(let alias of groupAliases[c.id]||[])add(alias,'group',c.id,c.name)}
 // Only complete customer headings; brand-only shorthand may identify a different corporate level.
 for(let c of U().customers)if(c.name.length>=10)add(c.name,'customer',c.id,c.name);
 for(let p of G().places)add(p.name,'park',p.id,p.name);for(let i of G().islands)if(i.id!=='indonesia-unknown'&&i.id!=='overseas')add(i.name,'island',i.id,i.name);
 for(let [id,as]of Object.entries({imip:['IMIP','莫罗瓦利工业园'],iwip:['IWIP','纬达贝工业园'],'obi-harita':['Obi工业园','Harita综合运营区'],huabao:['IHIP','华宝工业园','华宝园区'],ipip:['IPIP'],'north-morowali':['SEI工业园']}))for(let alias of as)add(alias,'park',id,geoPlace(id).name);
 const topicAliases={npi:['NPI','镍铁','镍生铁'],'low-matte':['低冰镍'],'high-matte':['高冰镍'],mhp:['MHP','镍钴混合氢氧化物'],'nickel-sulphate':['硫酸镍'],'refined-nickel':['精炼镍'],rkef:['RKEF','回转窑—电炉'],oesbf:['OESBF','富氧侧吹'],conversion:['转炉低转高'],'wet-refining':['湿法精炼'],hpal:['HPAL','高压酸浸'],'commercial-arrangements':['股东承购','委托加工']};for(let t of K.topics)for(let alias of topicAliases[t.id]||[t.name])add(alias,'topic',t.id,t.name);
 const entries=[...candidates.values()].sort((a,b)=>b.alias.length-a.alias.length);let byKey=new Map(entries.map(e=>[e.alias.toLocaleLowerCase(),e.targets.size===1?[...e.targets.values()][0]:null]));let escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');proseIndex={byKey,regex:new RegExp(entries.map(e=>escape(e.alias)).join('|'),'giu')};return proseIndex}
function articleLinks(root=document.getElementById('main')){if(!root)return;proseObserver?.disconnect();try{statusDecorate(root);let {byKey,regex}=proseLinkIndex(),current='#/'+route.filter(Boolean).join('/'),skip='a,button,input,select,textarea,code,pre,script,style,svg,table,nav,summary,h1,h2,h3,h4,sup,.source-list,.source-entry,.mhp-sources,.wiki-cites,#wiki-sources,.ix-chart,.hi-sources,.filters,.meta,.legal,.actions,.tags';for(let block of root.querySelectorAll('p,li,dd')){if(block.closest(skip))continue;let linked=new Set([...block.querySelectorAll('a[href]')].map(a=>a.getAttribute('href'))),walker=document.createTreeWalker(block,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest(skip)?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(let node of nodes){let text=node.nodeValue,last=0,fragment=document.createDocumentFragment(),changed=false;regex.lastIndex=0;let urls=[...text.matchAll(/https?:\/\/\S+/g)].map(m=>[m.index,m.index+m[0].length]);for(let m of text.matchAll(regex)){let term=m[0],start=m.index,end=start+term.length,target=byKey.get(term.toLocaleLowerCase());if(!target||target.href===current||linked.has(target.href)||linked.size>=7||urls.some(([a,b])=>start>=a&&start<b))continue;if(/^[A-Za-z0-9]/.test(term)&&/[A-Za-z0-9_]/.test(text[start-1]||''))continue;if(/[A-Za-z0-9]$/.test(term)&&/[A-Za-z0-9_]/.test(text[end]||''))continue;fragment.append(document.createTextNode(text.slice(last,start)));let a=document.createElement('a');a.href=target.href;a.className='prose-link';a.textContent=term;a.title='阅读词条：'+target.title;fragment.append(a);last=end;changed=true;linked.add(target.href)}if(changed){fragment.append(document.createTextNode(text.slice(last)));node.replaceWith(fragment)}}}}finally{proseObserver?.observe(document.getElementById('main'),{childList:true,subtree:true})}}
// Filtering and product-tab updates also receive links, without changing their controls.
proseObserver=new MutationObserver(()=>articleLinks());proseObserver.observe(document.getElementById('main'),{childList:true,subtree:true});
