// Linked project histories and interactive exploration of the original trade rows.
const IX=new Map();let ixSequence=0;
function ixReset(){IX.clear();ixSequence=0;document.querySelector('.ix-tooltip')?.remove()}
function ixDownload(rows,name){let csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n'),u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function ixTradeChart(rows,title='出口走势'){
 if(!rows.length)return '<p class="meta">当前范围暂无出口记录。</p>';
 let id='ix-'+(++ixSequence),months=[...new Set(rows.map(r=>r.month||r.date.slice(0,7)))].sort();
 IX.set(id,{rows,title,start:months[0],end:months.at(-1),from:months[0],to:months.at(-1),period:'month',mode:'bar',selected:null});
 return `<section class="ix-chart" id="${id}"><div class="ix-heading"><h4>${E(title)}</h4><span>实物吨</span></div><div class="ix-controls"><label>汇总<select data-ix="period"><option value="month">月度</option><option value="quarter">季度</option><option value="year">年度</option></select></label><label>图形<select data-ix="mode"><option value="bar">柱状图</option><option value="line">折线图</option></select></label><label>从<input type="month" data-ix="from" value="${months[0]}"></label><label>至<input type="month" data-ix="to" value="${months.at(-1)}"></label><button data-ix="reset">重置</button></div><div class="ix-summary" aria-live="polite"></div><div class="ix-plot"></div><p class="ix-hint">悬停查看数值；点击柱子或折线节点，展开该期买方和逐票记录。手机可直接点选。</p><div class="ix-selection" aria-live="polite"></div><div class="ix-actions"><button data-ix="table">查看数据表</button><button data-ix="download">下载图表数据</button></div><div class="ix-data" hidden></div></section>`;
}
function ixPeriod(month,p){return p==='year'?month.slice(0,4):p==='quarter'?month.slice(0,4)+' Q'+Math.ceil(Number(month.slice(5,7))/3):month}
function ixBuckets(s){let selected=s.rows.filter(r=>r.month>=s.from&&r.month<=s.to),map={};if(s.from<=s.to){let [y,m]=s.from.split('-').map(Number),end=s.to;for(let n=0;n<1200;n++){let date=y+'-'+String(m).padStart(2,'0');if(date>end)break;let key=ixPeriod(date,s.period);map[key]??={key,value:0,rows:[]};if(++m===13){m=1;y++}}}for(let r of selected){let key=ixPeriod(r.month,s.period),b=map[key]??={key,value:0,rows:[]};b.value+=Number(r.counted||0);b.rows.push(r)}return Object.values(map).sort((a,b)=>a.key.localeCompare(b.key))}
function ixSvg(buckets,{mode='bar',selected=null,unit='实物吨',width=null}={}){let max=unit==='项事件'?Math.ceil(Math.max(...buckets.map(b=>b.value),1)/4)*4:Math.max(...buckets.map(b=>b.value),1),n=buckets.length,w=width||Math.max(720,n*19+90),left=70,right=40,top=28,bottom=220,h=bottom-top,step=(w-left-right)/Math.max(1,n);let x=i=>left+step*(i+.5),y=v=>bottom-v/max*h;return `<svg viewBox="0 0 ${w} 270" style="min-width:${Math.min(w,900)}px" aria-label="可交互图表，点击数据点查看详情"><g class="ix-grid">${[0,.25,.5,.75,1].map(t=>`<line x1="${left}" y1="${y(max*t)}" x2="${w-right}" y2="${y(max*t)}"/><text x="${left-8}" y="${y(max*t)+4}" text-anchor="end">${F(max*t)}</text>`).join('')}</g>${mode==='line'?`<polyline points="${buckets.map((b,i)=>x(i)+','+y(b.value)).join(' ')}" fill="none" stroke="#a51b25" stroke-width="2.5"/>`:''}${buckets.map((b,i)=>`<g class="ix-mark ${selected===b.key?'selected':''}" data-point="${i}" tabindex="0" role="button" aria-label="${E(b.key)}，${F(b.value)} ${unit}，点击查看详情" aria-pressed="${selected===b.key}"><rect class="ix-hit" x="${left+i*step}" y="${top}" width="${step}" height="${h+5}" fill="transparent"/>${mode==='bar'?`<rect class="ix-bar" x="${x(i)-step*.33}" y="${y(b.value)}" width="${step*.66}" height="${Math.max(b.value?2:0,y(0)-y(b.value))}"/>`:`<circle class="ix-dot" cx="${x(i)}" cy="${y(b.value)}" r="${selected===b.key?6:4}"/>`}<title>${E(b.key)}：${F(b.value)} ${unit}</title></g>${(i%Math.max(1,Math.ceil(n/10))===0&&(n-1-i)*step>75)||i===n-1?`<text class="ix-axis" x="${x(i)}" y="246" text-anchor="middle">${E(b.key)}</text>`:''}`).join('')}</svg>`}
function ixTooltip(text,el){let tip=document.querySelector('.ix-tooltip');if(!tip){tip=document.createElement('div');tip.className='ix-tooltip';tip.setAttribute('role','tooltip');document.body.appendChild(tip)}tip.textContent=text;let rect=el.getBoundingClientRect();tip.style.left=Math.min(Math.max(8,rect.left),innerWidth-260)+'px';tip.style.top=Math.max(6,Math.min(innerHeight-85,rect.top-65))+'px';tip.hidden=false}
function ixHideTip(){let t=document.querySelector('.ix-tooltip');if(t)t.hidden=true}
function ixMarkEvents(plot,buckets,select,unit='实物吨'){plot.querySelectorAll('[data-point]').forEach(el=>{let b=buckets[Number(el.dataset.point)];el.onpointerenter=()=>ixTooltip(`${b.key} · ${F(b.value)} ${unit}${b.rows?' · '+b.rows.length+'条记录':''}`,el);el.onpointerleave=ixHideTip;el.onfocus=()=>ixTooltip(`${b.key} · ${F(b.value)} ${unit}`,el);el.onblur=ixHideTip;el.onclick=()=>{ixHideTip();select(b)};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(b)}if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();let i=Number(el.dataset.point)+(e.key==='ArrowLeft'?-1:1);plot.querySelector(`[data-point="${Math.max(0,Math.min(buckets.length-1,i))}"]`)?.focus()}}})}
function ixRowTable(rs){return `<div class="table-wrap"><table><thead><tr><th>日期／原票</th><th>出口商</th><th>买方</th><th>实物吨</th></tr></thead><tbody>${rs.slice(0,100).map(r=>`<tr><td>${E(r.date)}<span class="sub">${E(r.id)}</span></td><td>${r.project&&U().projects.some(p=>p.id===r.project)?A('project',r.project,r.exporter):E(r.exporter)}</td><td>${r.customer?A('customer',r.customer,r.buyer):E(r.buyer)}</td><td>${F(r.tonnes)}${r.counted!==r.tonnes?`<span class="sub">参考计入 ${F(r.counted)}</span>`:''}</td></tr>`).join('')}</tbody></table></div>${rs.length>100?'<p class="meta">显示前100条；可下载所选期间的全部记录。</p>':''}`}
function ixDraw(id){let el=$(id),s=IX.get(id);if(!el||!s)return;let a=ixBuckets(s);s.buckets=a;if(!a.some(b=>b.key===s.selected))s.selected=null;let rs=a.flatMap(b=>b.rows);el.querySelector('.ix-summary').textContent=s.from>s.to?'开始月份晚于结束月份，请调整范围。':`${s.from}—${s.to} · ${F(exSum(rs))} 实物吨 · ${rs.length}条记录${rs.some(r=>r.product==='sulfate')?' · 同票候选按参考口径计入':''}`;let plot=el.querySelector('.ix-plot');plot.innerHTML=a.length?ixSvg(a,s):'<p>当前范围没有记录。</p>';ixMarkEvents(plot,a,b=>{s.selected=s.selected===b.key?null:b.key;ixDraw(id)});let selected=a.find(b=>b.key===s.selected),detail=el.querySelector('.ix-selection');detail.innerHTML=selected?`<div class="ix-detail-head"><h4>${E(selected.key)} · ${F(selected.value)} 实物吨</h4><button data-close-period>收起</button></div>${selected.rows.length?`${exRawNote(selected.rows)}${exBuyers(selected.rows,10)}<details><summary>查看${selected.rows.length}条原始记录</summary>${ixRowTable(selected.rows)}<button data-period-download>下载这期记录</button></details>`:'<p>本样本在这一期没有匹配记录。</p>'}`:'';if(selected){detail.querySelector('[data-close-period]').onclick=()=>{s.selected=null;ixDraw(id)};let btn=detail.querySelector('[data-period-download]');if(btn)btn.onclick=()=>ixDownload([['记录编号','日期','出口商','买方','产品','原始实物吨','参考计入实物吨'],...selected.rows.map(r=>[r.id,r.date,r.exporter,r.buyer,r.product,r.tonnes,r.counted])],'所选期间出口.csv')};el.querySelector('.ix-data').innerHTML=`<div class="table-wrap"><table><thead><tr><th>期间</th><th>实物吨</th><th>记录</th></tr></thead><tbody>${a.map(b=>`<tr><td>${E(b.key)}</td><td>${F(b.value)}</td><td>${b.rows.length}</td></tr>`).join('')}</tbody></table></div>`;}
function ixMount(root=document){root.querySelectorAll('.ix-chart').forEach(el=>{if(el.dataset.mounted)return;el.dataset.mounted='yes';let id=el.id,s=IX.get(id);if(!s)return;el.querySelectorAll('[data-ix]').forEach(c=>{let key=c.dataset.ix;if(['period','mode','from','to'].includes(key))c.onchange=()=>{s[key]=c.value||s[key];s.selected=null;ixDraw(id)};if(key==='reset')c.onclick=()=>{Object.assign(s,{from:s.start,to:s.end,period:'month',mode:'bar',selected:null});for(let k of ['from','to','period','mode'])el.querySelector(`[data-ix="${k}"]`).value=s[k];ixDraw(id)};if(key==='table')c.onclick=()=>{let t=el.querySelector('.ix-data');t.hidden=!t.hidden;c.textContent=t.hidden?'查看数据表':'收起数据表'};if(key==='download')c.onclick=()=>ixDownload([['期间','实物吨','记录数'],...s.buckets.map(b=>[b.key,b.value,b.rows.length])],'出口走势图.csv')});ixDraw(id)})}
exMonthChart=function(rows){return ixTradeChart(rows)};
const ixOldExportsRows=exportsRows;exportsRows=function(...args){ixOldExportsRows(...args);ixMount()};
const ixOldNpiRows=npiTradeRows;npiTradeRows=function(...args){ixOldNpiRows(...args);let rs=ntRowsCurrent.map(r=>({id:r.id,date:r['日期'],month:r['月份'],exporter:r['出口商(标准化)'],buyer:r['买家'],customer:U().customers.find(c=>c.name===r.buyer_norm)?.id,product:'npi',tonnes:r['重量(吨)'],counted:r['重量(吨)']}));$('ntChart').innerHTML=ixTradeChart(rs,'镍铁出口走势');ixMount()};
const ixOldMhRows=mhTradeRows;mhTradeRows=function(...args){ixOldMhRows(...args);let node=document.querySelector('.mh-months'),rs=mhTradeFiltered().map(r=>({id:r.id,date:r['日期'],month:r['月份'],project:mhP(r.project_id)?.canonical_id,exporter:r['出口商(标准化)'],buyer:r['买家'],customer:MH().trade.buyers.find(b=>b.id===r.buyer_id)?.canonical_id,product:'mhp',tonnes:r['重量(吨)'],counted:r['重量(吨)']}));if(node)node.outerHTML=ixTradeChart(rs,'MHP出口走势');ixMount();ixHorizontal()};
function ixHorizontal(){document.querySelectorAll('.hbar').forEach(el=>{if(el.dataset.interactive)return;el.dataset.interactive='yes';let link=el.querySelector('a'),bar=el.querySelector(':scope > span');if(!bar)return;bar.tabIndex=0;bar.setAttribute('role',link?'link':'button');bar.setAttribute('aria-label',el.innerText.trim());let show=()=>ixTooltip(el.innerText.trim(),bar);bar.onpointerenter=show;bar.onpointerleave=ixHideTip;bar.onfocus=show;bar.onblur=ixHideTip;bar.onclick=()=>{ixHideTip();if(link)link.click();else{let p=el.querySelector('.ix-bar-note');if(!p){p=document.createElement('p');p.className='ix-bar-note';p.textContent=el.innerText.trim();el.appendChild(p)}else p.hidden=!p.hidden}};bar.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();bar.click()}}});document.querySelectorAll('.npi-bar').forEach((el,i)=>{if(el.dataset.interactive)return;el.dataset.interactive='yes';el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label','筛选地区：'+NPI.regions[i].region);el.onclick=()=>{$('npiRegion').value=NPI.regions[i].region;npiRows();$('npi-directory').scrollIntoView({behavior:'smooth'})};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}};el.onpointerenter=()=>ixTooltip(el.innerText.replace(/\n/g,' · '),el);el.onpointerleave=ixHideTip})}
const ixOldBuyerGraph=drawBuyerGraph;drawBuyerGraph=function(){ixOldBuyerGraph();ixHorizontal()};

// A shared chronology is used in every project article and in the industry view.
const HX=()=>window.HISTORY||{projects:{},events:CL().events};
function hxSort(e){let m=String(e.date).match(/(19\d{2}|20\d{2})(?:[-年.](\d{1,2}))?/),q=String(e.date).match(/Q([1-4])/i);return m?Number(m[1])*10000+(q?(Number(q[1])-1)*3+1:Number(m[2]||1))*100+Number(String(e.date).match(/^\d{4}-\d{2}-(\d{2})/)?.[1]||1):99999999}
function hxEvents(id){return HX().events.filter(e=>e.project_id===id).sort((a,b)=>hxSort(a)-hxSort(b))}
function hxEvent(e,withProject=false){return `<div class="event" data-event-kind="${E(e.kind||'历史')}"><div class="date">${E(e.date)} <span class="hx-kind">${E(e.kind||'历史')}</span></div><h3>${E(e.label)}</h3>${withProject?A('project',e.project_id,U().projects.find(p=>p.id===e.project_id)?.name||e.project_id):''}<p>${E(e.detail)}</p>${e.source_url?`<a class="small-link" href="${E(e.source_url)}" target="_blank" rel="noopener">${E(e.source_title||'原始资料')} ↗</a>`:e.source_note?`<p class="meta">资料：${E(e.source_note)}</p>`:''}</div>`}
function hxProject(id){let events=hxEvents(id),coverage=HX().projects[id]||{},kinds=[...new Set(events.map(e=>e.kind||'历史'))];return `<section id="wiki-history" class="hx-project" data-project="${id}"><h2>建设与运营时间线</h2><p class="meta">建设、首产、商业生产和扩产分别记录；点击类型可只看对应事件。</p>${events.length?`<div class="hx-chips" role="group" aria-label="项目历史事件类型"><button data-kind="" class="active" aria-pressed="true">全部 ${events.length}</button>${kinds.map(k=>`<button data-kind="${E(k)}" aria-pressed="false">${E(k)}</button>`).join('')}<button data-order="desc" aria-pressed="false">最新在前</button></div><div class="timeline">${events.map(e=>hxEvent(e)).join('')}</div>`:'<p>本条目的项目沿革见正文，具体建设与投产日期仍在补充。</p>'}<div class="actions"><a href="#/timeline/${id}">放入产业时间线对照 →</a></div>${coverage.coverage_note?`<details class="reading-notes"><summary>需要再确认</summary><p>${E(coverage.coverage_note)}</p></details>`:''}</section>`}
const hxOldWiki=wikiArticle;wikiArticle=function(id){let html=hxOldWiki(id);return html.replace('<a href="#" data-scroll="wiki-trade">','<a href="#" data-scroll="wiki-history">建设与运营时间线</a><a href="#" data-scroll="wiki-trade">').replace('<section id="wiki-trade">',hxProject(id)+'<section id="wiki-trade">')};
timeline=function(){let initial=location.hash.split('/')[2]||'';return `<div class="kicker">产业历史 / 项目沿革</div><h1>建设、投产与产业变化</h1><p class="lead">从项目起点读到投产、扩建与产品转换。按工厂、园区和事件类型筛选，也可以点击年份查看当年的变化。</p><div class="filters hx-filters"><select id="eventProject" aria-label="筛选事件项目"><option value="">全部项目</option>${U().projects.map(p=>`<option value="${p.id}" ${p.id===initial?'selected':''}>${E(p.name)}</option>`).join('')}</select><select id="eventProduct" aria-label="筛选事件产品"><option value="">全部产品</option><option value="npi">镍铁</option><option value="matte">低冰镍／高冰镍</option><option value="mhp">MHP</option><option value="sulfate">硫酸镍</option><option value="refined">精炼镍</option></select><select id="eventPark" aria-label="筛选事件园区"><option value="">全部园区与地区</option>${G().places.map(p=>`<option value="${p.id}" ${initial==='park:'+p.id?'selected':''}>${E(p.name)}</option>`).join('')}</select><select id="eventKind" aria-label="事件类型"><option value="">全部事件类型</option>${[...new Set(HX().events.map(e=>e.kind||'历史'))].sort().map(k=>`<option>${E(k)}</option>`).join('')}</select><input id="eventQ" aria-label="搜索历史事件" placeholder="查投产、扩产、合同或公司"><select id="eventYear" aria-label="事件年份"><option value="">全部年份</option>${[...new Set(HX().events.map(e=>String(e.date).match(/(?:19|20)\d{2}/)?.[0]).filter(Boolean))].sort().map(y=>`<option>${y}</option>`).join('')}</select><select id="eventOrder" aria-label="事件排序"><option value="asc">从早到晚</option><option value="desc">最新在前</option></select><button id="eventReset">清除筛选</button><button id="eventDownload">下载筛选事件</button></div><div class="ix-plot hx-year-chart" id="eventChart"></div><p class="meta">柱高是已收录事件数；点击年份筛选。它不代表该年的新增产能或全部投产项目数。规划日期按事件文字所述阅读。</p><div id="events"></div>`};
let hxCurrent=[];
drawEvents=function(){let id=$('eventProject').value,k=$('eventProduct').value,q=$('eventQ').value.toLowerCase(),park=$('eventPark').value,kind=$('eventKind').value,year=$('eventYear').value;let base=HX().events.filter(e=>{let p=U().projects.find(p=>p.id===e.project_id);return (!id||e.project_id===id)&&(!k||geoScope(p,k))&&(!park||geoLoc(p?.id)?.place_id===park)&&(!kind||(e.kind||'历史')===kind)&&(!q||(JSON.stringify(e)+(p?.name||'')).toLowerCase().includes(q))}),ys={};for(let e of base){let y=String(e.date).match(/(?:19|20)\d{2}/)?.[0];if(y)(ys[y]??={key:y,value:0}).value++}let bars=Object.values(ys).sort((a,b)=>a.key.localeCompare(b.key));$('eventChart').innerHTML=bars.length?ixSvg(bars,{selected:year,unit:'项事件'}):'';ixMarkEvents($('eventChart'),bars,b=>{$('eventYear').value=year===b.key?'':b.key;drawEvents()},'项事件');let arr=base.filter(e=>!year||String(e.date).match(/(?:19|20)\d{2}/)?.[0]===year).sort((a,b)=>(hxSort(a)-hxSort(b))*($('eventOrder').value==='desc'?-1:1));hxCurrent=arr;let p=HX().projects[id];$('events').innerHTML=`<p class="result-count">${arr.length}项事件 · ${new Set(arr.map(e=>e.project_id)).size}个项目</p>${arr.length?`<div class="timeline">${arr.map(e=>hxEvent(e,true)).join('')}</div>`:'<p class="empty">当前筛选没有日期事件，可调整条件或回到项目正文阅读。</p>'}${id?A('project',id,'阅读项目完整百科 →'):''}${id&&p?.coverage_note?`<details class="reading-notes"><summary>需要再确认</summary><p>${E(p.coverage_note)}</p></details>`:''}`};
function hxBind(){if($('eventPark')){for(let id of ['eventPark','eventKind','eventYear','eventOrder'])$(id).onchange=drawEvents;$('eventReset').onclick=()=>{for(let id of ['eventProject','eventProduct','eventPark','eventKind','eventQ','eventYear'])$(id).value='';$('eventOrder').value='asc';drawEvents()};$('eventDownload').onclick=()=>ixDownload([['项目','时间','类型','事件','说明','来源'],...hxCurrent.map(e=>[U().projects.find(p=>p.id===e.project_id)?.name,e.date,e.kind,e.label,e.detail,e.source_url])],'项目历史事件.csv')};document.querySelectorAll('.hx-project').forEach(el=>{let id=el.dataset.project,kind='',desc=false;let draw=()=>{let arr=hxEvents(id).filter(e=>!kind||(e.kind||'历史')===kind);if(desc)arr.reverse();el.querySelector('.timeline').innerHTML=arr.map(e=>hxEvent(e)).join('')};el.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;el.querySelectorAll('[data-kind]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});draw()});let order=el.querySelector('[data-order]');if(order)order.onclick=()=>{desc=!desc;order.textContent=desc?'最早在前':'最新在前';order.setAttribute('aria-pressed',String(desc));draw()}})}
function ixProduction(){let id=route?.[0]==='project'?route[1]:null,p=id&&CL().production?.[id];if(!p)return;let section=[...document.querySelectorAll('.wiki-prose section')].find(el=>el.querySelector('h2')?.textContent===p.title);if(!section||section.querySelector('.ix-production'))return;let box=document.createElement('div');box.className='ix-chart ix-production';box.innerHTML='<div class="ix-heading"><h4>生产、销售与产能对照</h4><span>实物吨</span></div><div class="ix-controls"><label>查看指标<select aria-label="产销图表指标"><option value="plant_output">自产产量</option><option value="reported_output">产销表产量（含当年委外）</option><option value="sales">销量</option><option value="capacity">产能表口径</option></select></label></div><div class="ix-plot"></div><p class="ix-hint">点击年份查看各项数值。产能、产量与销量分开比较。</p><div class="ix-selection" aria-live="polite"></div>';section.querySelector('.table-wrap').before(box);let metric=box.querySelector('select'),selected=null;function draw(){let a=p.rows.map(r=>({key:String(r.year),value:r[metric.value],row:r})),plot=box.querySelector('.ix-plot');plot.innerHTML=ixSvg(a,{selected});ixMarkEvents(plot,a,b=>{selected=b.key;let r=b.row;box.querySelector('.ix-selection').innerHTML=`<h4>${r.year}年</h4><p>自产产量 ${F(r.plant_output)} · 产销表产量 ${F(r.reported_output)} · 销量 ${F(r.sales)} · 产能表口径 ${F(r.capacity)} 实物吨</p>${r.year===2023?'<p>2023年产销表产量包含24,400吨委外加工。该年产能按投运月份加权。</p>':''}`;draw()})}metric.onchange=draw;draw()}
function ixBind(){ixMount();ixHorizontal();hxBind();ixProduction();for(let id of IX.keys())if(!$(id))IX.delete(id)}
function hxMilestones(id){let es=hxEvents(id),build=es.find(e=>e.kind==='建设'&&/开工|奠基/.test(e.label)),first=es.find(e=>['投产','首产','试产'].includes(e.kind)&&/首|投产|生产|运营/.test(e.label));return [build,first].filter(Boolean).map(e=>`${E(e.date)} · ${E(e.label)}`).join('<br>')}
const hxOldGeoTable=geoTable;geoTable=function(ps){return hxOldGeoTable(ps).replace('<th>出口记录</th>','<th>出口记录</th><th>建设与投产</th>').replace(/<tr>([\s\S]*?)<\/tr>/g,(all,body)=>{let id=body.match(/href="#\/project\/([^"]+)"/)?.[1];return id?`<tr>${body}<td>${hxMilestones(id)}<span class="sub"><a href="#/timeline/${id}">项目时间线（${hxEvents(id).length}）→</a></span></td></tr>`:all})};
const hxOldGeoArticle=geoArticle;geoArticle=function(id,island=false){let html=hxOldGeoArticle(id,island);return island?html:html.replace('<a href="#" data-scroll="geo-companies">',`<a href="#/timeline/park:${id}">园区项目时间线 →</a><a href="#" data-scroll="geo-companies">`)};
