const MH=()=>window.MHP;
const mhTxt=x=>Array.isArray(x)?x.join('；'):x??'';
const mhP=id=>MH().projects.find(p=>p.id===id);
const mhLink=p=>A('project',p.canonical_id,p.name);
function mhSources(ids){return `<div class="mhp-sources">${[...new Set(ids)].map(id=>{let s=MH().sources.find(s=>s.id===id);return s?`<div class="source-entry"><h3>${A('mhp-source',id,s.title)}</h3><p>${E(s.date||'日期见原文')} · ${E(s.evidence||'')}</p><a target="_blank" rel="noopener" href="${E(s.url)}">原始披露 ↗</a></div>`:''}).join('')}</div>`}
function mhSections(p){let view=readingMhpView(p);return [['ownership','股东与控制关系'],['history','为什么建、什么时候建'],['capacity','产能规模'],['status','建设与运营'],['process','生产工艺与设备'],['ore','矿源与原料供应'],['customers','卖给谁、合同与加工用途'],['rationale','商业逻辑与产业链关系'],['uncertainties','还需要确认什么']].map(([k,t])=>`<section><h3>${t}</h3>${String(view[k]||'本轮未取得可核资料').split('\n\n').map(s=>`<p>${E(s)}</p>`).join('')}</section>`).join('')}
function mhHome(){let t=MH().trade.summary;return `<div class="kicker">MHP · MSP · 电池盐 / 2026.09.17</div><h1>MHP产业研究</h1><p class="lead">项目、股东、设备与买方，放回同一条产业链里看。</p><div class="actions"><a href="#/mhp-trade">查看逐票与流向 →</a><a href="library/mhp-audit.xlsx" download>下载更新核查表 ↓</a><a href="library/mhp-report.html" target="_blank">完整研究报告 ↗</a><a href="#/groups">统一母公司库 →</a></div><div class="stat-row"><div><strong>47 + 1</strong><span>原表项目/分期 + 补充出口主体</span></div><div><strong>${t.exporters} / ${t.buyers}</strong><span>出口抬头 / 原始买方抬头</span></div><div><strong>${t.records.toLocaleString()}</strong><span>用户MHP样本记录</span></div><div><strong>${MH().sources.length}</strong><span>本轮去重来源</span></div></div><div class="flowrow"><div class="flow-node">褐铁矿等原料</div><span class="arrow">→</span><div class="flow-node">HPAL／STAL／堆浸<br>浸出、净化与沉淀</div><span class="arrow">→</span><div class="flow-node">MHP / MSP<br>两种中间品分开</div><span class="arrow">→</span><div class="flow-node">镍钴盐／精炼金属<br>集团自供、承购与外售</div></div><p class="meta">流程为机制示意，不表示每个项目都具备所有工序。海外项目与下游精炼厂不计为印尼现役MHP能力。</p><div class="filters"><input id="mhQ" placeholder="查项目、股东、产能、矿源或合同" aria-label="搜索MHP项目"><select id="mhCountry" aria-label="筛选地区"><option value="">全部地区</option><option value="印尼">印尼</option><option value="overseas">非印尼</option></select></div><div id="mhResults"></div><h2>产业链如何运作</h2>${MH().sections.map((s,i)=>[0,2,4].includes(i)?`<section><h3>${E(s.title)}</h3>${s.paragraphs.map(p=>`<p>${E(p)}</p>`).join('')}</section>`:`<details class="contract"><summary>${E(s.title)}</summary>${s.paragraphs.map(p=>`<p>${E(p)}</p>`).join('')}</details>`).join('')}<h2>证据与待核</h2><p>研究条目全覆盖不等于每个结论都已闭合。每厂保留股权、产品、能力、合同和现况的独立缺口。</p><div class="actions"><a href="#/mhp-sources">检索本轮来源 →</a><a href="library/mhp-library.json" download>下载完整MHP资料库 ↓</a></div>`}
function mhRows(){let q=$('mhQ').value.toLowerCase(),country=$('mhCountry').value,a=MH().projects.filter(p=>(!country||(country==='overseas'?p.country!=='印尼':p.country===country))&&JSON.stringify(p).toLowerCase().includes(q));$('mhResults').innerHTML=`<p class="meta">${a.length} 条项目/分期；同一主体的分期会进入同一档案，不重复合计出口。</p><div class="table-wrap"><table><thead><tr><th>项目／分期</th><th>地区与角色</th><th>投产与运行状态</th><th>产能口径</th><th>现况与股权</th></tr></thead><tbody>${a.map(p=>`<tr><td>${mhLink(p)}<span class="meta">${E(p.legal||'法律主体待核')}</span></td><td>${E(p.country)} · ${E(p.region)}<p>${E(p.classification)}</p></td><td>${opCell(p.canonical_id)}</td><td>${E(p.capacity)}</td><td>${E(p.status)}<details><summary>股东</summary><p>${E(p.ownership)}</p></details></td></tr>`).join('')}</tbody></table></div>`}
function mhBar(items){let max=Math.max(...items.map(x=>x.value),1);return `<div class="hbars">${items.map(x=>`<div class="hbar"><div>${x.link||E(x.name)}<strong>${F(x.value)} 实物吨</strong></div><span style="width:${Math.max(0,x.value/max*100)}%"></span></div>`).join('')}</div>`}
function mhExporter(p){let t=MH().trade,e=t.exporters.find(x=>x.project_id===p.trade_project_id);if(!e)return `<p>现有印尼MHP样本未匹配该项目。海外项目不在本样本覆盖范围；没有记录不等于没有生产。</p>`;let es=t.edges.filter(x=>x.project_id===e.project_id).sort((a,b)=>b.tonnes-a.tonnes);return `<p>${E(e.first)}—${E(e.last)} · ${e.records} 条 · ${F(e.tonnes)} 实物吨。${E(p.trade_note)}</p><p><a href="#/mhp-trade/${e.project_id}">筛选该主体全部原记录 →</a></p>${mhBar(es.slice(0,10).map(e=>{let b=t.buyers.find(b=>b.id===e.buyer_id);return {name:e.buyer,value:e.tonnes,link:A('customer',b.canonical_id,b.name)}}))}<details><summary>全部 ${es.length} 个买方与期间</summary>${es.map(e=>{let b=t.buyers.find(b=>b.id===e.buyer_id);return `<p>${A('customer',b.canonical_id,b.name)}：${F(e.tonnes)} 实物吨，${e.records} 条，${e.first}—${e.last}。</p>`}).join('')}</details>`}
function mhProjectChapter(ids){let a=ids.map(mhP).filter(Boolean);return `<section id="umhp" class="unified-chapter"><div class="kicker">MHP／MSP与下游研究</div>${a.map(p=>`<section><h2>${E(p.name)}</h2><p class="legal">${E(p.legal||'法律主体待核')} · ${E(p.country)}</p><p class="lead">${E(readingIntro(p)||p.classification)}</p>${mhSections(p)}${mhProduction(p.row)}<details><summary>原表对照</summary><p>原表行：${p.row||'补充主体'}；产能原值：${E(p.original.G??'未填')}（原列未明示单位）；日期：${E(p.original.E??'未填')}。</p><p>股权原文：${E(p.original.K??'未填')}</p><p>运行原文：${E(p.original.O??'未填')}</p></details><h3>出口与客户</h3>${mhExporter(p)}<details><summary>原始资料与支持范围</summary>${mhSources(p.source_ids)}</details></section>`).join('')}</section>`}
function mhTopic(t){return `<section><h3>${E(t.name)}</h3><p class="meta">${E(t.group||'')}</p>${['intro','purpose','contracts'].map(k=>`<p>${E(mhTxt(t[k]))}</p>`).join('')}${readingFold(`<p>${E(mhTxt(t.unknowns))}</p>`)}<details><summary>原文证据</summary>${mhSources(t.source_ids)}</details></section>`}
function mhCustomerChapter(ids){let bs=MH().trade.buyers.filter(b=>ids.includes(b.id)),topics=MH().customer_topics.filter(t=>bs.some(b=>b.topic_ids.includes(t.id)));return `<section id="ucmhp"><h2>MHP采购与实际供货方</h2>${topics.length?topics.map(mhTopic).join(''):'<div class="note neutral">该买方已建立贸易档案，但本轮未独立查实其股权、实际加工厂和长期承购合同。旧镍铁/冰镍业务资料如有列在同页，不能直接证明MHP用途。</div>'}${bs.map(b=>`<h3>${E(b.name)}</h3><p>${b.records}条 · ${F(b.tonnes)} 实物吨 · ${b.first}—${b.last}</p>${MH().trade.edges.filter(e=>e.buyer_id===b.id).map(e=>{let p=mhP(e.project_id);return `<div class="panel"><h3>${mhLink(p)}</h3><p>${F(e.tonnes)} 实物吨 · ${e.records}条 · ${e.first}—${e.last}</p><p>${E(p.customers)}</p></div>`}).join('')}`).join('')}<p class="meta">同名或标点归一连接仅用于共页阅读，保留原始抬头；交易量不证明终端投料量。</p></section>`}
let mhPage=1;
function mhTradeHome(id){let t=MH().trade;window.mhInitial=id||'';return `<div class="kicker">用户出口样本 / MHP</div><h1>谁在发货，货到了谁的抬头</h1><p class="lead">${t.summary.first}—${t.summary.last} · 2,283条 · 212组供销关系。重量为样本实物吨。</p><div class="actions"><a href="#/mhp">MHP项目与报告 →</a><a href="library/mhp-audit.xlsx" download>下载完整核查与贸易表 ↓</a><button id="mhDownload">下载筛选记录</button></div><div class="filters"><select id="mtProject" aria-label="筛选MHP出口厂"><option value="">全部出口主体</option>${t.exporters.map(e=>`<option value="${e.project_id}" ${e.project_id===id?'selected':''}>${E(e.name)}</option>`).join('')}</select><input id="mtQ" placeholder="查买方、月份、品名、原行号" aria-label="搜索MHP逐票"><input id="mtFrom" type="month" aria-label="开始月份"><input id="mtTo" type="month" aria-label="结束月份"></div><div id="mtResults"></div><section class="reading-information"><h2>资料说明</h2>${MH().trade.notes.filter(n=>!readingAudit.test(n)).map(n=>`<p>${E(n)}</p>`).join('')}</section>${readingFold(MH().trade.notes.filter(n=>readingAudit.test(n)).map(n=>`<p>${E(n)}</p>`).join(''))}`}
function mhTradeFiltered(){return MH().trade.records.filter(r=>(!$('mtProject').value||r.project_id===$('mtProject').value)&&(!$('mtFrom').value||r['月份']>=$('mtFrom').value)&&(!$('mtTo').value||r['月份']<=$('mtTo').value)&&JSON.stringify(r).toLowerCase().includes($('mtQ').value.toLowerCase()))}
function mhTradeRows(){let rs=mhTradeFiltered(),total=rs.reduce((s,r)=>s+(r['重量(吨)']||0),0),byMonth={},byBuyer={};rs.forEach(r=>{byMonth[r['月份']]=(byMonth[r['月份']]||0)+r['重量(吨)'];byBuyer[r.buyer_id]=(byBuyer[r.buyer_id]||0)+r['重量(吨)']});let max=Math.max(...Object.values(byMonth),1),pages=Math.max(1,Math.ceil(rs.length/50));mhPage=Math.min(mhPage,pages);let page=rs.slice((mhPage-1)*50,mhPage*50);$('mtResults').innerHTML=`<div class="stat-row"><div><strong>${rs.length.toLocaleString()}</strong><span>筛选记录</span></div><div><strong>${F(total)}</strong><span>实物吨</span></div><div><strong>${Object.keys(byBuyer).length}</strong><span>原始买方抬头</span></div></div><h2>逐月出口</h2><div class="mh-months" role="img" aria-label="月度实物出口柱状图；每根柱含月份与吨数提示">${Object.entries(byMonth).sort().map(([m,v])=>`<div class="mh-month" tabindex="0" title="${m}：${F(v)}实物吨"><span style="height:${Math.max(2,v/max*150)}px"></span><small>${m.slice(2)}</small><b>${F(v)}</b></div>`).join('')}</div><details><summary>查看月度数值表</summary>${Object.entries(byMonth).sort().map(([m,v])=>`<p>${m}：${F(v)} 实物吨</p>`).join('')}</details><h2>主要买方渠道</h2>${mhBar(Object.entries(byBuyer).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,v])=>{let b=MH().trade.buyers.find(b=>b.id===id);return {value:v,name:b.name,link:A('customer',b.canonical_id,b.name)}}))}<h2>逐条记录</h2><div class="actions"><button id="mtPrev" ${mhPage===1?'disabled':''}>上一页</button><span>第 ${mhPage} / ${pages} 页 · 每页50条</span><button id="mtNext" ${mhPage===pages?'disabled':''}>下一页</button></div><div class="table-wrap"><table><thead><tr><th>日期／原表行</th><th>出口商 → 买方</th><th>重量与金额</th><th>货描与品位证据</th></tr></thead><tbody>${page.map(r=>{let b=MH().trade.buyers.find(b=>b.id===r.buyer_id);return `<tr><td>${r['日期']}<span class="meta">原行 ${r.source_row} · ${r.id}</span></td><td>${mhLink(mhP(r.project_id))}<p>→ ${A('customer',b.canonical_id,r['买家'])}</p><span class="meta">${E(r['目的国'])} / ${E(r['到货港'])}</span></td><td>${F(r['重量(吨)'])} 实物吨<p>USD ${F(r['金额USD'])}</p></td><td>${E(r['品名'])}${readingFold(`<p>${E(r.grade_basis)}</p><p>来源品位标记：${E(r['品位来源'])}</p>`,'品位与重量说明')}</td></tr>`}).join('')}</tbody></table></div>`;$('mtPrev').onclick=()=>{mhPage=Math.max(1,mhPage-1);mhTradeRows()};$('mtNext').onclick=()=>{mhPage=Math.min(pages,mhPage+1);mhTradeRows()}}
function mhDownload(){let rs=mhTradeFiltered(),ks=['source_row','日期','月份','出口商(标准化)','买家','目的国','重量(吨)','金额USD','品名','Ni%原文','品位来源','grade_basis'];let csv='\uFEFF'+[ks,...rs.map(r=>ks.map(k=>r[k]))].map(a=>a.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');let u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='MHP筛选记录.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function mhSourcesHome(){return `<div class="kicker">MHP / 原始证据</div><h1>MHP研究来源</h1><div class="filters"><input id="mhSourceQ" placeholder="查公司、年报、工艺、合同" aria-label="查MHP来源"></div><div id="mhSourceResults"></div>`}
function mhSourceRows(){$('mhSourceResults').innerHTML=mhSources(MH().sources.filter(s=>JSON.stringify(s).toLowerCase().includes($('mhSourceQ').value.toLowerCase())).map(s=>s.id))}
function mhSource(id){let s=MH().sources.find(s=>s.id===id);return s?`<h1>${E(s.title)}</h1>${mhSources([id])}<h2>引用项目</h2>${s.projects.map(mhP).filter(Boolean).map(p=>`<p>${mhLink(p)}</p>`).join('')}`:missing()}
function mhRoute(k,id){return k==='mhp'?mhHome():k==='mhp-trade'?mhTradeHome(id):k==='mhp-sources'?mhSourcesHome():k==='mhp-source'?mhSource(id):null}
function mhBind(k){if(k==='mhp'){mhRows();$('mhQ').oninput=mhRows;$('mhCountry').onchange=mhRows}if(k==='mhp-trade'){mhPage=1;['mtProject','mtQ','mtFrom','mtTo'].forEach(id=>$(id).oninput=()=>{mhPage=1;mhTradeRows()});mhTradeRows();$('mhDownload').onclick=mhDownload}if(k==='mhp-sources'){mhSourceRows();$('mhSourceQ').oninput=mhSourceRows}}
// Extend the existing shared directories and profiles, preserving prior NPI/matte content.
const mhOldProject=uProject;uProject=function(id){let p=U().projects.find(x=>x.id===id);if(!p)return missing();return mhOldProject(id)+(p.mhp_ids?.length?mhProjectChapter(p.mhp_ids):'')};
const mhOldCustomer=uCustomer;uCustomer=function(id){let c=U().customers.find(x=>x.id===id);return mhOldCustomer(id)+(c?.mhp_ids?.length?mhCustomerChapter(c.mhp_ids):'')};
const mhOldProducts=uProducts;uProducts=function(p){return [mhOldProducts(p),p.mhp_ids?.length?'MHP／MSP及下游研究':''].filter(Boolean).join(' · ')};
const mhOldGroup=uGroup;uGroup=function(id){let c=U().companies.find(x=>x.id===id),a=(c?.mhp_ids||[]).map(mhP).filter(Boolean);return mhOldGroup(id)+(a.length?`<section class="unified-chapter"><h2>MHP投资、供矿与承购布局</h2><p>下列包括当前股权、历史参与和待核合作，不表示全部为该集团控制。比例与日期逐项目阅读。</p>${a.map(p=>`<section><h3>${mhLink(p)}</h3><p>${E(p.ownership)}</p><p>${E(p.rationale)}</p><p>${E(p.customers)}</p><details><summary>股权与供销依据</summary>${mhSources(p.source_ids)}</details></section>`).join('')}</section>`:'')};
const mhOldDirectory=uDirectory;uDirectory=function(k){return mhOldDirectory(k).replace('全部产品资料</option>','全部产品资料</option><option value="mhp">含MHP／MSP及下游资料</option>').replace('镍铁、低冰镍、高冰镍及转产历史','镍铁、低冰镍、高冰镍、MHP及转产历史').replace('镍铁和冰镍采购','镍铁、冰镍和MHP采购')+`<div class="actions"><a href="#/mhp">MHP完整研究 →</a><a href="#/mhp-trade">MHP逐票 →</a></div>`};
uRows=function(kind){let q=$('uQ').value.toLowerCase(),scope=$('uScope').value,arr=kind==='projects'?U().projects:kind==='groups'?U().companies:U().customers;arr=arr.filter(x=>{let n=!!x.npi_id,m=!!(x.matte_id||x.matte_ids?.length),h=!!x.mhp_ids?.length;return (!scope||scope==='both'&&n&&m||scope==='npi'&&n||scope==='matte'&&m||scope==='mhp'&&h||['sulfate','refined'].includes(scope)&&x.refining_products?.includes(scope))&&JSON.stringify(x).toLowerCase().includes(q)});$('uResults').innerHTML=`<p class="meta">${arr.length}项 · 股权/历史/合作关系以正文为准</p>`+`<div class="table-wrap"><table><thead><tr><th>名称</th><th>资料范围</th><th>简介与股权</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${A(kind==='projects'?'project':kind==='groups'?'group':'customer',x.id,x.name)}<p>${E(x.region||'')}</p></td><td>${x.npi_id?'镍铁／NPI<br>':''}${x.matte_id||x.matte_ids?.length?'低冰镍／高冰镍<br>':''}${x.mhp_ids?.length?'MHP／MSP及下游<br>':''}${(x.refining_products||[]).map(rfName).join(' · ')}</td><td>${E(kind==='projects'?x.ownership:x.intro)}</td></tr>`).join('')}</tbody></table></div>`};
const mhOldResearch=researchHome;researchHome=function(){return `<div class="note neutral"><h2>MHP全表研究已接入</h2><p>47条原表项目/分期及1个补充出口主体，各自保留明确待核事项。项目与母公司已接入统一目录。</p><a href="#/mhp">查看研究与逐厂缺口 →</a></div>`+mhOldResearch()};
const mhOldSources=sources;sources=function(){return `<div class="note neutral"><a href="#/mhp-sources">MHP：${MH().sources.length}项新增研究来源 →</a></div>`+mhOldSources()};
const mhOldAbout=about;about=function(){return `<div class="note neutral"><h2>统一资料库当前范围</h2><p>${U().summary.projects}个项目研究对象、${U().summary.companies}个集团/投资体系、${U().summary.customers}个买方目录条目。MHP新增47条原表项目/分期与1个补充主体；海外和下游项目独立分类。以下V19数量为旧冰镍底稿范围，非当前全库合计。</p><a href="#/mhp">MHP口径与资料 →</a></div>`+mhOldAbout()};

function mhProduction(row){let a=MH().production_facts.filter(x=>x.project_row===row);return a.length?`<h3>官方产销与运行指标</h3><p class="meta">权益数与全项目换算不重复累计；镍金属吨、矿石湿吨和MHP实物吨分开阅读。</p><div class="table-wrap"><table><thead><tr><th>期间与指标</th><th>值与单位</th><th>口径与证据</th></tr></thead><tbody>${a.map(x=>`<tr><td>${E(x.period)}<p>${E(x.metric)}</p></td><td>${E(x.value)} ${E(x.unit)}</td><td>${E(x.scope)}<p>${E(x.evidence)}</p>${x.url.split(' ; ').map(u=>`<a href="${E(u.trim())}" target="_blank">官方原件 ↗</a>`).join(' ')}</td></tr>`).join('')}</tbody></table></div>`:''}
const mhOldGraph=graph;graph=function(){return `<div class="note neutral"><h2>MHP：从矿源到买方</h2><div class="flowrow"><div class="flow-node">褐铁矿等矿源</div><span class="arrow">→</span><div class="flow-node">浸出与沉淀<br>MHP / MSP</div><span class="arrow">→</span><div class="flow-node">承购／贸易平台</div><span class="arrow">→</span><div class="flow-node">镍钴盐／精炼金属</div></div><p>机制示意，具体终端以逐厂证据为准。11个出口抬头、127个原始买方抬头、212组可见关系可筛选查看。</p><a href="#/mhp-trade">查看MHP实际供销关系与数量 →</a></div>`+mhOldGraph()};
const mhOldTimeline=timeline;timeline=function(){return `<details><summary>MHP建设与投产历史：展开全部项目</summary>${MH().projects.map(p=>`<section><h3>${mhLink(p)}</h3><p>${E(p.history)}</p><p>${E(p.status)}</p></section>`).join('')}</details>`+mhOldTimeline()};
const mhOldTopics=directory;directory=function(type){return (type==='topic'? `<div class="note neutral"><h2><a href="#/mhp">MHP、MSP与电池盐</a></h2><p>分清HPAL、分段温度酸浸、堆浸，以及混合氢氧化物和混合硫化物的工艺、产品与计量差异。</p></div>`:'')+mhOldTopics(type)};
