// Product chapters connect existing company, history and audited trade records.
const PC_META=[
 {id:'npi',topic:'npi',name:'镍生铁与镍铁',en:'NPI & FERRONICKEL',scope:'npi',trade:'npi',contracts:['C02','C07','C08'],cases:['NPI009','NPI020','NPI051']},
 {id:'low-matte',topic:'low-matte',name:'低冰镍',en:'LOW-GRADE NICKEL MATTE',scope:'matte',trade:'low',contracts:['C04','C07','C08','C10','C11'],cases:['NPI008','NPI020','P48'],matte:['P02','P03','P06','P09','P12','P14','P16','P17','P18','P19','P21','P22','P25','P26','P27','P28','P29','P30','P31','P32','P33','P34','P42','P43','P48']},
 {id:'high-matte',topic:'high-matte',name:'高冰镍',en:'HIGH-GRADE NICKEL MATTE',scope:'matte',trade:'high',contracts:['C01','C03','C04','C06','C07','C08','C09','C11'],cases:['P12','P01','NPI004'],matte:['P01','P02','P03','P04','P05','P06','P07','P08','P09','P10','P11','P12','P14','P16','P17','P18','P19','P21','P22','P25','P26','P27','P28','P29','P30','P31','P32','P33','P34','P38','P39','P40','P41','P42','P43','P44']},
 {id:'mhp',topic:'mhp',name:'MHP镍钴混合氢氧化物',en:'MIXED HYDROXIDE PRECIPITATE',scope:'mhp',trade:'mhp',contracts:[],cases:['MHP006','MHP003','MHP011']},
 {id:'sulfate',topic:'nickel-sulphate',name:'硫酸镍',en:'NICKEL SULPHATE',scope:'sulfate',trade:'sulfate',contracts:['C05'],cases:['MHP003','RF003','MHP011']},
 {id:'refined',topic:'refined-nickel',name:'精炼镍',en:'REFINED NICKEL',scope:'refined',trade:'refined',contracts:[],cases:['RF001','RF002','MHP017']}
];
const pcMeta=id=>PC_META.find(p=>p.id===id||p.topic===id);
const pcId=id=>U().project_matte_map[id]||id;
const pcIndonesian=p=>geoLoc(p.id)?.island_id!=='overseas';
function pcRows(m){return EXPORTS.records.filter(r=>r.product===m.trade)}
function pcProjects(m){const shipped=new Set(pcRows(m).map(r=>r.project)),matte=new Set((m.matte||[]).map(pcId));return U().projects.filter(p=>pcIndonesian(p)&&(m.matte?matte.has(p.id)||shipped.has(p.id):geoScope(p,m.scope)||shipped.has(p.id)))}
function pcRefs(ss=[]){return `<div class="pc-refs">${ss.map(s=>`<a href="${E(s.url)}" target="_blank" rel="noopener">${E(s.title)} ↗</a>`).join('')}</div>`}
function pcProse(m){let d=window.PRODUCT_CHAPTERS?.[m.id];return (d?.sections||[]).map(s=>`<section class="pc-prose-section"><h3>${E(s.title)}</h3>${s.paragraphs.map(p=>`<p>${E(p)}</p>`).join('')}${pcRefs(s.sources)}</section>`).join('')}
function pcRole(m,p){if(m.matte){let ms=p.matte_ids.map(P).filter(Boolean);return ms.map(x=>x.products[m.id]).filter(Boolean).join('；')||(pcRows(m).some(r=>r.project===p.id)?'匹配到该品目出口；制造归属见项目档案':'相关供料或后续加工项目')}let rf=RF().projects.find(x=>x.id===p.id);return rf&&['sulfate','refined'].includes(m.id)?(rf.role==='trade'?'贸易／下游关联主体':rf.products):p.classification||'产品角色见项目档案'}
function pcCapacity(m,p){let a=WIKI_ARTICLES[p.id],rf=RF().projects.find(x=>x.id===p.id);if(rf&&['sulfate','refined'].includes(m.id))return rf.capacity||'供销关联主体';if(m.id==='npi'){let n=NPI.projects.find(x=>x.id===p.npi_id);return (n?.capacity_verified?F(n.capacity_verified)+'；':'')+(n?.capacity_basis||n?.capacity_note||a?.facts.find(([k])=>/能力|产能/.test(k))?.[1]||'见项目设备与能力')}return a?.facts.find(([k])=>/能力|产能/.test(k))?.[1]||'见项目分期与产品能力'}
function pcHome(id){let m=pcMeta(id);if(!m)return missing();let d=PRODUCT_CHAPTERS[m.id],ps=pcProjects(m),rs=pcRows(m),period=[...rs.map(r=>r.date)].sort();return `<div class="pc-page" data-product="${m.id}"><div class="kicker"><a href="#/topics">品目研究与工艺</a> / ${m.en}</div><h1>${m.name}</h1><nav class="pc-switch" aria-label="切换品目">${PC_META.map(p=>`<a href="#/topic/${p.topic}" ${m.id===p.id?'aria-current="page"':''}>${p.name}</a>`).join('')}</nav><p class="lead">${E(d?.intro||K.topics.find(x=>x.id===m.topic)?.intro)}</p><div class="pc-summary"><div><strong>${ps.length}</strong><span>印尼关联研究项目</span></div><div><strong>${F(rs.length)}</strong><span>逐票样本记录</span></div><div><strong>${F(new Set(rs.map(r=>r.buyer)).size)}</strong><span>买方原始抬头</span></div><div><strong>${period[0]?.slice(0,7)||'—'}—${period.at(-1)?.slice(0,7)||'—'}</strong><span>出口样本覆盖月份</span></div></div><nav class="pc-toc" aria-label="专题章节">${[['pc-overview','发展历史与产业逻辑'],['pc-projects','企业、园区与产能'],['pc-trade','出口对象与流向'],['pc-relations','企业关系与协议'],['pc-history','项目时间线'],['pc-sources','资料说明']].map(([id,label])=>`<a href="#" data-scroll="${id}">${label}</a>`).join('')}</nav>
<section id="pc-overview"><h2>发展历史与产业逻辑</h2><div class="pc-prose">${pcProse(m)}</div></section>
<section id="pc-projects"><div class="section-head"><h2>企业、园区与产能</h2><a href="#/projects/${m.scope}">统一项目目录 →</a></div><p>这里包括生产、建设、历史转产和供销关联项目。每行列出本品目中的角色；“已投产”是项目状态，具体产品是否已投产看角色及分产品记录。</p><div class="filters"><input id="pcProjectQ" aria-label="专题项目搜索" placeholder="查企业、股东、产能或园区"><select id="pcProjectStatus" aria-label="专题项目状态"><option value="">全部项目状态</option>${Object.entries({operating:'已投产',partial:'部分运行／检修',halted:'停产',unbuilt:'未投产',trial:'试产',unknown:'待确认',trader:'贸易／下游'}).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div id="pcProjectRows"></div><button id="pcProjectMore">显示全部关联项目</button></section>
<section id="pc-trade"><h2>出口对象与贸易流向</h2><p>按出口样本追踪“哪家企业，发往哪个目的地，由谁接收”。选择年份或出口项目后，走势图、目的地、客户和供销表一起更新。点击目的地可继续筛选。</p><div class="filters"><select id="pcTradeYear" aria-label="专题出口年份"><option value="">全部样本年份</option>${[...new Set(rs.map(r=>r.date.slice(0,4)))].sort().map(y=>`<option>${y}</option>`).join('')}</select><select id="pcTradeProject" aria-label="专题出口项目"><option value="">全部出口项目</option>${[...new Set(rs.map(r=>r.project))].map(id=>({id,name:U().projects.find(p=>p.id===id)?.name||rs.find(r=>r.project===id).exporter})).sort((a,b)=>a.name.localeCompare(b.name)).map(x=>`<option value="${E(x.id)}">${E(x.name)}</option>`).join('')}</select><select id="pcTradeCountry" aria-label="专题目的地"><option value="">全部目的地</option>${[...new Set(rs.map(r=>r.country||'未列目的地'))].sort().map(c=>`<option value="${E(c)}">${E(pcCountry(c))}</option>`).join('')}</select><button id="pcTradeReset">重置流向</button></div><div id="pcTradeResults"></div><div class="actions"><a href="#/exports/~${m.trade}">打开完整逐票查询 →</a><button id="pcTradeDownload">下载当前流向明细 ↓</button></div></section>
<section id="pc-relations"><h2>企业之间的关系与协议</h2><p>投资关系解释谁参与项目，承购和供料关系解释产品如何移动。同属一个体系的企业，仍按具体法人及披露时期分别阅读。</p>${pcCases(m)}${pcContracts(m)}<div class="actions"><a href="#/graph">查看跨厂供料与加工关系图 →</a><a href="#/groups">全部集团档案 →</a></div><h3>参与本品目的母公司与集团</h3><div class="pc-groups">${U().companies.map(g=>({g,ps:ps.filter(p=>g.project_ids.includes(p.id))})).filter(x=>x.ps.length).map(({g,ps})=>`<details><summary>${E(g.name)} · ${ps.length}项关联项目</summary><p>${E(g.intro)}</p><a href="#/group/${g.id}">集团完整档案 →</a>${ps.map(p=>`<p>${A('project',p.id,p.name)}<span class="sub">${E(p.ownership)}</span></p>`).join('')}</details>`).join('')}</div></section>
<section id="pc-history"><h2>相关项目时间线</h2><p>从建设、首产到扩产、股权和销售安排，追踪本品目相关项目的完整历史。多产品项目保留上游与后端节点，事件文字说明具体产品；未来目标标为规划。</p><div class="filters"><select id="pcHistoryProject" aria-label="专题历史项目"><option value="">全部相关项目</option>${ps.map(p=>`<option value="${p.id}">${E(p.name)}</option>`).join('')}</select><select id="pcHistoryKind" aria-label="专题历史类型"><option value="">全部事件类型</option>${[...new Set(HX().events.filter(e=>ps.some(p=>p.id===e.project_id)).map(e=>e.kind||'历史'))].sort().map(k=>`<option>${E(k)}</option>`).join('')}</select><select id="pcHistoryYear" aria-label="专题历史年份"><option value="">全部年份</option>${[...new Set(HX().events.filter(e=>ps.some(p=>p.id===e.project_id)).map(e=>String(e.date).match(/(?:1[6-9]|20)\d{2}/)?.[0]).filter(Boolean))].sort().map(y=>`<option>${y}</option>`).join('')}</select><select id="pcHistoryOrder" aria-label="专题历史排序"><option value="asc">从早到晚</option><option value="desc">最新在前</option></select><button id="pcHistoryDownload">下载筛选事件</button></div><div id="pcHistoryChart" class="ix-plot"></div><p class="meta">点击年份查看当年事件。柱高表示资料库收录的事件数量。</p><div id="pcHistoryRows"></div><button id="pcHistoryMore">展开其余历史事件</button></section>
<section id="pc-sources"><h2>资料说明</h2><p>产业叙述依据正文所列企业公告、财报、园区及行业资料；企业表、股东关系和时间线连接同一项目档案。贸易统计使用用户提供的逐票样本，不作为全国全量统计；实际内销、厂内供料及未匹配记录另行判断。</p><p>${E(exNotes(m.trade))}</p><p>数量均为实物吨。2026年为截至样本最后发运日的部分年度；按全年总量直接与2025年比较会造成误读。项目数量包含多产品与历史对象，同一项目可出现在多个专题，不能跨品目相加。</p><div class="actions"><a href="library/product-chapters.json" download>下载六个品目研究正文 ↓</a><a href="#/sources">全部证据资料 →</a><a href="#/status-review">停产与待确认复查 →</a></div>${pcRefs(Object.values(EXPORTS.sources).filter(s=>s.url).map(s=>({title:s.label,url:s.url})))}<details class="reading-notes"><summary>需要再确认</summary>${(d?.pending||[]).map(p=>`<p>${E(p)}</p>`).join('')}</details></section></div>`}
function pcCases(m){return `<div class="pc-case-list">${m.cases.map(pcId).map(id=>{let p=U().projects.find(x=>x.id===id),w=WIKI_ARTICLES[id],rf=RF().projects.find(x=>x.id===id);return p?`<article class="pc-case"><h3>${A('project',id,p.name)}</h3><p>${E(['sulfate','refined'].includes(m.id)?rf?.customers||w?.summary:w?.summary||w?.intro||p.classification)}</p><p>${E(p.ownership)}</p><div class="actions"><a href="#/project/${id}">股东、工艺与客户全文 →</a><a href="#/exports/${id}~${m.trade}">本品目发货记录 →</a></div></article>`:''}).join('')}</div>`}
function pcContracts(m){return m.contracts.length?`<h3>供料与承购安排</h3>${m.contracts.map(id=>K.contracts.find(c=>c.id===id)).filter(Boolean).map(c=>`<article class="pc-contract"><h4>${E(c.parties_zh)}</h4><p class="meta">${E(c.instrument_type_zh)} · ${E(c.disclosure_or_agreement_date)}</p><p><strong>产品与安排：</strong>${E(c.product_zh)}。${E(c.quantity_or_allocation_zh)}</p><p><strong>为什么建立关系：</strong>${E(c.buyer_mechanism_zh)}</p><p><strong>期限与执行：</strong>${E(c.term_zh)}。${E(c.execution_evidence_zh)}</p>${pcRefs(c.sources.map(s=>({title:s.locator||'合同或关系资料',url:s.url})))}<details><summary>需要再确认</summary><p>${E(c.unresolved_zh)}</p></details></article>`).join('')}`:''}
const pcCountry=c=>({'China':'中国','Japan':'日本','South Korea':'韩国','Taiwan, China':'中国台湾','Singapore':'新加坡','Netherlands':'荷兰','Norway':'挪威','India':'印度','United Kingdom':'英国','United States':'美国','Philippines':'菲律宾','Malaysia':'马来西亚','Vietnam':'越南','Canada':'加拿大','Italy':'意大利','Germany':'德国','Brazil':'巴西','Turkey':'土耳其','Mexico':'墨西哥','South Africa':'南非'}[c]||c||'未列目的地');
let pcState={};
function pcDrawProjects(){let {m,ps}=pcState,q=$('pcProjectQ').value.trim().toLowerCase(),s=$('pcProjectStatus').value;let list=ps.filter(p=>(!s||opGet(p.id)?.key===s)&&(!q||[p.name,p.ownership,geoLoc(p.id)?.island,geoPlace(geoLoc(p.id)?.place_id)?.name,pcCapacity(m,p),pcRole(m,p)].join(' ').toLowerCase().includes(q)));$('pcProjectRows').innerHTML=`<p class="meta">${list.length}项 · ${pcState.allProjects?'全部显示':'先列前8项，可搜索或展开全部'}</p><div class="table-wrap"><table><thead><tr><th>企业／项目</th><th>本品目角色与项目状态</th><th>岛屿与园区</th><th>产能与设备口径</th><th>股东与关联集团</th></tr></thead><tbody>${list.slice(0,pcState.allProjects?Infinity:8).map(p=>`<tr><td>${A('project',p.id,p.name)}</td><td>${E(pcRole(m,p))}<span class="sub">${opBadge(p.id)}</span><span class="sub">${E(opGet(p.id)?.period)}</span></td><td>${geoLinks(p.id)}</td><td>${E(pcCapacity(m,p))}<span class="sub">${A('project',p.id,'设备、分期与能力来源 →')}</span></td><td>${U().companies.filter(g=>g.project_ids.includes(p.id)).map(g=>A('group',g.id,g.name)).join(' · ')}<span class="sub">${E(p.ownership)}</span></td></tr>`).join('')||'<tr><td colspan="5">没有匹配项目。</td></tr>'}</tbody></table></div>`;$('pcProjectMore').hidden=pcState.allProjects||list.length<=8}
function pcDrawTrade(){let {m}=pcState,y=$('pcTradeYear').value,p=$('pcTradeProject').value,c=$('pcTradeCountry').value,base=pcRows(m).filter(r=>(!y||r.date.startsWith(y))&&(!p||r.project===p)),rs=base.filter(r=>!c||(r.country||'未列目的地')===c);pcState.trade=rs;let countries={};for(let r of base){let k=r.country||'未列目的地';countries[k]??={key:k,value:0,rows:[]};countries[k].value+=r.counted||0;countries[k].rows.push(r)}let cs=Object.values(countries).sort((a,b)=>b.value-a.value),max=Math.max(1,...cs.map(x=>x.value)),edges={};for(let r of rs){let k=JSON.stringify([r.project,r.exporter,r.customer||r.buyer]);let e=edges[k]??={project:r.project,exporter:r.exporter,customer:r.customer,buyer:r.buyer,value:0,count:0,first:r.date,last:r.date};e.value+=r.counted||0;e.count++;if(r.date<e.first)e.first=r.date;if(r.date>e.last)e.last=r.date}let es=Object.values(edges).sort((a,b)=>b.value-a.value),dates=rs.map(r=>r.date).sort();$('pcTradeResults').innerHTML=`<p class="pc-trade-summary" aria-live="polite">${rs.length?`${E(dates[0])}—${E(dates.at(-1))} · ${F(rs.length)}条 · ${F(exSum(rs))}实物吨 · ${E(c?pcCountry(c):'全部目的地')}`:'当前筛选没有记录'}</p>${exRawNote(rs)}<h3>目的地分布</h3><div class="pc-destinations">${cs.map(x=>`<button class="pc-destination ${x.key===c?'selected':''}" data-country="${E(x.key)}" aria-pressed="${x.key===c}"><span>${E(pcCountry(x.key))}</span><span class="pc-track"><i style="width:${x.value/max*100}%"></i></span><b>${F(x.value)} 吨</b></button>`).join('')}</div><p class="meta">目的地按原记录列示，可能是贸易或仓储节点。点击选中，再次点击可取消。</p>${exAnnual(rs)}${ixTradeChart(rs,m.name+'出口走势')}<h3>主要买方</h3>${exBuyers(rs,12)}<h3>出口企业与买方之间的实际记录</h3><div class="table-wrap"><table><thead><tr><th>出口企业</th><th>买方</th><th>实物吨／记录</th><th>观察期间</th></tr></thead><tbody>${es.slice(0,20).map(e=>`<tr><td>${U().projects.some(p=>p.id===e.project)?A('project',e.project,U().projects.find(p=>p.id===e.project).name):E(e.exporter)}</td><td>${e.customer?A('customer',e.customer,e.buyer):E(e.buyer)}</td><td>${F(e.value)}<span class="sub">${e.count}条</span></td><td>${e.first}—${e.last}<span class="sub"><a href="#/exports/${E(e.project)}~${m.trade}">该项目逐票记录 →</a></span></td></tr>`).join('')||'<tr><td colspan="4">没有匹配记录。</td></tr>'}</tbody></table></div>${es.length>20?`<p class="meta">显示前20组，共${es.length}组；下载当前明细可查看全部。</p>`:''}`;document.querySelectorAll('[data-country]').forEach(b=>b.onclick=()=>{$('pcTradeCountry').value=c===b.dataset.country?'':b.dataset.country;pcDrawTrade()});ixMount();for(let id of IX.keys())if(!$(id))IX.delete(id)}
function pcDrawHistory(){let ps=new Set(pcState.ps.map(p=>p.id)),p=$('pcHistoryProject').value,k=$('pcHistoryKind').value,y=$('pcHistoryYear').value,desc=$('pcHistoryOrder').value==='desc';let base=HX().events.filter(e=>ps.has(e.project_id)&&(!p||e.project_id===p)&&(!k||(e.kind||'历史')===k)),years={};for(let e of base){let yr=String(e.date).match(/(?:1[6-9]|20)\d{2}/)?.[0];if(yr)(years[yr]??={key:yr,value:0}).value++}let buckets=Object.values(years).sort((a,b)=>a.key.localeCompare(b.key));$('pcHistoryChart').innerHTML=buckets.length?ixSvg(buckets,{selected:y,unit:'项事件'}):'';ixMarkEvents($('pcHistoryChart'),buckets,b=>{$('pcHistoryYear').value=y===b.key?'':b.key;pcDrawHistory()},'项事件');let es=base.filter(e=>!y||String(e.date).match(/(?:1[6-9]|20)\d{2}/)?.[0]===y).sort((a,b)=>(hxSort(a)-hxSort(b))*(desc?-1:1));pcState.events=es;$('pcHistoryRows').innerHTML=`<p class="meta">${es.length}项事件 · ${new Set(es.map(e=>e.project_id)).size}个项目</p><div class="timeline">${es.slice(0,pcState.allHistory?Infinity:20).map(e=>hxEvent(e,true)).join('')||'<p>当前筛选没有事件。</p>'}</div>`;$('pcHistoryMore').hidden=pcState.allHistory||es.length<=20}
function pcBind(key,id){if(key!=='topic'||!pcMeta(id))return;let m=pcMeta(id);pcState={m,ps:pcProjects(m),allProjects:false,allHistory:false};pcDrawProjects();pcDrawTrade();pcDrawHistory();$('pcProjectQ').oninput=pcDrawProjects;$('pcProjectStatus').onchange=pcDrawProjects;$('pcProjectMore').onclick=()=>{pcState.allProjects=true;pcDrawProjects()};for(let id of ['pcTradeYear','pcTradeProject','pcTradeCountry'])$(id).onchange=pcDrawTrade;$('pcTradeReset').onclick=()=>{for(let id of ['pcTradeYear','pcTradeProject','pcTradeCountry'])$(id).value='';pcDrawTrade()};$('pcTradeDownload').onclick=()=>ixDownload([['记录','日期','项目','出口商','买方','目的地','实物吨','参考计入实物吨'],...pcState.trade.map(r=>[r.id,r.date,r.project,r.exporter,r.buyer,r.country,r.tonnes,r.counted])],m.name+'出口流向.csv');for(let id of ['pcHistoryProject','pcHistoryKind','pcHistoryYear','pcHistoryOrder'])$(id).onchange=pcDrawHistory;$('pcHistoryMore').onclick=()=>{pcState.allHistory=true;pcDrawHistory()};$('pcHistoryDownload').onclick=()=>ixDownload([['项目','日期','类型','事件','说明','来源'],...pcState.events.map(e=>[e.project_id,e.date,e.kind,e.label,e.detail,e.source_url])],m.name+'项目历史.csv')}
const pcOldArticle=article;article=function(type,id){return type==='topic'&&pcMeta(id)?pcHome(id):pcOldArticle(type,id)};
const pcOldDirectory=directory;directory=function(type){if(type!=='topic')return pcOldDirectory(type);return `<div class="kicker">产品 · 企业 · 贸易 · 历史</div><h1>品目研究与生产工艺</h1><p class="lead">从一个品目进入，阅读它在印尼的发展历史、生产企业、股东与供销关系，再追踪出口流向和项目时间线。</p><div class="pc-topic-grid">${PC_META.map(m=>`<article><span class="num">${m.en}</span><h2>${A('topic',m.topic,m.name)}</h2><p>${E(PRODUCT_CHAPTERS[m.id]?.intro)}</p><p class="meta">${pcProjects(m).length}项关联研究项目 · ${F(pcRows(m).length)}条出口样本</p>${A('topic',m.topic,'进入完整品目研究 →')}</article>`).join('')}</div><h2>生产工艺与商业安排</h2><div class="entries">${K.topics.filter(t=>!pcMeta(t.id)).map(t=>`<article class="entry"><h3>${A('topic',t.id,t.name)}</h3><p>${E(t.intro)}</p></article>`).join('')}</div>`};
const pcOldMhHome=mhHome;mhHome=function(){return `<div class="note neutral"><h2><a href="#/topic/mhp">MHP完整品目研究 →</a></h2><p>发展历史、企业、股东与承购、出口流向和项目时间线。</p></div>`+pcOldMhHome()};
const pcOldRfHome=rfHome;rfHome=function(){return `<div class="actions"><a href="#/topic/nickel-sulphate">硫酸镍完整品目研究 →</a><a href="#/topic/refined-nickel">精炼镍完整品目研究 →</a></div>`+pcOldRfHome()};

const pcOldWiki=wikiArticle;wikiArticle=function(id){let html=pcOldWiki(id),items=PC_META.filter(m=>pcProjects(m).some(p=>p.id===id));return items.length?html.replace('</h1>','</h1><div class="actions pc-backlinks" aria-label="相关品目研究">'+items.map(m=>A('topic',m.topic,m.name+'专题 →')).join('')+'</div>'):html};
