function projectMapURL(m){const box=m.bbox.join(',');return 'https://www.openstreetmap.org/export/embed.html?bbox='+encodeURIComponent(box)+'&layer=mapnik'+(m.marker?'&marker='+encodeURIComponent(m.marker.join(',')):'')}
function projectMapLinks(m){const [w,s,e,n]=m.bbox,lat=m.marker?.[0]??(s+n)/2,lon=m.marker?.[1]??(w+e)/2,zoom=Math.max(2,Math.min(14,Math.round(Math.log2(360/(e-w)))));return {large:'https://www.openstreetmap.org/'+(m.marker?'?mlat='+lat+'&mlon='+lon:'')+'#map='+zoom+'/'+lat+'/'+lon,google:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(m.marker?lat+','+lon:m.label)}}
function projectMapBlock(id){
 const loc=geoLoc(id),m=loc&&window.PROJECT_MAPS?.places[loc.place_id];if(!m)return '';
 const wide=PROJECT_MAPS.regions[loc.island_id],hasWide=wide&&JSON.stringify(wide.bbox)!==JSON.stringify(m.bbox),[w,s,e,n]=m.bbox;
 const {large,google}=projectMapLinks(m);
 return `<section class="project-map" aria-label="项目位置地图" data-project="${E(id)}"><div class="project-map-head"><strong>项目位置</strong><span>${E(m.level)}</span></div><iframe title="${E(m.label)}地图" src="${E(projectMapURL(m))}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe><div class="project-map-caption"><strong>${E(m.label)}</strong><span>${m.level==='园区位置'?'标记为所在园区参考位置':m.level==='工业区范围'?'显示工业区及周边地形':'显示所在地区范围'}</span></div>${hasWide?`<div class="project-map-switch" role="group" aria-label="地图范围"><button type="button" data-map-view="near" aria-pressed="true">${m.level==='区域示意'?'所在地区':'园区附近'}</button><button type="button" data-map-view="wide" aria-pressed="false">${E(wide.label)}</button></div>`:''}<div class="project-map-links"><a href="${E(large)}" target="_blank" rel="noopener">打开大地图 ↗</a><a href="${E(google)}" target="_blank" rel="noopener">Google 地图 ↗</a>${m.source?`<a href="${E(m.source)}" target="_blank" rel="noopener" title="${E(m.source_title)}">位置来源 ↗</a>`:''}</div></section>`;
}
function projectMapBind(){document.querySelectorAll('.project-map').forEach(el=>{const loc=geoLoc(el.dataset.project),near=PROJECT_MAPS.places[loc.place_id],wide=PROJECT_MAPS.regions[loc.island_id];el.querySelectorAll('[data-map-view]').forEach(b=>b.addEventListener('click',()=>{const m=b.dataset.mapView==='wide'?wide:near;if(!m)return;const frame=el.querySelector('iframe');frame.src=projectMapURL(m);frame.title=m.label+'地图';const links=projectMapLinks(m),anchors=el.querySelectorAll('.project-map-links a');anchors[0].href=links.large;anchors[1].href=links.google;el.querySelectorAll('[data-map-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));el.querySelector('.project-map-caption strong').textContent=m.label;el.querySelector('.project-map-caption span').textContent=b.dataset.mapView==='wide'?'所在岛屿范围':near.level==='园区位置'?'标记为所在园区参考位置':near.level==='工业区范围'?'显示工业区及周边地形':'显示所在地区范围';}))})}
