const RF=()=>window.REFINING;
const rfName=k=>({sulfate:'硫酸镍',refined:'精炼镍'}[k]||k);
function rfHome(){return `<div class="kicker">印尼 / 镍的下游精炼</div><h1>硫酸镍与精炼镍</h1><p class="lead">硫酸镍把镍送入电池材料和化工生产，精炼镍则把镍制成高纯度金属。印尼的冶炼企业正在把MHP和冰镍继续加工，向这两类产品延伸。</p><div class="actions"><a href="#/exports/~sulfate">硫酸镍逐票出口 →</a><a href="#/exports/~refined">精炼镍逐票出口 →</a><a href="library/refining-projects.csv" download>项目与产能表 ↓</a></div><div class="filters"><select id="rfProduct" aria-label="精炼产品"><option value="">全部产品</option><option value="sulfate">硫酸镍</option><option value="refined">精炼镍</option></select><select id="rfRole" aria-label="项目类型"><option value="">工厂与相关主体</option><option value="plant">生产／建设项目</option><option value="trade">贸易与下游主体</option></select><input id="rfQ" aria-label="搜索精炼项目" placeholder="查工厂、股东、园区或原料"></div><div id="rfResults"></div><section class="wiki-prose"><h2>从镍中间品到两类成品</h2><p>MHP和高冰镍都可以作为进一步精炼的原料。工厂先把镍转入溶液，再去除铁、铜等杂质，得到适合下游生产的含镍溶液。接下来的产品选择，取决于工厂配置的结晶、电积或其他金属回收设施。</p><div class="rf-paths"><div><h3>硫酸镍路线</h3><p>${A('topic','wet-refining','浸出与净化')} → 硫酸镍溶液 → 结晶 → 硫酸镍晶体</p><p>六水硫酸镍含有结晶水，实物重量与镍金属量差别很大。用于前驱体生产的溶液，也可能在同一厂内直接输送，未必结晶后出口。</p></div><div><h3>精炼镍路线</h3><p>含镍原料 → 浸出与净化 → 电积 → 镍板／阴极镍</p><p>电积利用电流使溶液中的镍沉积为金属。达到相应规格并完成注册的品牌，可以进入交易所交割体系；直接销售仍需经过买方的质量和供应商审核。</p></div></div><h2>为什么在印尼继续向下加工</h2><p>过去，印尼不少项目把MHP或冰镍出口到境外，再加工成镍盐或金属镍。把精炼环节放到园区内，可以衔接附近的原料、公用工程和港口，也使企业有机会根据客户需求选择出售中间品、硫酸镍或金属。HPL、青美邦和晨曦体现了一体化延伸；鼎兴、永恒和华翔则需要作为各自的精炼主体阅读。</p><p>多产品项目的产能存在共享关系。例如，晨曦的镍当量设计能力覆盖MHP、硫酸镍和阴极镍三条产品去向，不能把每个名称下的同一份镍重复相加。项目表保留各家公司披露的单位、时点与建设状态。</p><h2>从买方看产品用途</h2><p>镍盐买方可能是前驱体或专业化学品生产企业，也可能是集团贸易平台。金属镍则可以流向贸易、合金、电镀及其他工业客户。逐票中的交易抬头、实际加工厂和最终电池或汽车品牌是不同层次，已披露的具体关系写入各项目与客户词条。</p><h2>出口资料覆盖</h2><p>新增明细来自用户提供的全品种出口资料。保留1,072条精炼镍和242条硫酸镍原记录，并将同票特征重复项单列；这份样本不是印尼所有工厂的全部销售。</p><p>${E(RF().trade_note||'')}</p><div class="actions"><a href="library/refining-export-rows.csv" download>新增产品原记录与复核标记 ↓</a><a href="library/refining-research.json" download>项目研究资料 ↓</a></div><h2>参考资料</h2><ol>${RF().overview_sources.map(s=>`<li><a href="${E(s.url)}" target="_blank" rel="noopener">${E(s.title)}</a></li>`).join('')}</ol></section>${RF().pending?.length?`<details class="reading-notes"><summary>需要再确认</summary>${RF().pending.map(x=>`<p>${E(x)}</p>`).join('')}</details>`:''}`}
function rfRows(){let q=$('rfQ').value.toLowerCase(),k=$('rfProduct').value,role=$('rfRole').value,a=RF().projects.filter(x=>(!k||x.product_keys.includes(k))&&(!role||x.role===role)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));$('rfResults').innerHTML=`<p class="meta">${a.length}个项目／主体 · 同一法律主体的多种产品合并展示</p><div class="table-wrap"><table class="rf-table"><thead><tr><th>项目与地点</th><th>投产与运行状态</th><th>产品／当前阶段</th><th>披露产能与单位</th><th>原料与工艺</th><th>股东／销售</th></tr></thead><tbody>${a.map(x=>`<tr><td>${A('project',x.id,x.name)}<span class="sub">${E(x.legal)}</span><p>${geoLinks(x.id)}</p></td><td>${opCell(x.id)}</td><td>${E(x.products)}<p>${E(x.status)}</p></td><td>${E(x.capacity)}</td><td>${E(x.feed)}<p>${E(x.process)}</p></td><td>${E(x.ownership)}<p>${exportMiniLinks(x.id)}</p></td></tr>`).join('')}</tbody></table></div>`}
function rfBind(k){if(k==='refining'){rfRows();['rfProduct','rfRole'].forEach(id=>$(id).onchange=rfRows);$('rfQ').oninput=rfRows}}
const rfOldProducts=uProducts;uProducts=function(p){return [rfOldProducts(p),...(p.refining_products||[]).map(rfName)].filter(Boolean).join(' · ')};
const rfOldCustomer=uCustomer;uCustomer=function(id){let c=U().customers.find(c=>c.id===id),rows=exBase('customer:'+id).filter(r=>['sulfate','refined'].includes(r.product));let s=rfOldCustomer(id);if(!rows.length)return s;return s+`<section class="wiki-prose"><h2>硫酸镍与精炼镍采购</h2>${(c.refining_sections||[]).map(x=>`<section><h3>${E(x.title)}</h3>${x.paragraphs.map(t=>`<p>${E(t)}</p>`).join('')}</section>`).join('')}${exKinds(rows).map(k=>{let a=rows.filter(r=>r.product===k),sup=[...new Set(a.map(r=>r.project))];return `<h3>${rfName(k)}</h3>${exAnnual(a)}<p>来源项目：${sup.map(id=>A('project',id,U().projects.find(p=>p.id===id)?.name||id)).join(' · ')}</p>${exLink('customer:'+id,k,'查看逐票与出口企业 →')}`}).join('')}${c.refining_sources?.length?`<h3>资料来源</h3><ol>${c.refining_sources.map(s=>`<li><a href="${E(s.url)}" target="_blank">${E(s.title)}</a></li>`).join('')}</ol>`:''}</section>`};
const rfOldDirectory=uDirectory;uDirectory=function(k){let html=rfOldDirectory(k);return k==='projects'?html:html.replace('全部产品资料</option>','全部产品资料</option><option value="sulfate">硫酸镍</option><option value="refined">精炼镍</option>').replace('镍铁、冰镍和MHP采购','镍铁、冰镍、MHP、硫酸镍和精炼镍采购')};
const rfOldGroup=uGroup;uGroup=function(id){let html=rfOldGroup(id),c=U().companies.find(c=>c.id===id);if(!c)return html;let ps=RF().projects.filter(p=>c.project_ids.includes(p.id));if(!ps.length)return html;let chapter=`<section class="refining-group"><h2>硫酸镍与精炼镍布局</h2>${ps.map(p=>`<section><h3>${A('project',p.id,p.name)}</h3><p>${E(p.products)}。${E(p.status)}。</p><p>${E(p.ownership)}</p><p>${E(p.capacity)}</p><p>${exportMiniLinks(p.id)}</p></section>`).join('')}${c.refining_sources?.length?`<h3>相关投资披露</h3><ol>${c.refining_sources.map(s=>`<li><a href="${E(s.url)}" target="_blank" rel="noopener">${E(s.title)}</a></li>`).join('')}</ol>`:''}<a href="#/refining">查看印尼精炼项目全表 →</a></section>`;return html.replace('</article>',chapter+'</article>')};
const rfOldWikiArticle=wikiArticle;wikiArticle=function(id){let html=rfOldWikiArticle(id);return RF().projects.some(p=>p.id===id)?html.replace('<p class="project-location">','<div class="actions"><a href="#/refining">硫酸镍与精炼镍产业研究 →</a></div><p class="project-location">'):html};
function rfSourceList(){let m=new Map();for(const p of RF().projects)for(const s of p.sources){if(!m.has(s.url))m.set(s.url,{...s,projects:[]});let r=m.get(s.url);if(!r.projects.includes(p.id))r.projects.push(p.id)}return [...m.values()]}
const rfOldDrawSources=drawSources;drawSources=function(){rfOldDrawSources();let q=$('sourceQ').value.toLowerCase(),ss=rfSourceList().filter(s=>JSON.stringify(s).toLowerCase().includes(q));$('sourceResults').insertAdjacentHTML('afterbegin',`<section><h2>硫酸镍与精炼镍资料 · ${ss.length}项</h2>${ss.map(s=>`<div class="source-entry"><h3><a href="${E(s.url)}" target="_blank" rel="noopener">${E(s.title)}</a></h3><p>${s.projects.map(id=>A('project',id,RF().projects.find(p=>p.id===id).name)).join(' · ')}</p></div>`).join('')}</section>`)};
const rfOldArticle=article;article=function(type,id){let html=rfOldArticle(type,id);return type==='topic'&&['nickel-sulphate','wet-refining'].includes(id)?html+`<section><h2>印尼的下游精炼项目</h2><p>这些工厂把中间品继续加工为硫酸镍或金属镍。点击项目可阅读建设历史、原料、股东与客户。</p>${geoTable(U().projects.filter(p=>p.refining_products?.length))}<a href="#/refining">硫酸镍与精炼镍研究 →</a></section>`:html};
